### ISSUE TITLE
Ошибки в плагине

### ISSUE THREAD

**Issue by mcunit** [Teplitsa/Leyka#10]
Не появляется описание платежной системы Яндекс.Деньги для физических лиц и Описание платежа по банковской карте с помощью системы Яндекс.Деньги для физических лиц. В настройках плагина такое описание есть, однако на сайте оно не появляется.

![01](https://cloud.githubusercontent.com/assets/10049094/5265501/1276af2c-7a6d-11e4-93c7-9ee8fbbd0487.jpg)
![02](https://cloud.githubusercontent.com/assets/10049094/5265502/12830b50-7a6d-11e4-8537-ac3c4383aee4.jpg)
![03](https://cloud.githubusercontent.com/assets/10049094/5265503/128f33bc-7a6d-11e4-9ef8-f72e610ce076.jpg)
![04](https://cloud.githubusercontent.com/assets/10049094/5265504/12a07fa0-7a6d-11e4-9c2a-32958024a49c.jpg)

**Comment by Ahaenor** [comment]
Добрый день!

> Виджет "Список пожертвований" заработал, но не на главной странице сайта, а на странице платежа. Это корректно, так и должно быть?

По умолчанию, виджет показывает список пожертвований для текущей кампании. Но, т.к. это возможно только для страницы кампании, на главной виджет не выводится.

Для того, чтобы виджет показывал список пожертвований безотносительно к кампании, нужно в его настройках найти опцию "ID кампании" и указать там пустое значение (не "0").

**Comment by Ahaenor** [comment]
Ошибки, связанные с поведением спасибо-писем, были исправлены.
