### ISSUE TITLE
Ребилы по регулярным платежам криво отображаются в списке пожертвований

### ISSUE THREAD

**Issue by lerniri** [Teplitsa/Leyka#100]
Добрый день, 

Столкнулись с проблемой не совсем корректного отображения ребилов по регулярным платежам. Наша конечная цель - наличие ребилов в истории платежей. В настоящее время этого не происходит. 

Смотрим в админку, в список пожертвований и видим это: 

![screenshot_041216_063254_pm](https://cloud.githubusercontent.com/assets/8013810/14465804/fbee5f64-00dc-11e6-8644-ee5c93170284.jpg)

Если посмотреть на оригинальную транзакцию, то в качестве ее колбека отображается последний ребил пришедший с хронопея. 

Подскажите, как должен работать данный функционал.

**Comment by Ahaenor** [comment]
Добрый день.

В случае с Хронопей, рекарринг устроен так.

1. У Хронопей есть параметр customer_id, он передаётся в POST при каждом коллбэке. Если платёж рекуррентный и первый в подписке, он сохраняется у пожертвования в Лейке в поле post_meta с названием "_chronopay_customer_id".

2. Далее, с некоторой периодичностью (она зависит от настроек продукта в Хронопее), напр., месяц, Хронопей присылает на сайт новые коллбэки.

В каждом коллбэке передаётся:
- product_id, который указывает, что платёж именно рекуррентный (значение параметра в POST должно совпадать со значением настройки в Лейке),
- значение customer_id, которое указывает, к какой рекуррентной подписке принадлежит платёж.

Получив такой коллбэк, Лейка пытается найти изначальный платёж в подписке. Для этого ищется самое раннее (по дате поста) пожертвование (пост типа leyka_donation) со статусом funded, типом rebill и post_meta-полем "_chronopay_customer_id", чьё значение совпадало бы с переданным в коллбэке.

Если такой пост-пожертвование находится, новое пожертвование (т.е. свежий ребилл в подписке) получает все его параметры (соотв. кампанию, имя/почту донора и пр.).

Если же пост изначального пожертвования не находится, то просто создаётся новый пост-пожертвование с типом "rebill", статусом "funded" и параметром "customer_id", переданным в коллбэке.

Насколько я понимаю, последний абзац - это как раз ваш случай. Проверьте, есть ли инитный платёж в рекуррентной цепочке, и имеет ли он статус "funded".

**Comment by lerniri** [comment]
Как всегда, спасибо за подробную информацию. На первый взгляд у нас есть все, что нужно, для того чтобы ребил нашел своего родителя. Попробуем подебажить. Отпишусь о результате

**Comment by lerniri** [comment]
Возвращаюсь к вам. Итак, я убедилась, что изначальное пожертвование находится и информация из него даже передается в новую транзакцию.. ( дебажила функцию _handle_service_calls ) Но в конечном итоге я все равно получаю безымянную транзакцию с нулевой суммой и т.д . Что посоветуете ?

![screenshot_041516_114626_am](https://cloud.githubusercontent.com/assets/8013810/14556208/b418ea5e-02ff-11e6-84bd-3acc15efc551.jpg)

**Comment by Ahaenor** [comment]
Странная ситуация. Но, если параметры в пр. части оператора присваивания в порядке, а в левой - уже нет, то проблемы, очевидно, в работе оператора.

Присваивание этих параметров происходит в методе __set() класса Leyka_Donation. В зав. от значения первого аргумента этого метода, вызываются различные update_post_meta().

Возможно, проблема именно на этом уровне - в работе с метаданными пожертвования.

Мы не встречали подобных багов - пжлст, поделитесь причиной, когда выясните.

**Comment by lerniri** [comment]
Прошу прощения, запутала немного вас. Данные в $donation присваиваются от инитной транзакции. То есть эхо мне выдает $donation такой же как $init_recurrent_payment. Уже когда я смотрю в админку лейки , в списке пожертвований транзакция отображается с пустыми значениями. Как будто что-то ее по пути обнуляет.

**Comment by lerniri** [comment]
@Ahaenor очень жду совета. Что может происходить с $donation после _handle_service_calls , что обнуляет ее данные ? Возможно при сохранении хук какой-нибудь? Как написала в предыдущем сообщении, присваивание конечно же в порядке.

**Comment by Ahaenor** [comment]
Ок, понял вас. Повторюсь, ситуация странная - раньше такого никогда не видели.

Я бы искал ошибку в одном из 2-х мест:

1. Первое открытие дочернего пожертвования в админке. Нужно подтвердить, что зануление инфо происходит до этого открытия, а не во время.
2. Работа методов add_donation_specific_data() и set_donation_specific_data() из класса Leyka_Chronopay_Gateway. Они отвечают за изменение параметров пожертвования, специфичных для Хронопей. Возможно, они вызываются неправильно?

Если оба эти варианта не сработают, я бы исследовал логи БД. А именно, все запросы UPDATE, которые затрагивали таблицу *_post_meta, т.к. у нас ситуация, когда сперва метаданные пожертвования в порядке (при его создании в коллбэке), а потом они становятся нулевыми.

**Comment by lerniri** [comment]
@Ahaenor , спасибо за хинты. 

Я начала с БД. Судя по логам происходит что-то весьма странное. 

Initial transaction = 1376
Rebill - 1783

Лейка находит инитную транзакцию, собирает ее мета данные, но апдейтит саму же ее, вместо ребила. 
```
SELECT meta_id FROM wp_postmeta WHERE meta_key = 'leyka_campaign_id' AND post_id = 1376

SELECT * FROM wp_postmeta WHERE meta_id = 7058

UPDATE `wp_postmeta` SET `meta_value` = '779' WHERE `post_id` = 1376 AND `meta_key` = 'leyka_campaign_id'

SELECT meta_id FROM wp_postmeta WHERE meta_key = 'leyka_donation_amount' AND post_id = 1376

SELECT * FROM wp_postmeta WHERE meta_id = 7051

UPDATE `wp_postmeta` SET `meta_value` = '100' WHERE `post_id` = 1376 AND `meta_key` = 'leyka_donation_amount'
```

Пока мне не очень хорошо удается подебажить сам код, может быть вы посоветуете что-нибудь. Я работаю в phpStorm + xDebug. Эмулирую ребил через Postman. Точки останова расставлены в процедуре _handle_service_calls, но по всей видимости такой подход не работает.

**Comment by Ahaenor** [comment]
Ок, понял вас. Возможно, я понял, в чём дело.

Пжлст, возьмите сейчас код из ветки dev и попробуйте протестировать с ним.

**Comment by lerniri** [comment]
@Ahaenor спасибо, сейчас буду тестить. Изменения были только в leyka-class-chronopay-gateway.php ?

**Comment by Ahaenor** [comment]
Не только. Вы можете обновить все файлы плагина.

2016-05-17 18:18 GMT+03:00 lerniri <notifications@github.com>:

**Comment by lerniri** [comment]
@Ahaenor  - работает! Ребил теперь обновляется данными, но почему-то остается в статусе 'submitted'.

**Comment by Ahaenor** [comment]
Ок, попробуйте взять код из dev ещё раз и проверить. Кажется, я нашёл баг.
Теперь должно быть нормально.

2016-05-19 16:35 GMT+03:00 lerniri <notifications@github.com>:

**Comment by lerniri** [comment]
@Ahaenor, сейчас отлично! Ребил получил 'funded' статус.  Когда примерно ожидать официальный апдейт ? Btw, У вас в дев версии есть некоторые изменения темплейта платежной формы, верно? Или я давно не обновлялась.  У меня стили съехали немного. 

**Dev**

![leyka_pmt_form_dev](https://cloud.githubusercontent.com/assets/8013810/15399805/c3ded46e-1df1-11e6-9546-62f4d326b753.png)

**Prod**

![leyka_pmt_form_prd](https://cloud.githubusercontent.com/assets/8013810/15399804/c3de6cc2-1df1-11e6-873f-4f0e4fc77d63.png)

**Comment by Ahaenor** [comment]
Да, шаблон формы немного изменён. Причина в том, что теперь доступен
смешанный тип поля суммы (варианты размера платежа + инпут для
произвольного размера).

Если вы использовали стандартную форму Лейки (и её стили), проблем быть не
должно. Но, судя по тому, что вёрстка у вас поехала, её нужно будет
поправить в стилях темы вашего сайта.

19 мая 2016 г., 18:45 пользователь lerniri <notifications@github.com>
написал:
