### ISSUE TITLE
Умный платеж Яндекс.Касса

### ISSUE THREAD

**Issue by radioset** [Teplitsa/Leyka#101]
Добрый день.
Реализуйте [умный платеж](https://kassa.yandex.ru/features#smart-checkout) от Яндекс.Кассы (юр. лица).
Когда способ платежа выбирается  на стороне Яндекс.Кассы.
Это улучшит эстетический вид формы пожертвования.
Не будут отображаться способы оплаты и одна кнопка под формой пожертвовать.
Форма передаст на Яндекс.Кассу пустой параметр **paymentType=''**
И на стороне Яндекс.Кассы пользователю будут предложены популярные варианты оплаты и на основе анализа его предыдущих платежей в других магазинах.

[Документация](https://tech.yandex.ru/money/doc/payment-solution/examples/examples-payment-docpage/)

[Демо](https://invis.io/Z56NPHD23)

**Comment by GSuvorov** [comment]
присылайте пуллреквест!

**Comment by Ahaenor** [comment]
Добрый день!

Умный платёж добавлен в гейтвей Яндекс.денег. Он будет доступен после апдейта Лейки до версии 2.3 (сейчас релиз готовится к выпуску).

Спасибо за запрос.
