### ISSUE TITLE
Получение списка людей, сделавших платеж

### ISSUE THREAD

**Issue by baimurzin** [Teplitsa/Leyka#104]
Есть ли возможность получиться список людей, сделавших платеж?

**Comment by Ahaenor** [comment]
Добрый день.

Вы можете экспортировать пожертвования в формат MS Excel, а затем взять из
этого списка уникальные сочетания "имя донора + email".

Работу с донорами как с отдельным разделом плагина предполагается добавить
в будущих версиях плагина.

2016-05-11 18:10 GMT+03:00 Vladislav <notifications@github.com>:

**Comment by baimurzin** [comment]
@Ahaenor А где это сделать - экспорт?
Спасибо за ответ

**Comment by Ahaenor** [comment]
Админ. раздел сайта - Лейка - Пожертвования - Кнопка "экспорт (csv)" над списком пожертвований.
