### ISSUE TITLE
Печать и отправка квитанции об оплате

### ISSUE THREAD

**Issue by baimurzin** [Teplitsa/Leyka#105]
Есть ли какой-нибудь callback, по которому можно получить информацию о платеже, в целях сделать квитанция плательщику?

**Comment by Ahaenor** [comment]
Добрый день.

Да, есть несколько хуков для момента выполнения пожертвования.

В какой именно момент вы хотите создавать/отправлять квитанцию?
Например, это можно делать после подтверждения платежа.

11 мая 2016 г., 18:11 пользователь Vladislav <notifications@github.com>
написал:

**Comment by baimurzin** [comment]
@Ahaenor Спасибо за отклик.
Да после подтверждения платежа. А можно получать не только информацию о платеже, а некоторую дополнительную информацию, которую пользователь может ввести при оплате?

**Comment by Ahaenor** [comment]
> Да после подтверждения платежа.
 - Платежи переходят в статус "завершено" в процессе выполнения метода _handle_service_calls($call_type = '') класса Leyka_Gateway.

Этот метод висит на action-хуке 'leyka_service_call-{ид-нужного-вам-гейтвея}' с приоритетом 10.
Вы можете использовать именно этот хук. Например:

```
add_action('leyka_service_call-'.$this->_id, 'your_quittance_sending_function', 11);

your_quittance_sending_function($call_type = '') {

    if($call_type == 'тип "успешного" коллбэка у вашего гейтвея') {

        // Получить данные пожертвования из $_POST
        // Отправить донору письмо с квитанцией и т.д.
    }
}
```

> А можно получать не только информацию о платеже, а некоторую дополнительную информацию, которую пользователь может ввести при оплате?

 - Только если гейтвей присылает эту информацию в $_POST при коллбэках. Чтобы ответить точнее, нужно знать, с каким гейтвеем вы работаете, и какую информацию он может возвращать.
