### ISSUE TITLE
При активации лейки перестают работать виджеты из VisualComposer

### ISSUE THREAD

**Issue by zaur** [Teplitsa/Leyka#106]
Здравствуйте!

Мы попытались интегрировать лейку на сайт нашего благотворительного фонда http://fondleki.ru.
Мы используем плагин VisualComposer для генерации главной страницы - там несколько аяксовых блоков, которые подгружают новости и другие типы постов.
Однако при активации лейки весь этот функционал ломается. Я приложил скриншот - аяксовые запросы падают с 500й ошибкой (хотя по идее они никакого отношения к Лейке не имеют).
Галочку "Загрузка скриптов и стилей плагина по необходимости" включал/выключал - не помогает.

Подскажите, пожалуйста, как быть.

<img width="696" alt="screen shot 2016-05-24 at 01 42 26" src="https://cloud.githubusercontent.com/assets/965068/15485512/d22f13c8-2150-11e6-90c6-dfba7e7ce05c.png">

**Comment by Ahaenor** [comment]
Добрый день.

Спасибо за репорт. Ранее мы не встречали этого конфликта - о причинах без исследования трудно сказать что-то определённое.

Мы проверим причину.

**Comment by zaur** [comment]
я могу как-нибудь помочь в диагностике? может, логи какие-нибудь скинуть?
очень хотим потестировать интеграцию с яндексом, но не можем.

**Comment by Ahaenor** [comment]
1. Если возможно, включите в WordPress режим WP_DEBUG. Проверим, выводятся ли какие-то нотайсы при этих отказах.

Кроме того, пригодится поискать причину в логах ошибок PHP. Пожалуйста, сообщите, если при загрузке главной с этими ошибками в логах появляется какой-то notice, warning или error.

2. Я захожу на главную сайта и не вижу ошибок 500 в Firebug. Возможно, потому, что я не залогинен на сайте. Проверьте это, пожалуйста.

**Comment by zaur** [comment]
1. вот такие ошибки:
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 12800 bytes) in /public_html/wp-content/plugins/js_composer/include/params/vc_grid_item/templates.php on line 156

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 49152 bytes) in /public_html/wp-content/plugins/js_composer/include/params/vc_grid_item/templates.php on line 140



2. Вы не видели ошибок, потому что я отключил лейку, поскольку главная перестает работать :)

**Comment by zaur** [comment]
Проблема решилась увеличением порога памяти.
https://wordpress.org/support/topic/fatal-error-allowed-memory-size-of-67108864-bytes-exhausted-1

**Comment by Ahaenor** [comment]
Ок, спасибо. Закрываем таск.
