### ISSUE TITLE
Отключение благодарственной авторассылки донорам

### ISSUE THREAD

**Issue by shum16** [Teplitsa/Leyka#108]
Подскажите, есть ли возможность отключения рассылки донорам? Не нашел такой опции.
Суть в том, что мы хотели бы использовать свою собственную централизованную рассылку по всем видам пожертвований. Если не отключить вашу, письма буду дублироваться.

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за вопрос.

Сейчас отключить рассылку спасибо-писем по донорам невозможно - при разработке мы предполагали, что получать их доноры должны всегда.

Но мы готовы добавить это как опцию в следующей версии плагина.

**Comment by shum16** [comment]
Спасибо, Лев! Будем очень признательны )
Если есть возможность, не подскажите, где лучше отключить это в коде плагина? Нам придется пойти временно на такую варварскую меру..

**Comment by Ahaenor** [comment]
В принципе, в варварстве нет нужды)

Вы можете взять из ветки dev следующие файлы:

- /inc/leyka-class-donation.php
- /inc/leyka-class-options-allocator.php
- /inc/leyka-options-meta.php

Скопируйте их с заменой в папку /inc вашей Лейки. После этого в настройках плагина в разделе Email должна появиться новая опция-чекбокс "Send a thankful email to a donor on each funded donation".
Снимите с неё отметку и сохраните опции. После этого спасибо-письма донорам отправляться не будут.

Пожалуйста, сообщите, если что-то будет работать некорректно.

**Comment by shum16** [comment]
Вот это я понимаю онлайн-разработка! Супер поддержка! Спасибо большущее!

**Comment by Ahaenor** [comment]
Пожалуйста, мы рады быть вам полезны.

P. S. Если вам будет несложно, мы были бы благодарны за отзыв и оценку Лейки на https://wordpress.org/plugins/leyka/
Вопросы и замечания мы постараемся учесть в будущих версиях.

**Comment by shum16** [comment]
Все работает как надо, спасибо еще раз! )
