### ISSUE TITLE
Использование Лейки не на Wordpress, возможно ли?

### ISSUE THREAD

**Issue by aichelnokov** [Teplitsa/Leyka#109]
День добрый.

Можно ли установить Лейку не на WP а на сайт с другой cms, к примеру самописной?
Есть ли API? Или быть может на поддомене возможно установить WP и настроить Лейку на нем, а на сам сайт вставить ифрэймом?

**Comment by Ahaenor** [comment]
Добрый день!

Да, Лейку вполне можно использовать для сайтов не на WordPress.

API у неё пока нет - вы первый, кто об этом спросил. Если к нам будут поступать другие аналогичные запросы, мы внесём это в план работ.

Сейчас решением для вашего случая, действительно, будет развернуть дополнительный сайт (WordPress+Лейка), который будет содержать только страницу для платежей (и бэкофис для их обработки).

Такой сайт можно развернуть на поддомене основного, либо просто в его подпапке (например, http://your-website.org/donate/). Последнее, по нашим данным, лучше с т. зр. SEO.

Далее возможны варианты:

1. На основном сайте организации ссылка на платёжную страницу указывает именно на этот "сайт для платежей", точнее, на страницу кампании.

2. Форма для платежа размещается на основном сайте, в айфрейме.

Мы называем такую схему "Лейка рядом". Её использует, например, фонд Перспектива (http://perspektiva-inva.ru/).

Если вам понадобится консультация по выбору платёжной системы или настройке Лейки, мы будем рады помочь. Пишите нам здесь или на почту support@te-st.ru.

**Comment by aichelnokov** [comment]
День добрый.

Я поступил как вы и советовали: установил вордпресс на поддомен и установил
лейку. Теперь мне нужно экземпляры сущностей из сайта связывать с
конкретными кампаниями по сбору средств.

Для полной интеграции модуля лейки к нашему сайту мне нужно:
1) Получать список активных кампаний по сбору средств
2) Получать детальную информацию о конкретном сборе
3) Получать информацию о пожертвованиях разных людей для конкретного сбора

Подскажите запросы к базе данных чтобы получить необходимые выборки?


2016-06-21 10:16 GMT+03:00 Lev Zvyagintsev <notifications@github.com>:

**Comment by Ahaenor** [comment]
Добрый день!

Вам нужно получать эту информацию на сайте с Лейкой (который размещён на поддомене) или на другом (основном)?

**Comment by metthebet** [comment]
Привет!

Насколько сложно было бы сделать пожжержку платёжного аггрегатора IntellectMoney? http://wiki.intellectmoney.ru/pages/viewpage.action?pageId=2098184

**Comment by aichelnokov** [comment]
Получать информацию о сборах нужно на основном сайте.
Там имеется класс пожертвований, экземпляры которого нужно ассоциировать со сборами в лейке, которая установлена на поддомене.

**Comment by Ahaenor** [comment]
> Насколько сложно было бы сделать пддержку платёжного аггрегатора IntellectMoney? http://wiki.intellectmoney.ru/pages/viewpage.action?pageId=2098184

 - Добрый день. Создайте, пожалуйста, отдельный тикет для этого вопроса.

> Получать информацию о сборах нужно на основном сайте.
> Там имеется класс пожертвований, экземпляры которого нужно ассоциировать со сборами в лейке, которая установлена на поддомене.

 - Ок, спасибо, понял вас.
Для того, чтобы получить данные от сайта на WP на сайте извне (например, данные о пожертвованиях), я вижу такие способы:

**1. Использовать функцию экспорта пожертвований.** На странице Пожертвований в админ. разделе Лейки вы можете экспортировать пожертвования в формате CSV, выбрав их по каким-то критериям (напр., все оплаченные за последний месяц). После этого напишите скрипт для сайта-приёмника, который получает на входе такой CSV-файл и переносит данные в БД сайта.

Плюсы подхода: не требуется никаких сторонних действий или решений.
Минусы подхода: экспорт/импорт пожертвований нужно будет делать вручную и регулярно (например, 1 раз в месяц).

**2. Отправлять данные о платежах автоматически.** Вы можете создать специальный скрипт и на сайте с Лейкой, который будет отправлять curl-ом данные о пожертвованиях на основной сайт. Это можно делать либо с некоторой периодичностью (по cron-у), либо при каждом успешном пожертвовании.

Разумеется, на основном сайте также понадобится спец. скрипт, который будет принимать эти данные.

Плюсы подхода: решение похоже на п.1, но полностью автоматизированное. Никаких ручных действий не нужно.
Минусы: нужно создать два скрипта для передачи/приёма данных, а не один.

**3. Установка плагина для получения данных через RESTful API.** Вы можете установить на сайте с Лейкой один из плагинов для WP, который позволяет работать с данными через REST. Например, этот: https://ru.wordpress.org/plugins/rest-api/

После этого основной сайт сможет получать любые данные о пожертвованиях просто по URL-у.

**Comment by aichelnokov** [comment]
Здравствуйте.

Получать информацию о сборах нужно на основном сайте.
Там имеется класс пожертвований, экземпляры которого нужно ассоциировать со
сборами в лейке, которая установлена на поддомене.

20 октября 2016 г., 14:26 пользователь Lev Zvyagintsev <
notifications@github.com> написал:

**Comment by aichelnokov** [comment]
День добрый. Я поступил как вы описали в третьем пункте: "Установка плагина для получения данных через RESTful API". Плагин установился, на запросы отвечает.

Получая список всех постов я не вижу рекламных кампаний. Когда пытаюсь получить инфо о конкретном посте (в котором инфо о рекламной компании) мне выдается следующее сообщение при выводе через print_r:

> stdClass Object ( [code] => rest_forbidden [message] => Извините, вам не разрешено выполнять данное действие. [data] => stdClass Object ( [status] => 403 ) ) 

Скажите, из-за чего может возникать данная ошибка? Каким образом можно получать информацию с помощью этого плагина?

**Comment by Ahaenor** [comment]
Добрый день.

К сожалению, я не понимаю, что за сущности "рекламные кампании".
Но в любом случае, всё, что не касается работы "Лейки" или её интеграции на сайте, мы комментировать не можем.

Спасибо за обращение!
