### ISSUE TITLE
Фатальная ошибка при активации плагина в Wordpress 4.1

### ISSUE THREAD

**Issue by ivbeg** [Teplitsa/Leyka#11]
При активации плагина появляется ошибка "Fatal error: Class 'DOMDocument' not found in /var/www/infoculture.ru/html/wp-content/plugins/leyka/inc/leyka-core.php on line 122"

и плагин не активируется.
Wordpress - 4.1
PHP - 5.3.3

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо за обращение. Мы займёмся. Ожидайте фикса в пределах завтра.

**Comment by Ahaenor** [comment]
Исправление выполнено. Пожалуйста, полностью удалите плагин с сайта и установите его заново.
