### ISSUE TITLE
Don't work with error

### ISSUE THREAD

**Issue by MinistrBob** [Teplitsa/Leyka#110]
WordPress 3.6.1
PHP 5.6

I install plugin. When I activate it.  I get error on any page my site.
Fatal error: Call to undefined function wp_validate_redirect() in /home/virtwww/<mysite>/http/wp-includes/functions.php on line 1305

[functions.php.txt](https://github.com/Teplitsa/Leyka/files/318738/functions.php.txt)

**Comment by Ahaenor** [comment]
Hello!

OK, thanks for the report. We see the problem and already working on a fix.

**Comment by Ahaenor** [comment]
To fix, please take the /inc/leyka-functions.php file from master branch (https://github.com/Teplitsa/Leyka/blob/master/inc/leyka-functions.php) and replace with it the file in your Leyka /inc folder.

Please report if the fix won't work.

**Comment by MinistrBob** [comment]
Заменил файл.  Теперь такой ошибки больше нет. Плагин активировался и я без ошибок могу перемещаться по любым страницам.



От: Lev Zvyagintsev [mailto:notifications@github.com]
Отправлено: 17 июня 2016 г. 16:39
Кому: Teplitsa/Leyka
Копия: Бобровский Дмитрий; Author
Тема: [MASSMAIL Spam:]Re: [Teplitsa/Leyka] Don't work with error (#110)


To fix, please take the /inc/leyka-functions.php file from master branch (https://github.com/Teplitsa/Leyka/blob/master/inc/leyka-functions.php) and replace with it the file in your Leyka /inc folder.

Please report if the fix won't work.

**Comment by Ahaenor** [comment]
Ок, прекрасно. Спасибо за обращение.
