### ISSUE TITLE
После заполнения формы контактных данных, не приходят эти данные

### ISSUE THREAD

**Issue by baimurzin** [Teplitsa/Leyka#111]
Совершая тестовый платеж, заполняя все данные - он проходит успешно. 
Но в списке пожертвований автор платежа указан, как Аноним - почему так?

**Comment by Ahaenor** [comment]
Добрый день!

Это необычная ситуация.

1. Вы могли бы сообщить ОС, где хостится ваш сайт, а также версию PHP, WP и Лейки?
2. Какую тему сайта вы используете?

**Comment by baimurzin** [comment]
1. хостинг - beget
    WP - 4.5.2
    Лейка - Версия 2.2.9.3

2. тема Rara Clean

**Comment by baimurzin** [comment]
@Ahaenor пока нет никаких решений?

**Comment by Ahaenor** [comment]
Добрый день!

Мы исследуем проблему. Ориентировочное время решения - конец текущей недели.

**Comment by Ahaenor** [comment]
Добрый день! Мы возвращаемся к вашему кейсу. Проблема ещё актуальна?
