### ISSUE TITLE
Некорректно отображается дата корректировочного пожертвования

### ISSUE THREAD

**Issue by shum16** [Teplitsa/Leyka#112]
При создании корректировочного пожертвования, указали для него дату 4.05.2016. После сохранения пожертвование появилось в списке пожертвований кампании, но дата отобразилась все равно сегодняшняя (29.06.2016). Долго искал, откуда она берется, оказалось, что из мета-данных пожертвования - '_status_log'.

Мне кажется, правильнее указывать в списке пожертвований дату, которую указали.

**Comment by GSuvorov** [comment]
Спасибо, внесем в список багов на исправление.

**Comment by Ahaenor** [comment]
Добрый день!

Прямо сейчас, насколько мы видим, и в админке, и в публичной части сайта отображается именно дата, которая была указана при создании корректировочного пожертвования.

1. Какая у вас версия Лейки?
2. На какой странице можно увидеть пожертвование с неправильной датой? Мы проверяли виджет для сайдбара ("список пожертвований"), страницу списка пожертвований по кампании и список на странице кампании.

**Comment by shum16** [comment]
Спасибо, сейчас проблем с датой уже не наблюдается.
