### ISSUE TITLE
Ссылка на недоступную страницу с документацией по настройке CloudPayments

### ISSUE THREAD

**Issue by versusbassz** [Teplitsa/Leyka#113]
![leyka-incorrect-link](https://cloud.githubusercontent.com/assets/2342074/16596456/af6dfb74-42fc-11e6-850f-b3f7fcbc6c09.png)

При переходе по данной ссылке на официальном сайте выдаётся 404 ошибка.
Проблемная ссылка: https://leyka.te-st.ru/docs/podklyuchenie-cloudpaiments/

**Comment by Ahaenor** [comment]
Ок, спасибо. Ссылка исправлена, фикс также войдёт в следующее официальное обновление.

На случай, если это актуально, корректная ссылка на документацию: https://leyka.te-st.ru/docs/podklyuchenie-cloudpayments/
