### ISSUE TITLE
Добавить ip-адрес 185.98.85.109 адресом по умолчанию в настройках модуля CloudPayments

### ISSUE THREAD

**Issue by versusbassz** [Teplitsa/Leyka#114]
https://cloudpayments.ru/Docs/Notifications

> Адреса, с которых система отправляет уведомления — это 130.193.70.192 и 185.98.85.109.

**Comment by Ahaenor** [comment]
Ок, спасибо. Второй IP добавлен. Правка войдёт в следующий официальный релиз плагина.
