### ISSUE TITLE
Оплата для Беларуси

### ISSUE THREAD

**Issue by rad73** [Teplitsa/Leyka#115]
Добрый вечер, хотелось бы использовать Лейку в Беларуси. 
Не могли бы вы подключить Хутки Грош
https://github.com/alexantr/HootkiGrosh
https://github.com/esasby/hgrosh/tree/master/CMS/Plugins/WordPress
или EasyPay
https://ssl.easypay.by/merinfo/
Спасибо

**Comment by Ahaenor** [comment]
Добрый день! Ок, вопрос понятен.

На данный момент мы, к сожалению, занимаемся интеграцией только российских платежных систем, т.е. мы не сможем добавить указанные вами системы своими силами.

Однако код плагина открыт, и мы будем рады pull-request'ам по данным платежным системам. Мы готовы всесторонне консультировать разработчиков, желающих добавить в плагин эти системы, но сами заниматься разработкой мы не можем. За консультациями можно обратиться здесь или на почту support@te-st.ru.

Спасибо за обращение!
