### ISSUE TITLE
Статус "Попытка платежа"

### ISSUE THREAD

**Issue by DanielSpb** [Teplitsa/Leyka#116]
Здравствуйте , у меня при рядом с каждым переводом стоит в статусе "Попытка платежа", до нас деньги доходят, хотя возможно это может быть неуспешной попыткой.  Сейчас мы сверяем дошедшие суммы и переводами внутри Лейка. Как определить через плагин , что платеж точно завершен и выполнен успешно? 

вот здесь часть экрана , который мы видим:

https://yadi.sk/i/p6pGFP7Ttdqgu

Заранее спасибо за ответ!

**Comment by Ahaenor** [comment]
Добрый день!

Чтобы платежи в Лейке автоматически переходили в статус "оплачено" при фактическом поступлении денег на счёт, нужно:
1. зайти в настройки вашей панели управления в RBK Money,
2. настроить уведомления сайта о поступивших платежах.

О том, как это сделать, можно прочитать в инструкции по настройке RBK Money: https://leyka.te-st.ru/instruction/
Раздел "Настройки на стороне панели управления РБК", п. 1 (оповещение о платеже) и п. 5 (не отправлять оповещения о платежах).

Если у вас будут ещё какие-либо вопросы, мы постараемся ответить) Спасибо за обращение.
