### ISSUE TITLE
Временной контроль и контроль уникальности оплаты заказа в ChronoPay

### ISSUE THREAD

**Issue by Mikhail84** [Teplitsa/Leyka#117]
Для подключения Лейки к аккаунту клиента в ChronoPay потребовалась поддержка временного контроля и контроля уникальности оплаты заказа. Найти опцию Лейке не удалось. 

Подробнее об этом написано в Руководстве ChronoPay по адресу
http://dev.support.nemo.travel/images/a/a9/Chronopay_Payment_page_RU_v1.16.pdf

Вот выдержка из п 5.10
"Внимание! Если подключён функционал контроля уникальности оплаты заказа (см. тут - 5.4. Временной контроль и контроль уникальности оплаты заказа), то при расчёте контрольной суммы используется номер заказа (order_id):
sign = md5(product_id-product_price-order_id-sharedsec)"

Поддержка опции крайне важна, так как без нее не возможно проводить оплату для некоторых платежных аккаунтов в ChronoPay.

**Comment by Ahaenor** [comment]
Добрый день.

1. На данный момент эта опция не поддерживается, т.к. мы никогда не встречались с таким запросом со стороны наших бенефициаров.

Мы рассмотрим её добавление в будущей версии Лейки.

2. В кач-ве альтернативы, вы можете добавить эту опцию (и её обработку) в плагин самостоятельно и прислать нам пулл реквест.

3. Какую огранизацию или инициативу вы представляете? Если не секрет )
Нам важно для ведения отчётности по обращениям в поддержку плагина.

**Comment by Mikhail84** [comment]
Участвую в разработке новой версии сайта благотворительного фонда "Димина Мечта"

**Comment by Ahaenor** [comment]
Ок, спасибо за обращение.

* Мы постараемся сделать экспресс-апдейт (включающий эту опцию) в течение следующей недели.
* Если важно получить обновление быстрее, мы будем рады пулл реквесту с вашей стороны (и объясним, какие дополнения в коде будут нужны).

**Comment by Mikhail84** [comment]
Непосредственно внести изменение для работоспособности достаточно в одном в файле leyka-class-chronopay-gateway.php в методе submission_form_data, а вот вынести настройки корректно в админ панель, например, тут нужно более глубоко быть знакомым с кодом плагина, а без документации для разработчиков сделать это затруднительно. Возможно не будет ошибкой включение опцию для всех платежей по умолчанию, даже для использования с аккаунтами, где функционал контроля не подключен, но я не имею пока возможности протестировать это.

**Comment by Ahaenor** [comment]
Добрый день.

В новой версии плагина в гейтвей Chronopay будет добавлена опция "контроль уникальности платежей". Если она отмечена, проверка по хэшу будет проходить с учётом ID пожертвования (как в инструкции).

Вы также можете получить свежий код в ветке dev репозитория, не дожидаясь релиза.

Спасибо за обращение!
