### ISSUE TITLE
Дополнительные поля данных в форме

### ISSUE THREAD

**Issue by Mikhail84** [Teplitsa/Leyka#118]
Необходима поддержка дополнительных полей "телефон и комментарии к платежу". Было бы удобно, если бы в настройках плагина можно было задавать произвольное количество полей, подключаемых к форме, и задавать заголовок и плейсхолдер для каждого из них.

**Comment by Ahaenor** [comment]
Сейчас добавление доп. полей к различным способам оплаты возможно (и даже несложно), но только средствами программирования. Если вы готовы на такой вариант, сообщите - мы расскажем, что именно нужно сделать.

В любом случае мы зафиксировали ваш запрос на эту функцию. Есть все шансы, что она войдёт в одну из будущих версий.

Спасибо за обращение!

**Comment by Mikhail84** [comment]
С удовольствием попробывал бы вариант с программированием, особенно, если есть решение, которое сохранится при обновлении плагина.

**Comment by Ahaenor** [comment]
Ок, тогда мы подготовим подробную инструкцию. Оставлю её здесь в начале следующей недели.

**Comment by Mikhail84** [comment]
Доброго дня! Есть какие успехи по созданию инструкции?

**Comment by Ahaenor** [comment]
К сожалению, мы были вынуждены переключиться на срочные задачи. Мы сможем
подготовить инструкции не ранее следующей недели.

Спасибо за ожидание!

18 августа 2016 г., 17:31 пользователь Михаил <notifications@github.com>
написал:

**Comment by katt999** [comment]
Добрый день!
Тоже хотелось бы добавить дополнительные поля к уже имеющейся форме. Расскажите пожалуйста как это сделать.

**Comment by Ahaenor** [comment]
Добрый день!

Итак, относительно добавления кастомных полей формы для пожертвований у одного/нескольких способов оплаты (платёжных методов, ПМов).

**1.** Сейчас в плагине есть т. н. "глобальные поля": размер платежа ('amount'), имя донора ('name'), почта донора ('email'), согласие с условиями сервиса ('agree'), кнопка отправки платежа ('submit').
Они есть (и будут) в большинстве ПМов, поэтому они управляются сразу всей группой.

Чтобы указать для ПМа, нужны ли ему глобальные поля, нужно при определении его класса (подкласс Leyka_Payment_Method) в методе _set_attributes() указать атрибут _support_global_fields в значение true или false.

 **2.** В методе _set_attributes() класса ПМа также можно определить значение атрибута _custom_fields.

Этот атрибут - ассоциативный массив, где ключи - строковые ID полей данных, а значения - HTML-код соотв. полей на форме.
Пример использования атрибута _custom_fields для добавления в ПМ специальных полей можно увидеть внутри метода _set_attributes() класса Leyka_CP_Card:

```
$this->_custom_fields = array(
    'recurring' => '<label class="checkbox"><span><input type="checkbox" id="leyka_'.$this->full_id.'_recurring" name="leyka_recurring" value="1"></span> '.__('Monthly donations', 'leyka').'</label>'
);
```

После этого на форме для пожертвований у соотв. ПМа появится новое поле. Его валидацией можно управлять с помощью CSS-классов.
Например, класс required подразумевает, что поле обязательно для заполнения; класс email - что значение должно быть валидным адресом эл. почты; non-email - что значение, напротив, не должно быть email-ом.

**Внимание:** если в определении кастомных полей вам необходимо использовать не просто статический HTML-код, но и значения опций плагина (leyka_options()->opt("ID опции")), то определять значение $this->_custom_fields нужно не в методе _set_attributes(), а в методе _set_dynamic_attributes().
Пример из класса Leyka_Mixplat_Text:
```
protected function _set_dynamic_attributes() {
    $this->_custom_fields = array(
        'sms_details' => apply_filters('leyka_the_content', leyka_options()->opt_safe($this->full_id.'_details')),
    );
}
```

 **3.** После того, как на форме у ПМа появились кастомные поля, их значения можно как-либо обрабатывать при отправке донором пожертвования.
Это можно сделать в JS-коде ПМа (как, напимер, в гейтвее CloudPayments, см. файл /gateways/cp/js/leyka.cp.js).
Кроме того, значения кастомных полей формы могут использоваться при сохранении данных пожертвования в БД сайта. Для этого используется метод process_form($gateway_id, $pm_id, $donation_id, $form_data) в классе гейтвея.
Последний параметр метода - ассоциативный массив, где имена и значения соотв. всем полям формы пожертвования (вкл. кастомные поля, определённые вами выше).
Пример метода process_form() из класса Leyka_CP_Gateway:
```
public function process_form($gateway_id, $pm_id, $donation_id, $form_data) {

    $donation = new Leyka_Donation($donation_id);

    if( !empty($form_data['leyka_recurring']) ) {
        $donation->payment_type = 'rebill';
    }

}
```

**Резюме:** эти сведения помогут вам добавить и использовайть (на базовом уровне) кастомные поля в различные платёжные методы (ПМы).

Если у вас будут вопросы по этой статье, или вы захотите узнать больше о том, как использовать кастомные поля данных в ПМах и БД пожертвований, напишите на скайп ahaenor.

**Comment by katt999** [comment]
Спасибо большое!!!
Обязательно попробую внести изменения.



Отправлено из мобильной Почты Mail.Ru


воскресенье, 25 сентября 2016 г., 14:36 +0300 от Lev Zvyagintsev  <notifications@github.com>:
>Добрый день!
>Итак, относительно добавления кастомных полей формы для пожертвований у одного/нескольких способов оплаты (платёжных методов, ПМов).
>1. Сейчас в плагине есть т. н. "глобальные поля": размер платежа ('amount'), имя донора ('name'), почта донора ('email'), согласие с условиями сервиса ('agree'), кнопка отправки платежа ('submit').
>Они есть (и будут) в большинстве ПМов, поэтому они управляются сразу всей группой.
>Чтобы указать для ПМа, нужны ли ему глобальные поля, нужно при определении его класса (подкласс Leyka_Payment_Method) в методе _set_attributes() указать атрибут _support_global_fields в значение true или false.
>2. В методе _set_attributes() класса ПМа также можно определить значение атрибута _custom_fields.
>Этот атрибут - ассоциативный массив, где ключи - строковые ID полей данных, а значения - HTML-код соотв. полей на форме.
>Пример использования атрибута _custom_fields для добавления в ПМ специальных полей можно увидеть внутри метода _set_attributes() класса Leyka_CP_Card:
>$this->_custom_fields = array(
    'recurring' => '<label class="checkbox"><span><input type="checkbox" id="leyka_'.$this->full_id.'_recurring" name="leyka_recurring" value="1"></span> '.__('Monthly donations', 'leyka').'</label>'
);
>После этого на форме для пожертвований у соотв. ПМа появится новое поле. Его валидацией можно управлять с помощью CSS-классов.
>Например, класс required подразумевает, что поле обязательно для заполнения; класс email - что значение должно быть валидным адресом эл. почты; non-email - что значение, напротив, не должно быть email-ом.
>Внимание: если в определении кастомных полей вам необходимо использовать не просто статический HTML-код, но и значения опций плагина (leyka_options()->opt("ID опции")), то определять значение $this->_custom_fields нужно не в методе _set_attributes(), а в методе _set_dynamic_attributes().
>Пример из класса Leyka_Mixplat_Text:
>protected function _set_dynamic_attributes() {
    $this->_custom_fields = array(
        'sms_details' => apply_filters('leyka_the_content', leyka_options()->opt_safe($this->full_id.'_details')),
    );
}
>3. После того, как на форме у ПМа появились кастомные поля, их значения можно как-либо обрабатывать при отправке донором пожертвования.
>Это можно сделать в JS-коде ПМа (как, напимер, в гейтвее CloudPayments, см. файл /gateways/cp/js/leyka.cp.js).
>Кроме того, значения кастомных полей формы могут использоваться при сохранении данных пожертвования в БД сайта. Для этого используется метод process_form($gateway_id, $pm_id, $donation_id, $form_data) в классе гейтвея.
>Последний параметр метода - ассоциативный массив, где имена и значения соотв. всем полям формы пожертвования (вкл. кастомные поля, определённые вами выше).
>Пример метода process_form() из класса Leyka_CP_Gateway:
>public function process_form($gateway_id, $pm_id, $donation_id, $form_data) {

    $donation = new Leyka_Donation($donation_id);

    if( !empty($form_data['leyka_recurring']) ) {
        $donation->payment_type = 'rebill';
    }

}
