### ISSUE TITLE
add Paypal Gateway

### ISSUE THREAD

**Issue by dalia12345** [Teplitsa/Leyka#12]
Hi, 
thanks for this great plugin. Only problem I got is that in Europe Yandex or Cronoplay are hardly known or used. Paypal Support would be great!

**Comment by foralien** [comment]
Thank you for your feedback and your attention to our work.
The plugin is mostly aimed for Russian market and Russian legal terms, that's why the local payment gateways were in the priority.
Anyway we have PayPal in our roadmap - so please follow updates.

**Comment by lerniri** [comment]
Hi, Anna/Team. Do you have in mind any existing workaround of integrating PayPal into Leyka, untill it's not included into plugin core ? Also, is where can I track PayPal task   updates ? Thanx a lot for a great plugin.

**Comment by Ahaenor** [comment]
Hello!

As a workaround I can advise you to use some of the specialized fundraizing
WordPress plugins - like this
<https://wordpress.org/plugins/paypal-donations/>, for example.

There are many of such plugins, actually - it's the other reason that the
priority of PayPal for us is quite low.

Regretfully, Leyka has no publicly accessible roadmap right now. But the
more our users asking for it, the sooner it will be.
As of now, I can say approx. 3-4 months from now as the Gateway support
release date.

Thank you for your question - your interest for new functions is very
important for us.

2015-05-26 11:40 GMT+03:00 lerniri <notifications@github.com>:

**Comment by lerniri** [comment]
Thanx Lev, appreciate that. Actually , figured that out  - just using paypal button + all usefull stuff that Leyka provides.

**Comment by Ahaenor** [comment]
Oh, it's brilliant solution :)

2015-05-28 18:48 GMT+03:00 lerniri <notifications@github.com>:
