### ISSUE TITLE
js-ошибка в функции "leyka_is_digit_key" (вызов глобальной переменной $)

### ISSUE THREAD

**Issue by versusbassz** [Teplitsa/Leyka#120]
![leyka-jquery-alias-bug](https://cloud.githubusercontent.com/assets/2342074/18522677/b8abb948-7ab9-11e6-9eff-9457ed2a6b08.png)

Фикс - заменить в указанной строке $ на jQuery. Ну или как-то ещё, если так будет лучше.

Ошибка выскакивает при вводе любой суммы в поле формы пожертвований на лицевой части сайта.

**Comment by Ahaenor** [comment]
Ок, спасибо. Мы проверим и исправим.

14 сент. 2016 г. 8:29 PM пользователь "Vladimir Sklyar" <
notifications@github.com> написал:

**Comment by Ahaenor** [comment]
К сожалению, не можем воспроизвести ошибку. На рабочих инсталляциях тоже всё нормально.

1. Где можно увидеть ошибку?
2. В какой точно строке в public.js вы выполнили замену?

**Comment by versusbassz** [comment]
1) в любой инсталляции плагина, при открытии формы пожертвования, например, тут:
https://leyka.te-st.ru/campaign/demo-kampaniya/
> Ошибка выскакивает при вводе любой суммы в поле формы пожертвований на лицевой части сайта.

2) ![leyka-bug-fix](https://cloud.githubusercontent.com/assets/2342074/18626966/f1f9287a-7e60-11e6-9511-4bb8704ead94.png)
+ см. скриншот из начального сообщения, там всё указано

**Comment by Ahaenor** [comment]
Странно, у нас не видно этой ошибки. Тестирование проводилось во всех совр. браузерах.

В любом случае, эта ошибка уже исправлена (в дев. ветке). Она войдёт в след. версию плагина.

Спасибо за обращение!
