### ISSUE TITLE
Вывод кампаний на страницу.

### ISSUE THREAD

**Issue by VitoM24** [Teplitsa/Leyka#122]
Добрый день, хотел бы узнать как вывести кампании на страницу как это сделано в вашей теме grassroots?
Если это невозможно, почему бы не добавить такую функцию в плагин, это же было бы очень удобно, либо добавить функцию вывода карточек через shortcode. Как пример плагин WP Charitable, у них есть возможность вывода, было бы отлично если бы у Вашего плагина была бы такая функция!

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за обращение.

Какой именно способ вывода кампаний на странице вас интересует - можете прислать ссылку на страницу Grassroots, где это выполняется?

Насколько мы понимаем, уже сейчас есть несколько способов вывести список кампаний в публичной части сайта:

**1.** В последней версии плагина (2.2.11) поддерживается страница архива (то есть списка) и для пожертвований, и для кампаний . Последнюю вы можете увидеть по ссылке _http://your-website.org_/campaign/

**2.** Кроме того, есть ещё виджет "Список кампаний". Его можно вывести в любой боковой панели вашей темы.

**Comment by VitoM24** [comment]
![main](https://cloud.githubusercontent.com/assets/22433448/18923421/c2cfa898-85b4-11e6-9e19-e3d04dbf0d58.png)
Вот такой вид, как на главной странице Grassroots.
Было бы очень удобно выводить кампании в таком виде через shortcode, например:[leyka_campaign_card_all]
Ещё было бы неплохо сделать галерею для каждой кампании, как это реализовано в woocommerce для продуктов:
![default](https://cloud.githubusercontent.com/assets/22433448/18923578/6ee03b2a-85b5-11e6-93a1-083f8b7e0962.png)

**Comment by Mobilkanokia** [comment]
Присоединяюсь к просьбе VitoM24.
Было бы здорово иметь возможность вывода карточек через shortcode. 
Плагин Charitable - отличный пример для подражания. Как раз работаем над проектом для НКО, в котором взяли за основу тему Born to Give (http://wp2.imithemes.com/born-to-give/), в ней встроен плагин Charitable с прекрасным выводом кампаний на главной.
![screen shot 2016-09-08 at 21 59 48](https://cloud.githubusercontent.com/assets/18754015/18969157/fbc9e5e4-869c-11e6-8dce-bbf6d3589e9e.png)
Но нам необходимо использовать Лейку вместо Charitable и мы столкнулись с проблемой вывода карточек на главную.
Подскажите, может у вас есть решение для этого вопроса.

**Comment by Mobilkanokia** [comment]
Shortcode Лейки нашли, вывели на главную кампании, 
![screen shot 2016-09-30 at 09 32 17](https://cloud.githubusercontent.com/assets/18754015/18982690/1abd4e30-86f9-11e6-9ff2-69a046de2ca4.png)
теперь думаем над тем, чтобы сделать галерею как в Born to Give.

Кстати в этой теме есть очень удобный инструмент Visual Composer, для клиента понятный (без правок кода). В него можно добавить дополнительные элементы для вывода на страницы, что мы и сделали. Теперь клиент сможет добавлять кампанию лейки на страницу при помощи удобного для него инструмента.

**Comment by Ahaenor** [comment]
Да, конструкторы страниц для WP есть во множестве. Иногда они встроены в тему, иногда устанавливаются как отдельные плагины.

Мы обычно используем SiteOrigin PageBuilder. Он позволяет визуально конструировать страницы из блоков на основе виджетов (WP_Widget и его подклассы). Для клиентов это вполне применимо (согласно нашему опыту).

Кроме того, у него есть вспомогательный плагин - SiteOrigin Widgets Bundle. Он добавляет много вариантов виджетов для конструктора, и, что важнее, даёт API для добавления и работы с ними из кода.

Таким образом, если вас чем-то не устроит набор виджетов самой Лейки (для вашего кейса у неё есть виджет "Список кампаний"), вы можете легко создать собственный, и в нём выводить карточки кампаний Лейки с произвольной вёрсткой.

**Comment by Ahaenor** [comment]
Мы учтём вашу просьбу об отдельном шорткоде для вывода серии карточек. Но сейчас план по развитию продукта идёт в другую сторону, руки дойдут нескоро :)

Но мы были бы очень рады пулл реквестам с таким шорткодом. Код Лейки открыт, и мы с радостью принимаем contributions.
