### ISSUE TITLE
Повторяющиеся платежи и Яндекс.Касса

### ISSUE THREAD

**Issue by zaur** [Teplitsa/Leyka#123]
Здравствуйте!
Вопрос по повторяющимся платежам.

В настройках яндекс.кассы в лейке можно включить галочку "повторяющиеся платежи", однако яндекс требует выполнения ряда условий, среди которых следующие:

> 
> 1. Сообщите менеджеру Яндекс.Кассы, что вы вы хотите настроить автоплатежи и опишите как пользователи смогут отвязать банковскую карту, укажите планируемые обороты в месяц по онлайн платежам;
> 2. ...
> 3. ...
> 4. Реализуете функцию repeatCardPayment, 
> 5. После подключения регулярных платежей на форме оплаты картой появится чекбокс "Запомнить данные карты". 
> 
> Если клиент его поставит, то в запросе checkOrder\paymentAviso вы получите параметр rebillingOn=true, что будет обозначать то, что invoiceid этого платежа можно использовать в функции repeatCardPayment для повторных платежей.
> Обратите внимание, что чекбокс можно предустановить и скрыть от клиента (текст с информацией о привязке останется), если в платежной форме сразу передать нам параметр rebillingOn=true,
> 
> 
> В обоих случаях интеграции вам в обязательном порядке необходимо реализовать процедуру отвязки карты. 
> Обратите внимание, что процедура является формальной и при отвязке карты вы обязаны удалить из своей системы токен для повторов. 
> Нам сообщать об отвязке не требуется.
> 

скажите, пожалуйста, это все уже реализовано в Лейке? или нужно делать самому?
Сейчас, к сожалению, не совсем понятно.

Спасибо!

**Comment by Ahaenor** [comment]
Добрый день!

Сейчас поддержка рекуррентных списаний от Яндекс.кассы есть, но настроить её довольно затруднительно. Причина этому не в Лейке, а в организационных требованиях со стороны Яндекс.кассы.

1. А именно, **п. 4, 5 и далее в Лейке реализованы**.
Но для корректной работы рекарринга также необходимо поставить в cron на вашем сервере ежедневный вызов специального УРЛа: _http://your-website.org_/leyka/service/do_recurring/

2. Кроме этого, необходимо получить специальный SSL-сертификат, который будет использоваться Лейкой для авторизации в системе Яндекс.кассы при рекуррентных списаниях. Для этого сертификата в настройках Яндекса в Лейке есть спец. поля.

3. Относительно отмены рекарринговых подписок. Сейчас Лейка не позволяет донору сделать это автоматически (напр., при переходе по какой-то ссылке из спасибо-письма). Эта функция - направление для дальнейшего развития поддержки Яндекс.кассы.

Сейчас отмена рекуррентных подписок выполняется администратором Лейки по просьбе донора. Об этом вы можете явно написать в шаблоне спасибо-писем, которые отправляются при рекуррентных списаниях.

4. Относительно удаления токена для повторов. Сейчас это в Лейке не выполняется, т.к. мы впервые встречаемся с таким требованием :) Насколько я понимаю, оно чисто формальное. Мы рассмотрим его реализацию в будущих версиях плагина. Сейчас рекуррентные платежи через Яндекс.кассу должны работать всё равно.

Спасибо за обращение!
