### ISSUE TITLE
Интеграция Яндекс.Касса для юрлиц

### ISSUE THREAD

**Issue by Gavroshe** [Teplitsa/Leyka#124]
Здравствуйте! 

Сайт thenoon.ru

Для подключения Яндекс.Кассы по протоколу HTTP помимо ввода shopId и scid на стороне CMS, необходимо также ввести shopPassword. В настройках Лейки данное поле я найти не смог http://clip2net.com/s/3DtQ2ua. Не подскажете, где его найти?

**Comment by Ahaenor** [comment]
Добрый день!

Параметр для shopPassword ("секретное слово магазина") появится в плагине в ближайшей новой версии (2.2.12). Она выйдет до конца этой недели :)

До этого вы можете не указывать в Лейке shopPassword. Платежи будут работать и без него.

Спасибо за обращение!
