### ISSUE TITLE
Обновление 2.2.12 - пропала панель администрирования

### ISSUE THREAD

**Issue by yurmar** [Teplitsa/Leyka#125]
Здравствуйте! Спасибо за отличный плагин. Но после обновления до версии 2.2.12 на сайте пропадает панель администрирования. У меня на двух сайтах пропала, на третем не хочу рисковать. Пожалуйста, проверьте.

С уважением, Юрий.

**Comment by Ahaenor** [comment]
Добрый день!

Эта ошибка исправлена. Пожалуйста, возьмите из этого репозитория файл /inc/leyka-core.php и замените им соотв. файл плагина на ваших серверах.

Спасибо за обращение!

**Comment by yurmar** [comment]
Доброе утро!
Всё заработало. Спасибо!

**Comment by Ahaenor** [comment]
Ура) Рады быть вам полезны.

Спасибо за обращение ещё раз.
