### ISSUE TITLE
Внешний стиль

### ISSUE THREAD

**Issue by topakov** [Teplitsa/Leyka#128]
Как изменить стиль на такой же https://www.asi.org.ru/campaign/support-agency/ ?
Есть ли css файл такого (https://www.asi.org.ru/campaign/support-agency/) или подобного стиля? И как прикрутить внешний css стиль, что бы после обновления плагина оформление не слетело.

**Comment by FunkyXL** [comment]
Как мы можем самостоятельно перевести в существующей форме следующие строки: ?
1. Изменить "or" на "или".
2. Перевести "MONTHLY DONATIONS" на "Ежемесячное пожертвование".
Скрин: [http://c2n.me/3DZkOZb](http://c2n.me/3DZkOZb)

В каком файле это можно поправить? Проверил файл - \leyka\lang\leyka-ru_RU.po но там не оказалось нужной информации.

**Comment by Ahaenor** [comment]
@topakov , добрый день!

1. На сайте АСИ (который вы указали в качестве примера) используется кастомный шаблон формы пожертвования. То есть такой "облик" формы не входит в Лейку, а был разработан для неё вручную.

В след. версии плагина появится новый вариант формы - он будет очень похож на этот, и его можно будет доработать с помощью CSS.

2. Внешний CSS можно прикрутить с помощью программных средств, обычных для WordPress.
Лейка подключает свои стили так:
`wp_enqueue_style($this->_plugin_slug.'-plugin-styles', LEYKA_PLUGIN_BASE_URL.'css/public.css', array(), LEYKA_VERSION);`

То есть идентификатор её стилей для публичной части сайта - **"leyka-plugin-styles"**.

Вы можете убрать этот файл стилей из подключения в вашем собственном коде (например, в теме вашего сайта) c помощью функции [wp_dequeu_style()](https://codex.wordpress.org/Function_Reference/wp_dequeue_style).
После этого останется только подключить ваш собственный файл CSS:
wp_enqueue_style($this->_plugin_slug.'-custom-leyka-styles', 'path/to/your/leyka/css/public.css', array(), LEYKA_VERSION);

**Comment by Ahaenor** [comment]
@FunkyXL , добрый день!

Спасибо за вопрос. Я создам под него новый таск и отвечу отдельно.

**Comment by topakov** [comment]
@Ahaenor, возможно ли в будущем обновлении сделать возможность подключения внешнего css-файла прямо из настроек плагина. Чтоб было проще. Если я сейчас буду править что-то в шаблоне сайта при следующем обновлении шаблона или cms все слетит.
Или можно хотя бы здесь, для людей с небольшими знаниями описать подробнее как подключить стиль, что бы после обновлений ничего не слетело.

**Comment by Ahaenor** [comment]
@topakov , способ, который я описал выше, безопасен) CSS-файл, подключённый так, не исчезнет с обновлением Лейки.
Ваши изменения пропали бы, если бы вы меняли код в CSS-файле Лейки (/css/public.css).

В подключении внешнего CSS-файла прямо из настроек плагина обычно нет необходимости. Наш опыт показывает, что если пользователь написал собственный CSS, то обычно он может и добавить пару строк в код темы. Эти строки я и привёл выше - вызов функций **wp_dequeue_style()** и **wp_enqueue_style()**.

Но мы планируем добавление настройки, которая позволит менять цветовое оформление формы (с зелёного по умолчанию на любой, по выбору пользователя).

**Comment by topakov** [comment]
@Ahaenor, просто у меня тема тоже обновляется путем замены всех файлов и не хочется после каждого обновления темы заново вводить эти строки.
Ладно, можете как для самого тупого. Написать какие строки (код полностью) в какой php файл вставить? Спасибо за помощь!

**Comment by Ahaenor** [comment]
Если тема обновляется, в неё помещать код тоже нельзя.
Тогда вам понадобится создать собственный плагин для WordPress.
О том, как это сделать, можно прочитать, например, [здесь](http://easy-code.ru/lesson/building-wordpress-plugin-part-one).

В вашем плагине достаточно будет иметь всего два файла:
 - Основной файл плагина, например, leyka-custom-css.php.
 - Файл с вашим CSS (в примере ниже он упоминается как **leyka-custom-styles.css**).

Кроме вступительного комментария с данными о плагине (см. статью по ссылке выше), поместите **в основной файл плагина** следующий код:
```
function cls_enqueue_custom_styles() {
	wp_dequeue_style('leyka-plugin-styles');
	wp_enqueue_style('leyka-plugin-styles', plugin_dir_path(__FILE__).'leyka-custom-styles.css');
}
add_action('wp_enqueue_scripts', 'cls_enqueue_custom_styles', 100);
```

P. S. После того, как вы загрузите ваш плагин на сайт, не забудьте включить его (активировать) в разделе "Плагины".
