### ISSUE TITLE
Стена кампаний на мультисайте

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#13]
У меня стоит wordpress мультисайт. Для НКО мы даем возможность вести свои сайты в мультисайтовой установке. Таким образом, на одной установке существует сразу много сайтов.

По просьбам владельцев сайтов мы включаем и настраиваем "Лейку". 

Хочется на одном ресурсе выводить карточки кампаний со всех сайтов мультисайтовой установки.

Механизм вручную через ифреймы очень нефункционален.

Хочется или отдельным плагином, или добавить функциональность в самой Лейке, чтобы На определенной странице любого сайта мультисайтовой сети в виджет выводить поток карточек текущих кампаний, с настройками количеств столбцов карточек и фильтрацией, сортировкой кампаний по разным параметрам.

**Comment by NikolayP** [comment]
Лейка на каждом поддомене своя стоит?

**Comment by olegtkirov** [comment]
В мультисайтовом WP общая папка плагинов, там файлы лейки тоже лежат. На каждом сайте активируются свои плагины из этого каталога. На каждом сайте, где активировано, сохраняются свои настройки лейки.

По общему правилу новые сайты в мультисайтовой структуре создаются на субдоменах, однако можно задавать уникальные домены любому сайту этой структуры

В связи с этим, думаю что данные кампаний с каждого сайта собирать в один массив, например JSON и этот массив разбирать фильтруя и сортируя в виджет, игнорируя такие параметры, как например параметры отображения карточки кампании (на каждом сайте внешний вид карточки может быть как-то уникальным образом быть настроен). Это чтобы на одной странице все карточки всех кампаний со всех сайтов выглядели одинаково.

**Comment by foralien** [comment]
Можно реализовать средствами собственно WP мультисайт - по аналогии например с https://wordpress.org/plugins/network-latest-posts/, так как  каждая кампания лейки на любом из сайтов (не зависимо от домена) - это пост типа leyka_campaign. Ну дальше собственно фукнции API - ничего не придумаешь, ну кеширование какое-ниудь для ускорения процесса,  собственно разметка виджета, чтобы был как вы хотите (ну или не виджет - тогда просто шаблон).
Мне кажется это будет оптимальнее, чем "внешними" способами как-то пытаться получать записи.
Можно по идее формить как отдельный плагин, который просто проверяет наличие Лейки при загрузке.

В целом спасибо за идею, до сих пор мы не очень двигались в сторону мультисайта.

**Comment by olegtkirov** [comment]
О, да, спасибо работает. Этот плагин как раз у нас был установлен и выводил анонсы постов со всех сайтов сети, а о настройках пользовательского типа записи я и забыл, что они там есть.

Выводится миниатюра, заголовок, цитата. Миниатюра конечно сообразно с версткой этого плагина, почему-то обрезанная в квадрат, но это уже мелочи, надо копаться, смотреть где и что выводится.

Думаю, надо все-таки его переработать в новый плагин под вывод именно лейки - задать оформление как карточки кампаний, вызвать отображение прогресс-бара, ну и отдельно фильтрацию и сортировку закончившихся кампаний и действующих (сейчас выводит закончившиеся и действующие в одном потоке). Может быть задать новые сортировки (по дате последнего пожертвования, по количеству собранных средств, по целевой сумме и пр.)

Отдельная хорошая идея от этого плагина - категории и теги кампаний (это тогда необходимо в лейке сделать дополнительные систематики). На сводном проекте чтобы можно было вызывать все кампании сети по тегу "Дети", "Инвалиды", "Спорт" и пр. Допустим организация на свой сайт выводит карточки кампаний со всей сети, близкие по своей тематике, и тем самым помогает коллегам.

**Comment by Ahaenor** [comment]
Сейчас программно можно добавить любые кастомные таксономии - и кампаниям, и даже пожертвованиям (хотя полезность последнего под вопросом).
Для этого используется стандартная функция WP - [register_taxonomy()](https://codex.wordpress.org/Function_Reference/register_taxonomy)

При этом программным же образом можно добавить ссылки на эти таксономии как подпункты в меню Лейки. Для этого послужит фильтр leyka_form_pm_order

**Comment by olegtkirov** [comment]
Не спорю, на своем проекте можно добавить. Но при взаимодействии кампаний с разных проектов, как например стена мультисайта, или если делать какой-то сводный ресурс, который с автономных установок будет карточки собирать и показывать в едином потоке, желательна единая система имен систематик.
