### ISSUE TITLE
Вывод формы на главную

### ISSUE THREAD

**Issue by FunkyXL** [Teplitsa/Leyka#130]
Подскажите пожалуйста как мы можем вывести существующую форму dobro.chuvstvo-doma.ru/campaign/test1/ (страницу целеком) на главную страницу dobro.chuvstvo-doma.ru ? 

Силами Wordpress возможно выводить только Страницы и Записи.
Спасибо!

**Comment by Ahaenor** [comment]
Добрый день!

Платёжную форму можно вывести в составе любой страницы, записи или виджета на сайте.
Для вставки формы на главную страницу добавьте в её текст следующий шорткод:
`[leyka_payment_form id=XXX]`
Здесь ХХХ - число-идентификатор (ID) кампании. Вы можете увидеть его в админ. разделе, на странице списка кампаний Лейки.

**Comment by FunkyXL** [comment]
Благодарю за помощь! Respect 21.11.2016, 12:13, "Lev Zvyagintsev" <notifications@github.com>:Добрый день!Платёжную форму можно вывести в составе любой страницы, записи или виджета на сайте.Для вставки формы на главную страницу добавьте в её текст следующий шорткод:[leyka_payment_form id=XXX]Здесь ХХХ - число-идентификатор (ID) кампании. Вы можете увидеть его в админ. разделе, на странице списка кампаний Лейки.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -------------------------------------------------- С уважением, АлексейE-mail: funkyxl@ya.ru
