### ISSUE TITLE
Вопрос с кодировкой?

### ISSUE THREAD

**Issue by katasor** [Teplitsa/Leyka#131]
Здравствуйте! У нас некорректно отображается блок вывода кампаний. Подскажите, пожалуйста, как это исправить? Проблема видна на скрине.

![254](https://cloud.githubusercontent.com/assets/23389890/20197036/76adb128-a7ae-11e6-96d8-24d8398bdbec.png)

**Comment by Ahaenor** [comment]
Добрый день!

Ок, проблема исправлена.
Вы можете обновить код плагина из ветки dev (а именно, файлов **/inc/leyka-functions.php** и **/inc/leyka-shortcodes.php**) или дождаться официального обновления.

Спасибо за сообщение!
