### ISSUE TITLE
Платежная форма

### ISSUE THREAD

**Issue by Mobilkanokia** [Teplitsa/Leyka#132]
Добрый день!
Подскажите пожалуйста, хочу вывести такой же внешний вид платежных систем как на скриншоте.
![screen shot 2016-11-17 at 00 59 11](https://cloud.githubusercontent.com/assets/18754015/20368335/030341a2-ac6d-11e6-803b-e80c4cbe310b.png)
Как мне вывести такое отображение?

**Comment by Ahaenor** [comment]
Добрый день!

На скриншоте изображён вывод кастомного шаблона платёжной формы, который был разработан специально под нужды сайта (miloserdie.ru).

Лейка поддерживает возможность использования таких отдельно разработанных шаблонов форм, но они не входят в неё как в продукт.

Я вижу такие варианты для этого случая:
 - Вы можете попробовать обратиться к администрации сайта miloserdie.ru и попросить их поделиться их разработкой.
 - Вы можете разработать такой шаблон самостоятельно.
 - Вы можете запросить помощь разработчика-волонтёра на сервисе [it-волонтёр](//itv.te-st.ru). Для этого нужно зарегистрироваться на it-волонтёре и создать задачу, описывающую вашу потребность.
 - Вы также можете заказать такую разработку Теплице социальных технологий. Мы готовы рассмотривать добавление нового шаблона в плагин на коммерческой основе.
