### ISSUE TITLE
Возможно ли добавить платежный шлюз ePay?

### ISSUE THREAD

**Issue by step4k** [Teplitsa/Leyka#133]
Здравствуйте! можно ли через ваше приложение (Leyka) настроить платежный шлюз банка KAZKOM (https://epay.kkb.kz/home) ???

**Comment by Ahaenor** [comment]
Добрый день!

Технически это вполне возможно. Вам понадобится:
 - информация об API этой платёжной системы,
 - PHP-программист.

Мы готовы оказывать любую консультативную помощь в процессе такой работы.

Альтернативный вариант - вы можете заказать разработку такого модуля нам (команде Теплицы социальных технологий). Но это будет заказ на коммерческих условиях. Если вам это интересно, пожалуйста, напишите на почту support@te-st.ru.
