### ISSUE TITLE
Подскажите где кнопка "Вкл" или "Отобразить"?

### ISSUE THREAD

**Issue by id095** [Teplitsa/Leyka#134]
Всем привет!

Настроил Способы, Кампании, Виджеты, 
А возможно ли показывать плагин на странице или в записи WP?

Спасибо

**Comment by Ahaenor** [comment]
Добрый день!

Чтобы вывести форму пожертвований в любом тексте записи, страницы (или даже виджета), используйте шорткод:

`[leyka_payment_form id=XXX]`

Здесь XXX - числовой ID кампании. Его можно узнать в админке Лейки, на странице "кампании".

**Comment by id095** [comment]
Спасибо большое, посоветую шорткоды прямиком около списков кампаний располагать, как по примеру контакт форм 7, прям лишних вопросов от блондинки не возникает :)

**Comment by Ahaenor** [comment]
Рады быть вам полезными :) Спасибо за обращение!

P. S. Кстати, шорткоды позволяют выводить не только форму пожертвования, но и все её "сопутствующие" элементы (список последних пожертвований, текст договора оферты и пр.). Если будет нужно подробное описание, пишите - мы сделаем приличную документацию по запросу от пользователей.

**Comment by id095** [comment]
да я уже просто взглянул в настройки (доперло блин ага))
там вроде все по инфо табам прям четенько ясно и лайтово, перегружать не стоит тоже

**Comment by Ahaenor** [comment]
👍
