### ISSUE TITLE
Подскажите примерно на что похожи поломки

### ISSUE THREAD

**Issue by id095** [Teplitsa/Leyka#135]
Подскажите примерно на что похожи поломки, где копать?
такой диковатый треш кишками сразу вылез, или это "норма"?:
http://joxi.ru/p27o9R5uonkv92.jpg
http://joxi.ru/12MpYeDhMw9nom.jpg

**Comment by Ahaenor** [comment]
Это точно не норма. Проблема, вероятно, в том, что где-то не закрыт HTML-тэг. Из-за этого поехала вся структура документа.

Я рекомендую начать отладку с понимания, после какой правки началась эта проблема.

**Comment by id095** [comment]
...ну я шорткод поставил пока что только)
видимо я гений верстки до этого, ладноть, буду валидировать, спасиб

**Comment by Ahaenor** [comment]
Ещё вариант причины: автоматическое экранирование кавычек в тексте поста. Иногда тема сайта делает это (например, через фильтр the_content).

**Comment by id095** [comment]
ага понял, попробую вникнуть, спасибо
