### ISSUE TITLE
Возможно ли подключения слива пожертвований на яндекс деньги?

### ISSUE THREAD

**Issue by id095** [Teplitsa/Leyka#136]
В настройках вижу только реквизиты Р/С и К/С (пока не вникал в магию как это все работает с деньгами правда),

А возможно ли подключения слива пожертвований на яндекс деньги?
Быть может давно известно где в яндексе посмотреть секретную страницу с реквизитами банка и собственного р/с и к/с? (обычно до нее мало кто доходит вроде)

**Comment by Ahaenor** [comment]
Смотря какой Яндекс вы имеете в виду.

Лейка поддерживает два способа получения средств с помощью Яндекса:
 - для юр. лиц (Яндекс.касса),
 - для физ. лиц (Яндекс.кошелёк).

Оба эти способа позволяют принимать средства через банк. карты или Яндекс.деньги.

1. Если вы имеете в виду Яндекс.кассу, то для заключения договора с ней вы уже должны иметь реквизиты счёта вашего юр. лица. Они точно есть в договоре с Кассой - копию можно запросить у вашего менеджера в службе поддержки Яндекс.кассы.

2. Если вы имеете в виду Яндекс.кошелёк (для физ. лица), то реквизиты должны быть в настройках вашего кошелька. Больше инфо вы сможете найти в документации по сервису Кошелька от Яндекса.
**Примечание:** если у вас есть юр. лицо, принимать средства с помощью второго способа (яндекс.кошелька) будет нарушением налогового законодательства.

**Comment by id095** [comment]
Понял, спасибо
