### ISSUE TITLE
Темы!

### ISSUE THREAD

**Issue by id095** [Teplitsa/Leyka#137]
Еще раз приветствую сердечно держателей супер проекта!

Такой вопрос - как я могу довести (или Вы поможете найти) нужную тему, похожую вот на эту верстку?
http://sredisvoih.orazvitii.ru/tzdaka/

Или какие варианты выхода есть:
- Какие могу задевать файлы шаблонов, чтобы не поломать обновления?
- Либо без вариантов править только CSS жесткими !important-конфликтами только извне, с того же Style.css?

**Comment by id095** [comment]
при всем при том все ссылки на проект Лейка будут рядом на видном месте, +я готов еще задонатить этому проекту (кстати сумма вероятно тоже будет неким решением моих хотелок!)

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо за вопрос.

Такая форма оплаты достаточно сильно отличается от тех, которые сейчас поддерживаются плагином.
Я бы рекомендовал вам реализовать отдельный специальный (т.е. кастомный) шаблон страницы кампании. Если при его разработке вы будете использовать API Лейки корректно, то никакие будущие обновления вам не повредят.

Вам даже не понадобится использовать !important в CSS - у вас просто будет целый отдельный набор стилей для ваших страниц кампаний.

Чтобы создать в теме вашего сайта кастомный шаблон кампании, добавьте в папку темы файл single-leyka_campaign.php.

В нём может быть любая разметка (например, как в шаблоне page.php вашей темы).
В эту разметку вы можете встроить кастомный код формы для пожертвований. Как выглядит такой код, вы можете увидеть в папке плагина, далее скрипты вида /templates/leyka-template-*.php

В этих скриптах используются функции для вывода различных полей и настроек плагина - например, суммы, почты донора, чекбокса для согласия с условиями и т.д.

Используйте эти функции Лейки в вашем шаблоне кампании, и обновления вам не повредят.

**Comment by id095** [comment]
КЛАСС! Я попробую, спасибо

**Comment by id095** [comment]
Добрый день, скопипастил шаблон в новый шаблон страницы в WP, не дает проходу единственная глобальная ошибочка http://joxi.ru/LmGjeyEfegXLVr.jpg
Возможно с этим шаблоном надо было как-то куда-то подмешать и папку Service? http://joxi.ru/J2b3V41SXgDy8A.jpg

**Comment by id095** [comment]
И вид какой-то лысый вывелся 
![_ _ _ _ _ _ _-_2016-12-27_11 28 18](https://cloud.githubusercontent.com/assets/13396469/21494036/0d2a2170-cc28-11e6-85d9-3940c01b51b7.png)

**Comment by id095** [comment]
Вместо того что по щелчку "Пожертвовать", который мной ожидался

**Comment by id095** [comment]
![_1_ _ _ _-_2016-12-27_11 27 23](https://cloud.githubusercontent.com/assets/13396469/21494050/2bedb5f4-cc28-11e6-81ce-0ec0ea15d9c6.png)

**Comment by id095** [comment]
....ладно я так чую придется конфликтами CSS всё ж таки

**Comment by Ahaenor** [comment]
Добрый день!

Вы скорпировали код одного из встроенных шаблонов формы, но этого самого по себе недостаточно:
1. Во-первых, он и выглядеть будет как встроенный, пока вы не напишете новую разметку и стили для формы (соотв., HTML и CSS).
2. Во-вторых, очевидно, встроенные стили конфликтуют с темой. Это видно, если сравнить облик формы на скриншоте с тем, как она должна выглядеть, когда всё в порядке: https://leyka.te-st.ru/campaign/demo-kampaniya-po-sboru-sredstv-shablon-bloki/

Чтобы решить эту проблему, вам нужно:
1. Снять с хука wp_enqueue_scripts метод enqueue_styles() класса Leyka. Это приведёт к тому, что встроенные стили Лейки не будут загружаться.
2. Написать и подключить разметку формы и стили для вашего шаблона формы. При этом в разметке нужно использовать функции Лейки, которые выводят различные элементы формы (например, поля суммы, имени и email донора).

**Comment by id095** [comment]
ок, подумал что копирну структуру хтмл этой тестовой страницы Лейки и только классы добавлю свои...

**Comment by Ahaenor** [comment]
В принципе, можно попробовать и так. Но вам придётся переопределять очень много свойств - у вас достаточно нестандартный шаблон формы. Я бы сразу писал свою разметку и классы.

Главное, избегайте хардкода в разметке формы. Вместо этого нужно использовать служебные функции Лейки для вывода элементов. Это интерфейсные обёртки, которые обеспечивают совместимость с будущими обновлениями плагина.

**Comment by id095** [comment]
В общем, вот что у меня вишло простой CSSонькой
http://sredisvoih.orazvitii.ru/campaign/tzdaka/
как будете мимо проходить свободным полетом - гляньте, ничего ль не забыл? Ничего не покарежил?

**Comment by Ahaenor** [comment]
Ок, вижу, что вполне прилично.

Что ещё я бы поправил:
1. Всплывающее окно с условиями договора оферты выводится под тёмным оверлеем, а не над ним.
2. Это окно содержит не текст договора, а реквизиты счёта организации (почему-то).
3. Звёздочки обязательности полей располагаются над полями формы, а не справа от них.
4. Текст "Я соглашаюсь с условиями сбора пожертвований" содержит ненужные переносы строк. В идеале, он должен идти одной строкой, сразу за чекбоксом.
5. Блоки с ошибками для полей сейчас имеют высоту несколько больше, чем нужно.

Но в целом, хорошая работа. Форма уже готова к отладке подключений к платёжным системам.

**Comment by id095** [comment]
юхууу!! Спасибо огромное за рецензию, буду на недельке править как от перегруза вылезу,
С Праздниками Вас!

**Comment by Ahaenor** [comment]
Спасибо :) Вас тоже!
