### ISSUE TITLE
Непонятный град ошибок

### ISSUE THREAD

**Issue by id095** [Teplitsa/Leyka#138]
Заполнил реквизиты с Р/С и К/С,
при попытках произвести платеж - на первом же шаге град ошибок
http://joxi.ru/4AkGozpcy0geMA.jpg
или
http://joxi.ru/KAgWoY8h4NBkeA.jpg

Выбираю платеж любым способом, или банковской картой, что это может быть, куда Лейка случайно постучалась?

**Comment by Ahaenor** [comment]
Добрый день!

Заполнение реквизитов юр. лица - только первый шаг настройки. Чтобы платежи через платёжную систему проходили, вы должны указать в настройках Лейки технические параметры вашего аккаунта. Какие именно параметры, зависит от платёжной системы, выбранной вами.

Подробнее о настройках нужных вам платёжных систем можно прочесть на официальном сайте Лейки: https://leyka.te-st.ru/docs/
