### ISSUE TITLE
Лишние или не лишние поля

### ISSUE THREAD

**Issue by id095** [Teplitsa/Leyka#139]
Добрейшего дня, Уважаемые Гении,
вот такой вопрос меня преследует и вроде как бы намекается что последний:

На странице кампании присутствуют почему-то 3 поля для ввода цифры
http://joxi.ru/Dr8Ny36F4JRnQ2.jpg

Их возможно как-то превратить в одно? Причем редактируется почему то одно верхнее...
Или я просто скрою их при помощи display:none , ничему не повредит?

Вот стр кампании: http://sredisvoih.orazvitii.ru/campaign/pozhertvovaniya-1/#leyka-payment-form

**Comment by Ahaenor** [comment]
Добрый день!

Поле, безусловно, должно быть одно. Каждое из них посвящено отдельной валюте (руб, USD, EUR). Но в каждый момент показывается только одно поле (т.к. выбрана только одна валюта). Ненужные, соответственно, скрываются с формы с помощью JS-кода Лейки (файл /js/public.js).

Если у вас они выводятся все сразу, это означает, что форме не хватает JS-кода. Он выполняет в т.ч. и валидацию полей (например, email донора и чекбокс согласия с условиями).

Т.к. у вас собственный (кастомный) шаблон формы, возможно, вам и JS для него понадобится отдельный. Вы можете взять нужный код из файла Лейки - public.js.

**Comment by id095** [comment]
Нет, я решил жестко конфликтами сделать, т.к. не до конца еще понял из каких конкретно инклудов копипастить кучки кода,

А файл public.js присутствует, скрин http://joxi.ru/DmBxLJNSwg3jLA.jpg

Адрес страницы я переименовал:
http://sredisvoih.orazvitii.ru/campaign/sredisvoih1/

**Comment by Ahaenor** [comment]
JS-код Лейки работает с разметкой полей от Лейки. Если нет конфликтов с CSS темы, то он работает правильно. В вашем случае, очевидно, конфликты есть.

Обратите внимание на классы всех 3-х полей. В них указаны валюты. Вам нужно скрыть и выключить все поля, не относящиеся к rur.

**Comment by id095** [comment]
Спасибо, понял
