### ISSUE TITLE
Сайт тормозит из-за плагина.

### ISSUE THREAD

**Issue by ver1000000** [Teplitsa/Leyka#14]
Поставили плагин на сайт http://www.cdrnsk.ru/. Теперь он тормозит.
При деактивации всё становится нормально. В чём может быть проблема?
Списко установленных плагинов:

Akismet	
All In One SEO Pack	
Auto_more
Contact Form 7	
Current Date & Time Widget
Custom Login	
Date and Time Widget
Donate Plus	
Dynamic Registration Links	
Events Manager	
Favicon Rotator
Google Analytics		
Google Calendar Events
HyperComments
JW Player 6 Plugin for Wordpress
Лейка	
Local Time Clock	
MiniMeta виджет
My Page Order
NextGEN Gallery by Photocrati
Replace WP-Version
RusToLat	
Tumblr Importer
UniSender
WordPress File Monitor Plus
WP-DownloadManager
WP-Webmoney
WP Bannerize
WP Clean Up
WP FullCalendar
WP YouTube
WSA Favicon
Xorbin Digital Flash Clock

**Comment by Ahaenor** [comment]
Добрый день.

1. Пожалуйста, проверьте, не создались ли избыточные копии страниц "спасибо за пожертвование" и "пожертвование не прошло". Если этих страниц явно больше одной каждого типа, то причина тормозов именно в этом.

Это известная ошибка, которая проявляется достаточно редко. Она будет исправлена в ближайшей версии плагина (конец марта-начало апреля).

2. Если указанные страницы есть всего в одном экземпляре, то причина тормозов неясна, и не обязательно она заключается в Лейке. Мы рекомендуем воспользоваться плагином для профилирования работы WordPress и отследить, на каких именно страницах что вызывает замедление.

Кроме того, можно попробовать отключить все плагины, кроме Лейки, и проверить скорость работы. Лейка сама по себе не нагружает сайт. Возможно, дело в конфликте с каким-то другим плагином.

**Comment by ver1000000** [comment]
Действительно. Имеет место конфликт с плагином Auto_more http://mywordpress.ru/plugins/auto-more/
В официальном каталоге его нет. Разрабатывался похоже "на коленке".

**Comment by Ahaenor** [comment]
Ок, спасибо за отчёт. К сожалению, мы не поддерживаем работоспособность Лейки с плагинами, не входящими в официальный репозиторий.

Отказ от этого плагина решит проблему.
