### ISSUE TITLE
Индивидуальные настройки для компаний

### ISSUE THREAD

**Issue by FunkyXL** [Teplitsa/Leyka#140]
Добрый день!
1. Возможно ли в будущем сделать индивидуальный настройки для разных компаний?
- Свой набор готовых сумм;
- Выбор доп полей для ввода данных.

2. Возможно сделать настройку - фиксирующую галочку ЕЖЕМЕСЯЧНЫЕ ПОЖЕРТВОВАНИЯ по умолчанию?

**Comment by Ahaenor** [comment]
Добрый день!

Да, это возможно и обязательно будет реализовано в одной из будущих версий. Точнее сказать пока сложно, но мы держим эту функцию в TO DO.

Спасибо за обращение!
