### ISSUE TITLE
Глюк с переводом способов платежей

### ISSUE THREAD

**Issue by Mobilkanokia** [Teplitsa/Leyka#141]
Добрый день!
Подскажите, пожалуйста, некоторые пункты способов платежей внутри кампании не переводятся на русский язык, хотя в файле leyka-ru_RU.po эти строки переведены на русский. В чем может быть причина?
Спасибо!
![screen shot 2017-01-22 at 15 12 36](https://cloud.githubusercontent.com/assets/18754015/22182350/e9f31d66-e0bc-11e6-9880-041e0f27635c.png)

**Comment by Ahaenor** [comment]
Добрый день!

Вероятная причина в том, что язык берётся не из файлов плагина, а из языкового массива сайта (/wp-content/languages/plugins/).
Быстрое решение:
* либо вручную удалить файлы Лейки оттуда,
* либо дождаться обновления плагина. В ближайшей версии перевод для языкового массива как раз будет обновлён.
