### ISSUE TITLE
Проблема с hhtps

### ISSUE THREAD

**Issue by sergsemeykin72** [Teplitsa/Leyka#143]
Приветствую!

Используем Лейку на wordpress, но после установки на сервер SSL сертификата он ругается на плагин из-за одной ошибки:
Mixed Content: The page at 'https://xn--90a2anb.xn--p1ai/' was loaded over HTTPS, but requested an insecure image 'http://xn--90a2anb.xn--p1ai/wp-content/uploads/2017/03/Logo-cristall.png'. This content should also be served over HTTPS.

Те. в коде прописан url начинающийся с http, а должен начинаться с https раз соединение защищенное. Как решить эту проблему, где подправить эту строку?
![default](https://cloud.githubusercontent.com/assets/26995981/24787017/1b799a7a-1b7f-11e7-8ca4-61e623f698ab.JPG)

**Comment by scufa** [comment]
К лейке, как таковой, это не имеет отношения. Возможно ошибка в теме - URL логотипа берётся без использования базового URL сайта. Остальные ссылки, как я вижу, генерируются правильно. Поищите в теме то место, где логотип выводится.

**Comment by sergsemeykin72** [comment]
Хорошо, спасибо полазим поищем. 

Второй вопрос появился. Письма уведомления, реально ли сделать что бы они отправлялись с нашего mail сервера? Сейчас используется любой адрес почты и отправка идет через хостера - Gmail такие письма не очень любит к примеру, а если что и в спам их загонит легко.

**Comment by scufa** [comment]
Реально. Надо чтобы ваш сервер поддерживал отправку через SMTP. Ставьте плагин - https://ru.wordpress.org/plugins/wp-mail-smtp/

Можно его настроить, чтобы он и через gmail-ящик слал письма, т.к. gmail позволяет отсылку через SMTP.

**Comment by Ahaenor** [comment]
@scufa , спасибо за ответы! Закрываю ветку.
