### ISSUE TITLE
Не удаётся подключить русский язык

### ISSUE THREAD

**Issue by KitsenkoDmitry** [Teplitsa/Leyka#144]
![image](https://cloud.githubusercontent.com/assets/20664568/24865114/f5e96794-1e0e-11e7-901c-2324d1b08854.png)

Здравствуйте. 
Не получается русифицировать Лейку. Сайт работает на русском языке. В настройках тоже стоит русский, а сама Лейка включилась на английском.
В чем может быть дело?

**Comment by Ahaenor** [comment]
Добрый день!

Вероятнее всего, причина в том, что сайт не загрузил русскую локализацию "Лейки" при её установке.
Попробуйте зайти в Консоль - Обновления - внизу страницы "Обновить переводы".

Если это не решит проблему, обязательно сообщите.

Спасибо за обращение!

**Comment by KitsenkoDmitry** [comment]
Да, спасибо. По большей части помогло. Но вот, например, вот эта строка не перевелась 
![image](https://cloud.githubusercontent.com/assets/20664568/24873284/ec5ac0d2-1e28-11e7-913c-f02923c2c103.png)

**Comment by Ahaenor** [comment]
Ок, понял вас.

Эта строка хранится в БД сайта с момента активации плагина - перевод применяется только к её значению по умолчанию.

Чтобы перевести её после активации, нужно вручную изменить её значение в разделе Лейка - Настройки - Платёжные системы - соотв. вариант в блоке для перестановки/переименования способов оплаты.

**Comment by VitalyKondratiev** [comment]
Здравствуйте, у меня та же проблема, установил плагин, и не могу перевести его на русский. В разделе обновлений Wordpress сказано что переводы не требуют обновления. Возможно ли установить файлы перевода вручную?

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо, вопрос понятен.
Мы постараемся ответить до конца этой недели.
