### ISSUE TITLE
Ошибка "Вы указали некорректный email"

### ISSUE THREAD

**Issue by almaz74** [Teplitsa/Leyka#145]
Здравствуйте. С некоторых мобильных телефонов при заполнении формы на сайте выдается ошибка "Вы указали некорректный email" - хотя поле заполнено верно и при идентичном заполнении с другого телефона всё нормально. У кого-то ошибка появляется, у кого-то всё нормально. В чём может быть причина?

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо за обращение. Ранее мы не встречались с такой проблемой - будем ловить.

На каких устройствах, ОС и браузерах это можно увидеть?

**Comment by almaz74** [comment]
Sony Xperia, браузер Google Chrome
И ещё у других тоже была такая ошибка, но там не спрашивали пока модель и ОС
![image-0-02-05-18a3570635f0849d44d1ac3e7e4af96bda0fa8df5aed6e5d961b325ea99da83b-v](https://cloud.githubusercontent.com/assets/27674551/25085974/614f7e50-237e-11e7-8a57-9bb0d68629f2.jpg)
![image-0-02-05-578d0623063ac8c5f0aecbe36a2b1460f727aa3c999b500ceb69a572d88bce85-v](https://cloud.githubusercontent.com/assets/27674551/25085975/61509d76-237e-11e7-9fd2-5e35d4a2b6cf.jpg)

**Comment by Ahaenor** [comment]
Ок, спасибо, мы проверим.
Если будут ещё сведения о моделях/ОС/браузерах с ошибкой, пожалуйста, сообщите.
