### ISSUE TITLE
Регулярные платежи Хронопей

### ISSUE THREAD

**Issue by tatarin93** [Teplitsa/Leyka#146]
Добрый день! Настраиваю ваш  плагин на сайте и возникли некоторые конфликты с поддержкой Хронопея по регулярным платежам. Прошу Вас подсказать текущую логику работы с регулярными платежами системы Хронопей. На сколько я вижу работа организована следующим образом: 
1) Хронопей регистрирует product, помечаемый, как регулярный. Интервал платежей фиксируемый, например, месяц. Входная сумма для данного product'а может быть разная, в зависимости от того какую сумму введет донор.
2) Соответствующий product_id я в вожу в поле "product_id для регулярных пожертвований в рублях".
3) Параметры POST запроса, отправляемые в адрес хронопей аналогичны параметрам разового платежа (только указывается иной product_id).
Не могли бы Вы поправить меня, если я не прав. Так как поддержка хронопея утверждает, что может создать продукт только с фиксированной суммой и фиксированным интервалом. Однако, я вижу, что ваш плагин успешно работает с регулярными платежами, например, на сайте http://vverh.su/campaign/help/
Заранее благодарю за ответ!

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо за вопрос. В целом, вы верно описали ситуацию.

Когда мы последний раз настраивали интеграцию рекарринга через Хронопей, у них была возможность сделать рекуррентный продукт с известной валютой и интервалом, но с переменной суммой.
Работа рекарринга в Лейке основывается именно на этом - в настройках Хронопей нужно указывать 1 продукт для рекарринга, а не множество.

Возможно, политика Хронопей в части возможностей рекуррентных продуктов изменилась с тех пор, как мы имели с ними дело. Но все существующие интеграции работают, насколько я могу судить.

**Comment by tatarin93** [comment]
Спасибо большое за помощь!
