### ISSUE TITLE
Call to undefined function leyka_options()

### ISSUE THREAD

**Issue by titov-andrei** [Teplitsa/Leyka#147]
Ошибка возникает в момент активации плагина

`Fatal error: Uncaught Error: Call to undefined function leyka_options() in /home/users/j620423_wp1/site/wp-content/plugins/leyka/inc/leyka-polylang.php:187 Stack trace: #0 /home/users/j620423_wp1/site/wp-content/plugins/leyka/leyka.php(82): require_once() #1 /home/users/j620423_wp1/site/wp-admin/includes/plugin.php(1882): include('/home/users/j62...') #2 /home/users/j620423_wp1/site/wp-admin/plugins.php(164): plugin_sandbox_scrape('leyka/leyka.php') #3 {main} thrown in /home/users/j620423_wp1/site/wp-content/plugins/leyka/inc/leyka-polylang.php on line 187`

**Comment by Ahaenor** [comment]
Добрый день!

Эта ошибка исправлена - переустановка плагина из официального репозитория должна решить проблему.

Спасибо за обращение!
