### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function leyka_options()

### ISSUE THREAD

**Issue by sergeybrava** [Teplitsa/Leyka#148]
Обновление плагина на сайте fond39.com привело к падению. Работает на PHP7.

`Fatal error: Uncaught Error: Call to undefined function leyka_options() in /home/f/fr790993/fond39.com/public_html/wp-content/plugins/leyka_old/inc/leyka-polylang.php:187 Stack trace: #0 /home/f/fr790993/fond39.com/public_html/wp-content/plugins/leyka_old/leyka.php(82): require_once() #1 /home/f/fr790993/fond39.com/public_html/wp-admin/includes/plugin.php(1882): include('/home/f/fr79099...') #2 /home/f/fr790993/fond39.com/public_html/wp-admin/plugins.php(164): plugin_sandbox_scrape('leyka_old/leyka...') #3 {main} thrown in /home/f/fr790993/fond39.com/public_html/wp-content/plugins/leyka_old/inc/leyka-polylang.php on line 187`

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо за обращение. Эта ошибка уже исправлена - переустановите плагин из официального репозитория, это должно устранить проблему.
