### ISSUE TITLE
Статус пожертвования неверно отображает данные.

### ISSUE THREAD

**Issue by AleksandrPulyak** [Teplitsa/Leyka#149]
Добрый день!
При внесении пользователем разового пожертвования статус пожертвования постоянно указывается как "попытка пожертвовать", несмотря на фактический результат (даже если оплата прошла).
Оплачивают с банковских карт, Яндекс-кошелька. Перевод происходит на Яндекс счёт физического лица.
В чём может быть проблема?

**Comment by Ahaenor** [comment]
Добрый день!

Наиболее вероятная причина - неправильно указан URL для обратной связи в настройках вашего Яндекс.кошелька.
Об этом можно прочитать в предпоследнем абзаце нашей инструкции по настройке Яндекс.кошелька: https://leyka.te-st.ru/docs/podklyuchenie-yandeks-dengi-dlya-fizicheskih-lits/

**Comment by sgtwhite** [comment]
Та же проблема. Ставлю в настройках Яндекса ссылку вида https://persona4.ru/leyka/service/yandex_phyz/response/

Сам сайт ессна расположен по https://persona4.ru Что тут может быть не так?
