### ISSUE TITLE
Поддержка объявленных кампаний

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#15]
Вот появилась такая идея. Маленький сайт некоммерческой организации с установленной Лейкой всегда будет проигрывать большим краудфандинговым площадкам. Для развития плагина мне кажется требуется хоть и небольшая, но инфраструктура поддержки.

Собственно, очень хочется посмотреть на все (или не все, а многие) кампании, сделанные по технологии Лейки где-то в одном месте. Авторам кампаний как воздух необходима поддержка их объявленных кампаний в интернете, поиск сочувствующих доноров по тематикам деятельности.

Предлагаю сделать интернет-ресурс, на котором будут выводиться карточки кампаний, где посетитель может посмотреть, оценить, выбрать многое из многого. По сути, по внешнему виду это должно походить на одну большую краудфандинговую площадку.

Для всего этого, предлагаю в плагин встроить функцию пингования удаленного сервера при публикации кампании, автоматический сбор информации об объявленной кампании и вывод ее карточки на едином общем ресурсе. В настройках можно сделать чекбокс, включающий или отключающий функцию сообщения об объявленных кампаниях на единый ресурс.

Также предлагаю у типа записей кампания сделать отдельную систематику, чтобы разные кампании можно было разделить по разным тематикам и выводить их на сайтах разным образом. На мой взгляд, необходимо большие организации поощрять  на установку плагина в первую очередь. Организации, ведущие одновременно несколько кампаний (именно в этой гибкости за счет автономности преимущества Лейки перед большими площадками) мне кажется могут стать двигателем развития плагина. Если организация объявляет более 5 кампаний на Лейке, то уже возникает необходимость какой-то группировки кампаний, вывода карточек в определенном порядке, по определенным условиям. При реализации возможностей вывода кампаний разных организаций на сводных ресурсах (мультисайтовые сети, единые площадки для раскрутки) вопрос наличия сортирующих систематик будет важен.

**Comment by Ahaenor** [comment]
Олег, добрый день!

Ок, спасибо за подробное предложение. Мы обсудим и ответим подробно.

**Comment by Ahaenor** [comment]
Добрый день.

В настоящее время Теплицей планируется создание подобного ресурса-аккумулятора информации о пожертвованиях различных организаций. Первые шаги в разработке уже сделаны, ожидайте продолжения :)

Спасибо за интерес к нашему продукту.
