### ISSUE TITLE
errorDepositionNotificationUrl

### ISSUE THREAD

**Issue by Mobilkanokia** [Teplitsa/Leyka#150]
Добрый день.
Оформляем рекуррентные платежи через Яндекс.Касса. В технической анкете Организации есть поле для заполнения - URL для уведомления о возврате (errorDepositionNotificationUrl). Подскажите, пожалуйста, где его взять.
Спасибо.

**Comment by Ahaenor** [comment]
Добрый день.

В настоящее время Лейка не использует этот коллбэк. Мы узнаем у Яндекс.Кассы, является ли он необходимым для подключения рекарринга через них - если этот так, то мы добавим поддержку в Лейку в течение ближайших нескольких дней.

**Comment by Ahaenor** [comment]
Получен официальный ответ от поддержки Яндекс.Кассы.

Как и ожидалось, для подключения рекарринга **поле errorDepositionNotificationUrl можно не заполнять**.

Спасибо за обращение!

**Comment by Mobilkanokia** [comment]
Спасибо большое!
