### ISSUE TITLE
Не проходят рекуррентные платежи CloudPayments

### ISSUE THREAD

**Issue by SemenAltabasov** [Teplitsa/Leyka#152]
Здравствуйте! Возникла проблема c рекуррентными платежами через сервис CloudPayments. При пожертвовании указанная сумма перечисляется, но в ЛК CloudPayments в разделе "Подписки" не появляется новая подписка. В информации о пожертвовании поле "ID подписки на рекуррентные платежи:" остается пустым. При этом рекуррентные платежи с ВКонтакте добавляются в "Подписки".
Поддержка CloudPayments говорит что с их стороны все нормально, но исходники плагина никак не изменялись. В чем может быть проблема? Спасибо.

**Comment by Ahaenor** [comment]
Ок, спасибо за сообщение.

Ошибка исправлена и войдёт в ближайший релиз хотфиксов (2.3.1).
Мы планируем выпустить его сегодня к вечеру.
