### ISSUE TITLE
Статус пожертвования неверно отображает данные.

### ISSUE THREAD

**Issue by sgtwhite** [Teplitsa/Leyka#153]
> Добрый день!
> При внесении пользователем разового пожертвования статус пожертвования постоянно указывается как "попытка пожертвовать", несмотря на фактический результат (даже если оплата прошла).
> Оплачивают с банковских карт, Яндекс-кошелька. Перевод происходит на Яндекс счёт физического лица.
> В чём может быть проблема?

У меня те же сложности - только не надо как в предыдущий раз отправлять меня курить мануал, я излазил его более чем полностью. Ставлю в настройках Яндекса ссылку вида 

https://persona4.ru/leyka/service/yandex_phyz/response/

Сам сайт ессна расположен по https://persona4.ru Что тут может быть не так?

**Comment by Ahaenor** [comment]
Добрый день.

Ссылка правильная, но она справедлива для сайта, на котором включены пермалинки (они же красивые ссылки или ЧПУ).
На вашем сайте сейчас они не задействованы, поэтому в ответ на УРЛ коллбэка отдаётся страница 404.

Варианты решения:
- Самое разумное, как нам кажется, включить пермалинки (админ. раздел сайта - настройки - постоянные ссылки).
- Альтернатива - в настройках Яндекс.кошелька указать УРЛ так: https://persona4.ru/?leyka/service/yandex_phyz/response/
