### ISSUE TITLE
Повторные платежи Яндекс кассы

### ISSUE THREAD

**Issue by lo7ev** [Teplitsa/Leyka#154]
В какой момент происходит запоминание повторного платежа? Когда человек отправляет форму с галочкой или когда Яндекс возвращает payment aviso с rebillingon=1?
Сорри за офтоп, но можно ли использовать самоподписанный сертификат, или необходимо приобрести его?

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за вопрос.

> В какой момент происходит запоминание повторного платежа? Когда человек отправляет форму с галочкой или когда Яндекс возвращает payment aviso с rebillingon=1?

Запоминание в БД сайта происходит при нажатии донором кнопки отправки формы пожертвования. После payment aviso происходит переход пожертвования (и рекуррентной подписки) в активное состояние.

> Сорри за офтоп, но можно ли использовать самоподписанный сертификат, или необходимо приобрести его?

Смотря для чего.

- Для коллбэков разовых платежей через Яндекс.Кассу можно создать самоподписанный (и зарегистрировать его в Яндексе через техн. специалиста, который сопровождает подключение) либо купить полноценный (тогда ничего регистрировать не нужно). Кстати, некоторые хостинги предоставляют полноценные сертификаты бесплатно (Timeweb).
- Для коллбэков рекуррентных платежей через Яндекс.Кассу сертификат выпускает сама Касса по вашему запросу и передаёт сертификат вам для установки на сервере.

Спасибо за обращение!

**Comment by lo7ev** [comment]
Спасибо большое. Есть ещё вопрос. Хо елось бы проконсультироваться. Я бы
хотел проводить оплату на стороне Яндекса(банковскими картами). У меня на
сайте есть форма которая открывает Яндекс кассу. После подключение
сертификата в форму добавиться галочка для рекуррентных платежей. Могу ли я
просто форму отправлять сначала не в Яндекс, а в какой-то ваш скрипт? Где
она соответственно будет запоминаться(в случае рекуррентного платежа) А
дальше снова будет переадресация в Яндекс? Просто не хотелось бы городить
отдельно все эти функции для повторных платежей и баз данных, а хотелось бы
использовать ваш продукт. А формы я так понял у вас уже со своими стилями.
Если что-то путаю, извините.

**Comment by Ahaenor** [comment]
В Лейке данные формы пожертвования уже сейчас сначала обрабатываются бэкендом, и только потом происходит редирект на Яндекс.Кассу для платежа.

Также в Лейке вы можете создать собственный шаблон формы (со своими стилями). Для этого создайте шаблон страницы кампании в теме вашего сайта (single-leyka_campaign.php) и используйте в нём функции API Лейки для вывода полей платёжной формы. Такая форма будет выглядеть, как вам нужно, вести себя как одна из встроенных форм плагина и не отвалится при обновлениях Лейки.

Пример такого подхода: https://korablik-fond.ru/campaign/help-us/

**Comment by lo7ev** [comment]
Спасибо большое, будем пробовать с:

**Comment by lo7ev** [comment]
1)Не могли бы дать ссылку на документацию по API.  Не могу найти.
2)у меня не отдельная страница с пожертвованиями, а просто одна вкладка в
менюшке. Короче, можно осуществить взаимодействие с бэкэндом лейки,
используя JS и правильно заполнив атрибуты тега form и его инпутов?
