### ISSUE TITLE
Leyka API

### ISSUE THREAD

**Issue by lo7ev** [Teplitsa/Leyka#155]
Не могу найти документацию к API. Куда отправлять формы? Как должны называться поля, чтобы все правильно обработалось?

**Comment by Ahaenor** [comment]
Вся существующая документация по API Лейки находится здесь, в гитхабе проекта, [в разделе Wiki](https://github.com/Teplitsa/Leyka/wiki/). Как можно видеть, статей очень мало.

Чтобы узнать, куда отправлять формы и каким должен быть набор полей, отправьте пожертвование с любой встроенной формы Лейки и на странице "Сейчас вы будете перенаправлены на платёжную систему" откройте исходный код в браузере. В коде нужно будет найти форму Лейки, она будет содержать нужный набор полей.

Если необходима более подробная информация, её можно найти в коде самого плагина. В его корневой папке есть подпапка gateways (модули поддержки платёжных операторов), в ней - подпапки соотв. операторов, в них - скрипты leyka-class-GATEWAY_ID-gateway.php.

В этих скриптах содержатся подклассы Leyka_Gateway. В них есть методы:
 - submission_redirect_url() - возвращает УРЛ, куда нужно отправлять форму для данного оператора,
 - submission_form_data() - возвращает ассоциативный массив полей этой формы.
