### ISSUE TITLE
Удаление плагина

### ISSUE THREAD

**Issue by PavelZX** [Teplitsa/Leyka#156]
При попытке удалить плагин стандартными средствами, появляется надпись удаление и вверху удаление не удалось. Вордпресс последний WordPress 4.8.

Версия: 2.3.1

**Comment by Ahaenor** [comment]
Добрый день!

Для корректного удаления в этой версии нужно отметить одну или обе галочки в настройках плагина, в разделе "Разное -> Удаление данных плагина".

В ближайшей будущей версии эта ошибка будет устранена - плагин будет удаляться корректно и без этих отметок.

Спасибо за обращение!
