### ISSUE TITLE
Не отображаются платежи

### ISSUE THREAD

**Issue by Leopays** [Teplitsa/Leyka#157]
Добрый день. 
После создания кампании, перехожу к оплате помощи.
Оплата проходит , деньги поступают на кошелек, но в кабинете и на сайте ничего не меняется.
Надпись, не получен ответ от платежной системы.

Проверял Робокасса и яндекс физ лица

**Comment by Ahaenor** [comment]
Добрый день!

Я правильно понимаю, что при выполнении платежа запись о нём появляется в админ. разделе сайта на странице "Пожертвования", но статус платежа остаётся "Попытка платежа"?

**Comment by Leopays** [comment]
Да, все верно

**Comment by Ahaenor** [comment]
Вероятнее всего, не настроены адреса для коллбэков (техн. уведомлений) платёжных систем.
Вам нужно зайти в личный кабинет Робокассы и Яндекс.кошелька и указать там специальные адреса вашего сайта, по которым он будет уведомляться о проведённых платежах.

Как выполнить эту настройку, подробно сказано в инструкции по Лейке:

- Робокасса: https://leyka.te-st.ru/docs/podklyuchenie-robokassa/
- Яндекс.кошелёк: https://leyka.te-st.ru/docs/podklyuchenie-yandeks-dengi-dlya-fizicheskih-lits/

**Comment by Leopays** [comment]
У меня сайт вордпресс  установлен в папку В платежках прописаны такие адреса https://donate.leopays.com/campaign/leyka/service/robokassa/response/
https://donate.leopays.com/campaign/leyka/service/yandex_phyz/response/

**Comment by Leopays** [comment]
Я вижу что ошибка, но не могу понять как прописать адрес

**Comment by Ahaenor** [comment]
Ок, понял вас.

Проблема в том, что по данным адресам ваш сайт отдаёт страницу 404.
Это происходит из-за того, что у вас не включен режим постоянных ссылок.

Включить его можно в админ. разделе сайта, на странице "настройки - постоянные ссылки".
Для включения выберите любой вариант, кроме первого, и сохраните настройки.

**Comment by Leopays** [comment]
Спасибо
