### ISSUE TITLE
Документы публичных оферт в шаблонируемые страницы

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#158]
Вот оферта о благотворительном пожертвовании и соглашение о персональных данных прекрасно что в модальном окне открываются, но хотелось бы иметь постоянную ссылку на оба документа, чтобы куда-то в список к другим документам приделать и открывать как обычную запись.

имеет смысл вывести функционал шаблонов этих документов из плагина на внешние страницы, в плагине сделать выбор страницы как с политикой конфиденциальности. Просто когда контент документа вручную редактировать и там и там, то скорее всего кто-то позабудет синхронизировать версии при внесении изменений, и получатся разные документы.

Шаблонирование с переменными это отличная мысль, просто сохранять бы это в отдельные страницы с постоянными ссылками, как например страница с благодарностью.

Ну и кстати, после некоторых размышлений, подумалось, что данные организации, которые забиваются в настройках лейки имеет смысл сделать доступными в любом месте сайта. Может шорткодами, может какими-то переменными, чтобы использовать помимо прямого функционала Лейки. Полное название организации, руководитель, реквизиты требуются в разных местах сайта, для формирования разных публичных и презентационных документов организации, и чтобы не копипастить везде вручную, можно использовать данные, забитые в одном месте.

Вот под другие задачи, не связанные с Лейкой, хотел написать или приспособить нехитрый плагин позволяющий использовать данные организации в разных местах сайта. Подключение нового плагина это конечно лишний запрос, но иногда действительно утомляет копипастить одну и ту же информацию на разных страницах, а потом снова искать и заменять ее, если сменился руководитель, или адрес, или контакты, или что-то еще. Ну и иногда есть потребность выводить какие-то формируемые посетителем документы, создаваемые по шаблону с данными организации. 

Может правда, изъять из Лейки функционал формирования документов по шаблонам, сделать отдельный подключаемый и работающий с Лейкой плагин, который мог бы работать и автономно без использования Лейки?

Если бы такое шаблонирование было в одной экосистеме с Лейкой, то было бы замечательно.

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо за предложение. Это интересные идеи.

1. Страница для условий использования перс. данных уже есть, она создаётся автоматически (вместе со страницами "Спасибо" и "Ошибка платежа").

2. Отдельную страницу для текста оферты - ок, мы добавим.

3. Синхронизация текстов в модальных окнах и на соотв. страницах - записали в бэклог.

4. Шорткоды для вывода данных НКО в любом месте сайта - также могут появиться в будущих версиях.

Но делать отдельный плагин под такие данные, на мой взгляд, это архитектурное переусложнение.
В нашей практике они нужны ситуативно - шорткоды с такой задачей прекрасно справятся.

Спасибо за обращение!
