### ISSUE TITLE
Как поменять надпись на кнопке?)

### ISSUE THREAD

**Issue by RAlzar** [Teplitsa/Leyka#159]
Здравствуйте!

Подскажите, как можно поменять надпись"ПОДДЕРЖАТЬ" в форме, которая отображается в результате размещения кода "Встраивание кампании"?)

https://drive.google.com/open?id=0B1jUIdeYpYopRXdlRmRXdzJtQmM

С уважением
Руслан Писанка

**Comment by Ahaenor** [comment]
Добрый день.

На данный момент изменить надпись на указанных кнопках невозможно через настройки плагина.
Вы можете изменить её напрямую в коде.

Спасибо за обращение!

**Comment by RAlzar** [comment]
Если можно подскажите, код какого именно файла для этого нужно редактировать?)

**Comment by Ahaenor** [comment]
Это можно сделать в файле /inc/leyka-shortcodes.php в строке 78:

`return 'ВАШ ТЕКСТ ДЛЯ КНОПКИ';`

**Comment by RAlzar** [comment]
Спасибо, получилось, но лучше, конечно-же, предусмотреть возможность менять эту надпись в настройках.

С уважением и наилучшими пожеланиями
Руслан Писанка
