### ISSUE TITLE
глюки обновления 2.2.5

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#16]
Нажал обновить, все обновилось. На странице настроек первые три вкладки настроек пустые http://prntscr.com/6w7fmi

email, вид, разное показывает нормально.

Криво выдает виджет карточки кампании и ломает сайдбар. Сайт вешается и думает по 2 минуты открывая главную. Удаление виджета карточки кампании из сайдбара разгружает немного.

Откатываюсь на 2.2.4

**Comment by Ahaenor** [comment]
Ок, это исправлено. Можно заново обновиться до 2.2.5, все страницы настроек должны остаться на месте.

Спасибо за обращение.

**Comment by olegtkirov** [comment]
Спасибо, работает. 
Есть еще один неожиданный эффект. Если у кампании не заполненно "Аннотация", то в виджет карточки кампании в поле аннотации берется текст с разметкой со страницы, на которой выводится виджет. Получается полный бред. У меня например на главной в аннотацию умудрилась залезть двухколоночная grid разметка главной страницы с виджетами и контентом, при этом разумеется вся верстка сломалась. На других записях взялся весь видимый контент.

В версии 2.2.4 карточка без цитаты отображалась нормально. 
После заполнения поля аннотации все нормализовалось.
Понятно, что аннотацию надо заполнять, но вот такой эффект есть, и кто из неопытных людей не досмотрит, будет сильно удивлен внешним видом.

**Comment by Ahaenor** [comment]
Ок, спасибо. Вы могли бы предоставить страницу, где можно увидеть этот эффект расползания?

**Comment by olegtkirov** [comment]
http://prntscr.com/6wx8ah
И эта же кампания в виджете на другой странице 
http://prntscr.com/6wx96d
А на главной, где в контент страницы встроены блоки, там вобще что попало
http://prntscr.com/6wxat3 ну и несколько километров виджета кампании вниз циклически повторяя саму себя http://prntscr.com/6wxbmp 

К слову заметить, такое возникает при пустом теле кампании и пустой аннотации. Если добавить текст в тело кампании, берет его. Если аннотацию, то берет ее. У меня кампания висела пустая, для тестовых целей, вот ее и перекорежило.

**Comment by Ahaenor** [comment]
Добрый день.

Мы готовы заняться этой проблемой вплотную и включить фикс в ближайший релиз.
Можете предоставить доступы в админку сайта? Если да, то пожалуйста, вышлите их на почту ahaenor@gmail.com

**Comment by Ahaenor** [comment]
Добрый день.

Мы хотели бы решить этот тикет или закрыть его.

Вы готовы предоставить доступ в админку сайта?
Мы понимаем, что это ответственное решение, поэтому, если вы решите отказаться, никаких вопросов с нашей стороны не последует.

**Comment by olegtkirov** [comment]
Я могу предоставить доступ в админку, без проблем, но я написал уже небольшое описание кампании и краткое описание, проблема не проявляется. Проблема была когда создана кампания и в ней нет ни краткого описания ни полного текста, тогда если кампанию состоящую только из заголовка вывести виджетом в карточку кампании в сайдбар, то вместо описания он берет все что видит на странице вместе с разметкой. После обновления Лейки не пробовал создавать пустую кампанию.

Доступ в админку вроде есть уже  http://prntscr.com/7mpovi  Могу еще кому-то предоставить.

Олег.


Понедельник, 29 июня 2015, 4:19 -07:00 от Lev Zvyagintsev <notifications@github.com>:

**Comment by Ahaenor** [comment]
Ок, спасибо. Мы смогли вызвать эту ошибку самостоятельно. Фикс войдёт в следующую версию (2.2.7).

Благодарим вас за багрепорт.
