### ISSUE TITLE
не работают рекуррентные платежи

### ISSUE THREAD

**Issue by lo7ev** [Teplitsa/Leyka#160]
Здравствуйте, подключил яндекс кассу с рекуррентными платежами. Сертификаты и прочие формальности выполнены. Но перестало получаться сделать тестовый рекуррентный платеж. Есть платеж со статусом funded и типом rebill. Вызываю do_recurring, но новые платежи не появляются. Так же отсутсвует настройка email для подписчиков на регулярные платежи.

**Comment by Ahaenor** [comment]
Добрый день!

1. Настройка email-ов для подписчиков на рекарринг - это известная проблема.
Это ошибка, её исправление войдёт в ближайшую новую версию Лейки.

2.1. Я правильно понимаю, что раньше тестовый рекарринг работал правильно, и rebill-платежи со статусом "funded" при вызове /do_recurring/ появлялись?

2.2. Проверьте, пожалуйста, активна ли рекуррентная подписка, на которой вы тестируете?
Для неактивных подписок новые платежи появляться не должны.

**Comment by lo7ev** [comment]
Добрый день, да, подписка активна. Я даже создаю новую подписку, но после
do_reccuring новые платежи не появляются.

**Comment by lo7ev** [comment]
Обновил лейку. Появилась настройка email. Спасибо.
И теперь можно прямо из письма отменять подписку! Ура!
Но, после нажатия на ссылку для отписки, статус подписки остается active.
do_recurring по прежнему не повторяет платеж с подпиской.

**Comment by Ahaenor** [comment]
Добрый день!

А вы на последних тестах пробовали отменить рекуррентную подписку из старых писем?

Нужно делать это из новых писем.
Лучше всего создать новую подписку, сделать по ней первое списание через do_recurring, получить и попробовать отменить подписку из него.
Но из первого письма тоже должно отменяться.

Пожалуйста, сообщите о результатах.

**Comment by lo7ev** [comment]
О, платежи стали появляться. только они не funded, а только submitted. Так и должно быть? Отписка работает. И еще один вопрос. Я вместо готовой формы, просто взял input ы из вашей форм. И иногда с моей формы перекидывает на вашу из-за ошибки. Я так понимаю это из-за поля _wpnonce значение которого меняется. Можно ли этого избежать?

**Comment by Ahaenor** [comment]
1. Рекуррентные платежи остаются в статусе "попытка" (submitted), если неправильно указаны настройки рекарринга - либо в Лейке (в настройках Яндекс.Кассы), либо на стороне самой Кассы.

Мы бы рекомендовали связаться с техн. поддержкой Кассы и проверить:
 * правильный ли SSL-сертификат указан в Лейке,
 * правильный ли IP-адрес сайта указан на стороне Кассы,
 * получают ли на стороне Кассы запросы на рекарринг от вас,
 * и если да, то что отвечает ваш сайт на техн. уведомления Кассы о платежах.

2. Некорректная переадресация при ошибке платежа - да, это происходит из-за того, что вы скопировали поля формы. Но дело не в поле nonce, а в другом, где передаётся адрес страницы ошибочного платежа. Вам нужно заменить значение этого поля на адрес соотв. страницы на вашем сайте. Обычно такое поле называется "failure_page".

**Comment by lo7ev** [comment]
Я не могу найти такого поля. Иногда моя форма(когда какие-то данные
некорректны) перекидывает на страницу компании с таким добавлением
#leyka-submit-error

**Comment by Ahaenor** [comment]
Ок, понял вас.

Тогда дело, безусловно, в поле "nonce".
Сам принцип этого поля предполагает, что значение не копируется откуда-то, а генерируется при каждой загрузке формы.

**Comment by lo7ev** [comment]
Я так и думал. Похоже по простому не получится сделать форму со своим
дизайном.

**Comment by Ahaenor** [comment]
Ваш подход всё ещё возможен - просто надо заменить в коде формы статический вывод значения поля nonce на функцию WordPress. Например, `wp_create_nonce()`.

**Comment by lo7ev** [comment]
Поддержка яндекса просит указать полный адрес, куда идет запрос, xml запрос с параметрами и полный текст получаемого ответа. Как можно получить эти данные?

**Comment by Ahaenor** [comment]
Вопрос непонятен. Мы говорим сейчас о разовых или рекуррентных платежах?

**Comment by lo7ev** [comment]
Рекуррентных

**Comment by Ahaenor** [comment]
Ок, понял вас. Мы проясним вопрос с техн. поддержкой Яндекс.Кассы напрямую.

Пришлите, пожалуйста, на почту support@te-st.ru:
 * адрес вашего сайта,
 * доступ в админ. раздел сайта - аккаунт уровня "администратор" или "администратор пожертвований".

**Comment by lo7ev** [comment]
Здравствуйте, вам дошло письмо?
Долго ли будет происходить настрйока?

**Comment by Ahaenor** [comment]
Добрый день.

Причины могут быть очень разными.
Если вы выполнили все настройки по инструкции (https://leyka.te-st.ru/docs/yandex-dengi/), проблема может быть на стороне Яндекс.Кассы.

Мы бы рекомендовали попросить вашего менеджера из Кассы связать вас с их техн. специалистами.
Они должны подсказать детально, что происходит при вызове do_recurring.

**Comment by pyotr** [comment]
@Ahaenor Здравствуйте - написал вам на почту, да вроде проверяли с техническими специалистами с кассы - все в порядке с подключением..
