### ISSUE TITLE
поправка стилей в шаблоне Нео

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#161]
Быть может мешаются стили темы или еще что, но без поправки выглядит вот так:
http://prntscr.com/gc2zpi

Вывод стилей получается такой:
.leyka-tpl-neo#leyka-payment-form .leyka-field.amount-selector .figure .rdc-radio__label {
    color: rgba(0, 0, 0, 0.9);
    font-family: Helvetica,sans-serif;
    font-size: 28px;
    display: inline-block;
    width: 100%;
    /* height: 100%; */
    border: 1px solid #d1d1d1;
    padding: 0 10px;
    cursor: pointer;
}

Чтобы привести к виду:
http://prntscr.com/gc30yb

Пришлось поставить поверху стиль:

.leyka-tpl-neo#leyka-payment-form .leyka-field.amount-selector .figure .rdc-radio__label {
     padding: 0;
}

**Comment by Ahaenor** [comment]
Олег, добрый день!

Ок, спасибо за дополнение. Указанная правка в CSS появится в ближайшей новой версии плагина.

**Comment by sidorenkoa** [comment]
Олег, а вы бы pull-request бы сделали. Было бы круче!
