### ISSUE TITLE
Сбрасывает на #leyka-submit-errors

### ISSUE THREAD

**Issue by lo7ev** [Teplitsa/Leyka#162]
Использую inputs из вашей формы. заменил статический _wpnonce на такой 
`<input id="_wpnonce" name="_wpnonce" type="hidden" value=wp_create_nonce()/>` ,
потому что он изменяется каждый раз при генерации формы. Но все равно продолжает сбрасывать на страницу компании. Остальные поля формы совпадают. Данные ввожу корректно.

**Comment by Ahaenor** [comment]
Код некорректен, т.к. wp_create_nonce() - это PHP-функция.
Правильно:
`<input id="_wpnonce" name="_wpnonce" type="hidden" value=<?php echo wp_create_nonce('leyka_payment_form');?>>`
