### ISSUE TITLE
Поддержка не отвечает

### ISSUE THREAD

**Issue by lo7ev** [Teplitsa/Leyka#163]
Здравствуйте, отправил вашей поддержке доступы к сайту, чтобы вы напрямую с Яндексом разобрались. Никак не могу получить ответ в каком состоянии находится процесс настройки.

**Comment by Ahaenor** [comment]
Добрый день!

Мы помним о вашем запросе - он находится в очереди.
Ожидаемое время реакции - конец этой недели.
