### ISSUE TITLE
Страница условий использования персональных данных

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#164]
Обнаружил, что в модальном окне, при пожертвовании, текст условий использования персональных данных открывается нормально, вместо специальных переменных подставляются данные из настроек Лейки, а вот на самой странице, если открыть ее обычным способом, стоят сами переменные, а не данные.

Условия использования ПД нужны не только для платежей, также все это надо и в различных формах на сайте, поэтому страницу вобще надо постить в подвал и в каждой форме делать на нее ссылку с чекбоксом. А тут небольшой облом )) [http://prntscr.com/girp0q](http://prntscr.com/girp0q)

**Comment by Ahaenor** [comment]
Олег, добрый день!

Ок, спасибо, мы исправим. Фикс войдёт в ближайшую новую версию "Лейки".

Спасибо за репорт!
