### ISSUE TITLE
Откорректировать платёжную форму

### ISSUE THREAD

**Issue by RAlzar** [Teplitsa/Leyka#165]
Здравствуйте!

Если можно, помогите, на странице с платёжной формой http://transformation.drealm.nu/campaign/создание-общины-свет-жизни/#leyka-payment-form :

1. Сделать, чтобы не отображались маркеры.

2. Сделать, чтобы по-умолчанию была валюта Евро, и пользователь мог переключать валюты.

3. В поле "Представьтесь пожалуйста" надпись "Ваше имя" поменять на "Ваше имя, и, желательно, фамилия".

4. Поменять слова "получении пожертвования", на слова "зачислении вложения".

![2017-09-14_213951](https://user-images.githubusercontent.com/25256435/30450887-d872c568-999a-11e7-881e-0351097f5ff7.png)

С уважением
Руслан Писанка

**Comment by Ahaenor** [comment]
Добрый день!

К сожалению, мы не занимаемся подобными модификациями)
Для этого вам понадобятся услуги PHP-программиста.
