### ISSUE TITLE
Тестовый режим платежных систем

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#166]
Предлагаю, что если в настройках стоит галочка "тестовый режим", то на поверхности сайта платежную форму настраиваемой платежной системы отражать только для администратора. Посетителям не показывать такую форму.

[http://prntscr.com/gnyp72](http://prntscr.com/gnyp72)

**Comment by Ahaenor** [comment]
Ок, спасибо. Добавили в бэклог.
