### ISSUE TITLE
Ошибка при создании корректировочного пожертвования

### ISSUE THREAD

**Issue by shum16** [Teplitsa/Leyka#168]
При попытке сохранить корректировочное пожертвование, получаем такую ошибку:
```
PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/new/public/content/plugins/leyka/inc/leyka-class-donation.php:1814
Stack trace:
#0 /var/www/new/public/content/plugins/leyka/inc/leyka-class-donation.php(1266): Leyka_Donation->__set('status', 'funded')
#1 /var/www/new/public/wp/wp-includes/class-wp-hook.php(300): Leyka_Donation_Management->save_donation_data(179513)
#2 /var/www/new/public/wp/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/new/public/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /var/www/new/public/wp/wp-includes/post.php(3510): do_action('save_post', 179513, Object(WP_Post), true)
#5 /var/www/new/public/wp/wp-includes/post.php(3583): wp_insert_post(Array, false)
#6 /var/www/new/public/wp/wp-admin/includes/post.php(378): wp_update_post(Array)
#7 /var/www/new/public/wp/wp-admin/post.php(193): edit_post()
#8 {main}
```

Версия Лейки: 2.3.3
Версия PHP: 7.1.9

**Comment by foralien** [comment]
Добрый день!

Ок, спасибо, мы проверим.




С уважением,
служба поддержки
«Теплица социальных технологий»
te-st.ru
https://www.facebook.com/TeplitsaST

2017-10-13 18:53 GMT+03:00 shum16 <notifications@github.com>:

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо, мы проверим.

**Comment by Ahaenor** [comment]
Добрый день!

Сейчас эта ошибка специфична для вашего случая.
Мы готовы исследовать ситуацию подробнее и устранить неполадку.
Но для этого нам понадобится:

- Доступ в админ. раздел сайта (аккаунт уровня "администратор" или "администратор пожертвований").
- Доступ к сайту по FTP (лучше по SSH).

Эти доступы пришлите, пожалуйста, на почту support@te-st.ru.

**Comment by shum16** [comment]
Добрый день! Спасибо за ответ.
Доступ - это сложно.. Вообще может достаточно рассмотреть случай, когда это первая запись в статус логе и заблаговременно инициализировать массив на этот случай? Я сейчас сделал и все получилось:
```
 if(!($status_log = get_post_meta($this->_id, '_status_log', true))) {
	$status_log = [];
}
```

**Comment by Ahaenor** [comment]
Это рабочий вариант. Но лучше всего было бы понять, почему именно в вашем кейсе параметр не инициализирован. На всех остальных инсталляциях это происходит.

Кроме того, ручной фикс в коде плагина всё равно будет перезаписан при первом обновлении - это должен быть официальный патч (через pull request, например).

**Comment by Ahaenor** [comment]
Меня ещё настораживает "[] operator not supported for strings" в тексте ошибки.
Т.е. изначально параметр не пустой, он имеет строковое значение.
Желательно понять, какое именно.

**Comment by shum16** [comment]
Видимо проблема в третьем аргументе функции get_post_meta.

**Comment by Ahaenor** [comment]
Я тоже про это подумал. Но просто так убрать этот аргумент нельзя - в этой функции есть пара особенностей, требующих внимания. В любом случае, мы проверим этот вариант.

**Comment by olegtkirov** [comment]
тоже есть ошибка при создании корректировочного

**Comment by Ahaenor** [comment]
Потенциальная ошибка исправлена, фикс войдёт в ближайший релиз.

Всем спасибо за сообщение!

**Comment by shum16** [comment]
Спасибо, Лев!
