### ISSUE TITLE
cloudpayments на андроиде

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#169]
Не срабатывает кнопка в форме пожертвования, когда запускается с телефона на андроиде в платежной системе cloudpayments.

На обычном десктопе все нормально, вводим имя и емейл, появляется форма ввода данных карты от платежной системы, в таблице пожертвований лейки фиксируется попытка пожертвовать. 

Открываем в телефоне, вводим имя, емейл, жмем на кнопку - кнопка становится оранжевой и никуда дальше ничего не движется. Данные пожертвования не фиксируются в таблице пожертвований, в логах платежной системы тоже не видно следов присутствия.

Пробовал с телефона стоящую тут же яндекс-кассу, там нормально все переходит на платежную систему.

Тема оформления на сайте используется "Нео".

Помогите понять что не так, чем можно на телефоне отдебажить, понять о чем там задумывается.

**Comment by Ahaenor** [comment]
Добрый день!

1. На наших тестах в ФФ и Хроме в шаблоне "Нео" платёжный виджет CloudPayments работает корректно.

2. Какой именно у вас андроид, и какой используется браузер?

3. Включён ли JS при отправке формы?

**Comment by olegtkirov** [comment]
Версия Андроида 6.0 браузер UC Browser, по поводу JS ложно сказать, ничего специально на телефоне не включал, не выключал, согласился с рекомендуемой конфигурацией. Тут даже непонятно где смотреть.

Проблема наверное не только с этой моделью и версией. Клиенты написали, что не отправляется платеж, я тоже сначала начал проверять на стационарном компе, на нем все нормально. Так и выяснилось, что чисто на телефонах не работает. Как только по скрину понял, что у написавшего клиента на телефоне не работает, попробовал у себя, и правда не работает. Вот не знаю, только ли на андроидах, и на всех ли, надо бы и на эпплах проверить.

**Comment by Ahaenor** [comment]
Наши проверки пока не выявили проблемы. Продолжаем искать.

**Comment by chekazoid** [comment]
Тоже проблема с этим. Дебаг дает следующее: 
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.n.parseJSON (jquery.js?ver=1.12.4:4)
    at Function.a.parseJSON (jquery-migrate.min.js?ver=1.4.1:2)
    at Object.<anonymous> (leyka.cp.js?ver=2.3.3:58)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
n.parseJSON @ jquery.js?ver=1.12.4:4
a.parseJSON @ jquery-migrate.min.js?ver=1.4.1:2
(anonymous) @ leyka.cp.js?ver=2.3.3:58
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
y @ jquery.js?ver=1.12.4:4
c @ jquery.js?ver=1.12.4:4
XMLHttpRequest.send (async)
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
(anonymous) @ leyka.cp.js?ver=2.3.3:47
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3
 
Скрипт ждёт от сервера JSON, а получает, судя по ошибке, HTML.

**Comment by Ahaenor** [comment]
@chekazoid , спасибо.

Можете прислать также тот HTML, который сайт фактически получает от сервера в этот момент?
Мы всё ещё не можем вызвать ошибку на наших тестовых стендах.

**Comment by olegtkirov** [comment]
Опыты на живом сайте показали, что для разных пользователей эффект или показывался или нет. Чуть позже, негативный эффект исчез у тех, у кого наблюдался.

Есть подозрение что особенности кеширования на хостинге.

Техподдержка хостинга ответила на запрос:

> Здравствуйте!
> 
> Возможно, дело в дополнительной защите, которую мы активировали 14.10.2017 для папки /wp-admin/.
> 
> Дело в том, что публичная часть сайта не должна бы обращаться к этой папке, в частности к файлу 
> /wp-admin/admin-ajax.php
> Но по факту при использовании некоторых плагинов WP такое случается.
> 
> Мы прописали исключение для сайта ххххххх.ru.
> Проверьте, ушла ли проблема?

Если дело именно в этом, то вряд ли это выявит тестирование в других условиях. Продолжаем смотреть, полностью или нет исчез негативный эффект.

**Comment by Ahaenor** [comment]
Спасибо за ответ! Да, эта причина имеет смысл.

Хотя хостингу следовало бы знать, что обращение из фронтенда к /wp-admin/admin-ajax.php - это не только нормальная, но и [рекомендуемая для разработчиков практика](https://codex.wordpress.org/AJAX_in_Plugins).

Им надлежит прописать исключения для обращений к файлу admin-ajax.php **для всех сайтов на WP**.
