### ISSUE TITLE
Записи пожертвований

### ISSUE THREAD

**Issue by logikv** [Teplitsa/Leyka#170]
Здравствуйте. 
У нас два сайта, и оба на wp. Нужно записи о пожертвованиях из одной базы, добавить к другой. 
Как понять, куда лейка записывает пожервования и как их проще было бы достать?
Спасибо.

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за вопрос.

Чтобы ответить подробно, нужно больше техн. деталей.
Но, в целом, ситуация такая:

1. Базу данных сайта вы можете узнать, открыв файл wp-config.php (обычно расположен в корне сайта). Название БД - это значение параметра "DB_NAME".

2. Кроме того, есть специальные плагины для WP, которые позволяют редактировать и экспортировать данные из базы прямо через админ. раздел сайта. Один из таких плагинов - ARI Adminer: https://wordpress.org/plugins/ari-adminer/

3. Что касается переноса данных о пожертвованиях с одного сайта на другой - это более узкий технический вопрос. Вам нужно экспортировать в целевую БД записи кампаний (post type "leyka_campaign") и пожертвований (post type "leyka_donation"), а также соотв. метаданные записей (post meta). Разумнее всего это сделать PHP-скриптом, но его должен написать программист.

Спасибо за обращение!

**Comment by logikv** [comment]
Так в какой таблице содержаться записи пожертвований?
В таблице _post ?

**Comment by Ahaenor** [comment]
Да. Кампании - там же.

И пожертвования, и кампании - это кастомные типы записей.

2017-11-12 14:58 GMT+03:00 logikv <notifications@github.com>:

**Comment by logikv** [comment]
Спасибо

**Comment by logikv** [comment]
А возможен ли такой вариант развития плагина, в котором данные о пожертваваниях предоставлялись для сторонних сервисов, создавая, своего рода, API?
