### ISSUE TITLE
Изменение цвета кнопок

### ISSUE THREAD

**Issue by Centrtruda** [Teplitsa/Leyka#171]
Добрый день,

пытаюсь изменить цвет кнопок в Шаблоне РЕВО плагине Лейка, но найти отвечающего за него файла .css не могу. Сменил цвет кнопок в плагине везде, а вот в шаблоне РЕВО не меняется.

Подскажите, пожалуйста, в каком файле плагина Лейка можно менять стили именно шаблона Рево.
Сайт centrtruda.com

Благодарю.

**Comment by klylex** [comment]
Добрый день.
CSS для Рево находится в скрипте /assets/css/public.css.
Но, если будете в будущем обновлять Лейку, то изменения затрутся при обновлении Лейки.
Правильный подход - добавить изменённые стили специальным плагином или через возможность вставки CSS в кастомайзере темы.
