### ISSUE TITLE
Адрес check-запросов Mixplat

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#172]
В справке написано про то, что рекомендуется задать адрес check-запросов
http://prntscr.com/hcf573

Ок, запросим, менеджер предоставит возможность заполнить пустое поле.

Сам адрес check-запросов для Mixplat как будет выглядеть? В Лейке предусмотрен этот адрес?

При тестировании мобильных платежей после оформления перекидывает сразу на страницу успешного платежа и ставит статус успешного, а в телефоне еще не успел подтверждение отправить и соответственно сам платеж еще не провелся.

В статистике много незавершенных платежей, где видимо люди не догадались что надо подтвердиться. Поэтому check-запрос надо делать. Подскажите как правильно пишется URL

**Comment by klylex** [comment]
Олег, добрый день.

URL для check-запросов выглядит так: https://your-site.org/leyka/service/mixplat/

**Comment by olegtkirov** [comment]
Т.е. и для уведомлений и для check-запросов используется один и тот же адрес, только по умолчанию в Миксплате check-запросы не проводятся?

**Comment by Ahaenor** [comment]
Да, всё так.
