### ISSUE TITLE
Ошибка при ответе на уведомление об успешном

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#176]
При зачислении регулярных платежей от Клоудпейментс успешные уведомления приходят, но по 100 раз с интервалом в 3 минуты.

Изучение показало, что Клоудпейментс в ответ на уведомление не получает отклика о зачислении, и посылает повторно каждые 3 минуты 100 попыток.

В нашем логе ошибок светится вот такая ошибка:
`[28-Nov-2017 21:06:05 UTC] PHP Warning:  A non-numeric value encountered in /home/............./WWW/wp-content/plugins/leyka/inc/leyka-class-donation.php on line 1506 `

Насколько понимаю, ругается на поле leyka_main_curr_amount, но там просто стоит сумма рублей, и вроде ошибаться негде.

Данная ошибка приводит к неприятному эффекту - уведомления от платежной системы записываются 100 раз, и если пришла 1000 рублей, то на сайте нарисовывается 100000. И пользователю посылается автоматом 100 писем об успешном пожертвовании. Ну письма пока отключил, но все равно что-то надо делать.

**Comment by Ahaenor** [comment]
Добрый день!

Такой ошибки мы не встречали. Скорее всего, проблема в поведении PHP на вашем хостинге.

Пришлите, пжлст, на почту техн. поддержки Теплицы (support@te-st.ru):

- копию вашего сообщения,
- логин и пароль в админ. раздел сайта,
- доступ к сайту по FTP (лучше по SSH).

Спасибо за обращение!
