### ISSUE TITLE
Невозможно пожертвовать более 30 000 р.

### ISSUE THREAD

**Issue by shum16** [Teplitsa/Leyka#177]
Добрый день!
Столкнулись с такой проблемой: невозможно пожертвовать более 30 000 р. в форме нового дизайна (возможно и в старом - не проверяли). При установке ползунка на значение больше 30 тыс и нажатии кнопки Поддержать разово выдается ошибка выхода за диапазон значений: 
[http://prntscr.com/hhibwe](http://prntscr.com/hhibwe)

**Comment by klylex** [comment]
Добрый день.
Пришлите доступы в админ-панель сайта (ссылка, логин и пароль) на эту почту support@te-st.ru

**Comment by shum16** [comment]
Здравствуйте! Вам сейчас должно было уйти письмо с доступом в админку. На support@te-st.ru

**Comment by klylex** [comment]
Логин получил, пароль задал. Вхожу в админку, страница перезагружается, но в админку попасть не могу. Может у вас есть какая-то прямая ссылка в админ-панель? И пришлите сразу ссылку на кампанию.

**Comment by Ahaenor** [comment]
Добрый день!

Изначальную проблему увидели и исправили.
Фикс войдёт в ближайшую официальную версию плагина (2.3.5).
Её выход планируется на ближайшие 1-2 рабочих дня.

Спасибо за обращение!

**Comment by shum16** [comment]
Лев, спасибо, будем ждать!
