### ISSUE TITLE
cloudpayments не работает

### ISSUE THREAD

**Issue by Centrtruda** [Teplitsa/Leyka#178]
После обновления перестала работать платежная система cloudpayments. При нажатии "Пожертвовать" платежная форма cloudpayments не вызывается.
Сайт: centrtruda.com

**Comment by klylex** [comment]
Добрый день.
Пришлите доступы в админ-панель сайта (ссылка, логин и пароль) на эту почту support@te-st.ru.

**Comment by Ahaenor** [comment]
Добрый день!

Проблему увидели и исправили - фикс войдёт в ближайшую официальную версию плагина (2.3.5).
Она должна выйти в ближайшие пару рабочих дней.

Спасибо за обращение!
