### ISSUE TITLE
Ошибка на странице

### ISSUE THREAD

**Issue by Life-V** [Teplitsa/Leyka#18]
Добрый день. 
ри создании новой компании и выводе ее на страницу выходит следующая ошибка. Могли бы глянуть в чем проблема ? 

class=»leyka_donation_currency» data-currency-label=»руб.» value=»rur» />

**Comment by foralien** [comment]
Добрый день!
А не могли бы вы дать ссылку на сайт (если это возможно), где это можно увидеть, спасибо :)

**Comment by Life-V** [comment]
Добрый день. 
Да вот для теста сделал компанию.
http://life-v.ru/campaign/multi-level-marketing-na-woocommerce

**Comment by Life-V** [comment]
Дак можете что подсказать ?

**Comment by Ahaenor** [comment]
Добрый день.

Судя по поведению страницы, проблема в том, что один из модулей сайта выполняет дополнительную обработку кода платёжной формы. Это и приводит к ошибочному отображению.

Чтобы это исправить, нужно предпринять следующее:
* Попробуйте сменить тему вашего WordPress. Если эта ошибка исчезнет, значит, она возникла из-за неправильного поведения темы. В этом случае вам нужно найти и исправить это поведение в коде темы, либо поменять тему сайта на другую (более дружественную).
* Попробуйте отключать ваши плагины по одному и проверять, как выглядит страница формы. Найдя, из-за какого плагина возникает проблема, вы сможете заменить его на аналогичный или вообще отключить.
* Попробуйте создать отдельную страницу (page) и вставить в её текст шорткод кампании:
[leyka_payment_form id=id_вашей_кампании]
Если это приведёт к отображению без ошибки, используйте для платежей эту страницу. В этом случае работа с темой и плагинами сайта не нужна.

**Comment by Ahaenor** [comment]
Замечу в скобках, что, судя по вашему сайту, он служит для продаж. Лейка не подходит для обслуживания таких задач, т.к. является плагином именно для сбора пожертвований.

**Comment by Life-V** [comment]
Да вы оказались правы на другой теме все хорошо отображается. Отключение плагинов не помогло. На отдельной странице тоже не помогло. 

Есть ли возможность не меняя тему исправить данную проблему? 

То что сайт для продаж. Это не страшно. Мне важен принцип работы плагина. У меня не для пожертвований он.

**Comment by Life-V** [comment]
Может поможете за отдельную плату ?

**Comment by Ahaenor** [comment]
Выше я описал способ решить проблему, не отказываясь от текущей темы. Для
этого действительно понадобится php-программист, но задача сама по себе
простая.

К сожалению, прибегнуть к нашим ресурсам для её решения невозможно. Наша
целевая аудитория - некоммерческие и социальные проекты.

2015-05-19 17:00 GMT+03:00 Life-V <notifications@github.com>:

**Comment by Life-V** [comment]
Добрый день, а есть возможность подключить комментарии к компаниям. По умолчанию они отключены.

**Comment by Ahaenor** [comment]
Добрый день.

Это возможно. Для добавления комментариев необходимо добавить в код вашей темы (или специально написанного плагина) вызов (следующей функции)[https://codex.wordpress.org/Function_Reference/add_post_type_support]. По ссылке есть пример её применения.

**Comment by Life-V** [comment]
У меня в теме есть вывод комментариев. Мне надо сделать только на вашей странице. На скооько я понимаю я должен где-то у вас вставить код выдачи комментариев. Вопрос только где

**Comment by Ahaenor** [comment]
Не совсем так. Код нужен для того, чтобы настроить тип записей "кампания" на поддержку комментариев (по умолчанию, они не поддерживают их).

Если этот код будет добавлен, комментарии на страницах кампаний должны появиться автоматически - никакого специального кода для вывода блока комментариев вставлять не нужно.
