### ISSUE TITLE
Цвет кнопок в форме платежа

### ISSUE THREAD

**Issue by tguk05** [Teplitsa/Leyka#180]
Здравствуйте. Пост от 15-ноя по цвету кнопок  помог настроить через файл /assets/css/public.css цвета кнопки и градусника в соответствии с темой карточку на странице сайта. Но при переходе на форму оплаты цвета вновь изменяются на стандартные (расцветки зеленого). Исходный код php показал, что существуют предопределенные константы, определяющие цвет в форме оплаты (рево) при создании временных файлов *.scss. Хорошо бы сделать стандартный .xml файл, где каждый сможет поменять цвета под свою тему. Или, уточните, пожалуйста, где докопаться в коде к заданию этих констант. За Лейку - респект, дело полезное. Спасибо.

**Comment by Ahaenor** [comment]
Добрый день!

Мы, безусловно, планируем сделать цвета формы настраиваемыми. Даже не через отдельный файл, а через параметры в админ. разделе Лейки. Ориентировочно, это появится в плагине в первых релизах после НГ.

В качестве временного решения, как перекрасить элементы формы, мы можем рекомендовать только изменение CSS-стилей, которые используются шаблоном "Рево".
Добавить такие изменения стилей можно в Настройках темы (при необходимости, добавляя "!important").

Главное, не меняйте CSS самой Лейки или Кандинского. Инче они будут перезаписаны на стандартные значения при обновлении до новых версий.

Спасибо за обращение!
