### ISSUE TITLE
Добавить возможность приема платежей в криптовалюте, как минимум в Bitcoin и Ethereum

### ISSUE THREAD

**Issue by pavelsr** [Teplitsa/Leyka#182]
Было бы здорово если б была возможность собирать донейты и в крипте.

**Comment by klylex** [comment]
Добрый день.
Такая возможность рассматривается. Но пока есть ряд вопросов, в частности юридического характера.

**Comment by pavelsr** [comment]
А в чём, если не секрет, проблема?
На физлицо через яндекс.деньги лейка то может отправлять. Также можно сделать и переводы в крипте - от физлица физлицу.

**Comment by klylex** [comment]
Вот вы сами практически и ответили на свой вопрос. Лейка переводы не делает. Это агрегатор платёжный систем. А Российские платёжные системы, например Яндекс, не работают с криптовалютами. Плюс, для НКО есть ещё ряд проблем. Например, анонимность платежей и другие юридические тонкости. Также наши разработчики пока сильно загружены, поэтому этот вариант только рассматривается.
