### ISSUE TITLE
Невозможно прописать кастомный IPN для сбора через PayPal

### ISSUE THREAD

**Issue by shum16** [Teplitsa/Leyka#184]
Здравствуйте!
Используем Лейку для сбора пожертвований через paypal, кроме того используем для этого параллельно еще и свое решение. Есть необходимость вести учет пожертвований централизовано, для этого мы хотим изменить адрес ipn на свой и обрабатывать колбэк сами, но тут сталкиваемся с проблемой - адрес ipn прописан жестко внутри класса Leyka_Paypal_Gateway, а изменения внесенные в него проживут лишь до следующего обновления плагина. 
Как нам лучше поступить?

**Comment by Ahaenor** [comment]
Добрый день!

Технически, добавить это возможно.
Но с т. зр. плагина, это нежелательная ситуация, т.к. ответственность за учёт поступивших платежей выносится с сайта (с Лейкой) в другое место.

Какая у вас организация? Сайт уже есть?

**Comment by shum16** [comment]
Добрый день, Лев!
Мы БФ Измени одну жизнь: [changeonelife.ru](https://changeonelife.ru)
У нас централизованный учет всех пожертвований, поэтому нужно чтобы все уведомления от платежных систем (а у нас их 4!) приходили в одно место.
С CloudPayments так получилось сделать, то есть и наши собственные пожертвования и пожертвования от кампаний приходят на один url. А вот с PayPal сделать так не вышло..

Не понял насчет ответственности?

**Comment by Ahaenor** [comment]
Спасибо, суть запроса понятна.

Насчёт ответственности - смысл в следующем.
Лейка отвечает за учёт пожертвований, которые поступили через неё.
Это отображается не только в бэкенде (админ. разделе сайта), но и во фронтенде (списки поступивших пожертвований, прогресс-бары целевых сумм).

Все инициированные платежи (статус "попытка пожертвовать") Лейка учитывает в любом случае. Но если коллбэк от одного из платёжных операторов будет приходить не в Лейку, а на другую (внешнюю систему), это не позволит плагину корректно учитывать и отображать реально поступившие платежи. По нашему мнению, это повредит прозрачности работы деньгосбора с т. зр. пользователей-доноров.

Другими словами, с т. зр. Лейки, лучшая схема работы - когда данные о поступивших платежах поступают и в неё, и во внешнюю систему.
(Примечание: для большинства случаев Лейка - и есть такая единая система. Плагин разрабатывается именно с такой целью.)

В качестве альтернативного варианта для решения вашей проблемы, мы можем предложить следующий подход.
Создаётся специальный скрипт, который 1 раз в сутки (или при каждом поступившем платеже через Лейку) отправляет данные о таком платеже во внешнюю систему.
Это можно реализовать и без правок в коде плагина - только на добавлении обработчиков для action-ов.

* Если такой вариант для вас приемлем, мы готовы проконсультировать по деталям.
* Вариант, запрошенный вами, мы готовы реализовать, но не ранее следующей версии Лейки. Это будет как минимум через месяц.

**Comment by shum16** [comment]
Лев, да, понятно, что при использовании своего IPN на разработчика ложится ответственность, по обработке пожертвований Лейки. Но в принципе я ничего в этом страшного не вижу, главное, чтобы сам разработчик осознавал, на что он идет. Мы сами разобрались, как нужно обрабатывать пожертвования Лейки, чтобы все правильно отображалось на фронтенде и в админке.
Если это будет документировано, так вообще прекрасно )

В общем, тогда мы будем ждать выхода новой версии Лейки, а пока харкодно пропишем свой IPN с вашего позволения.
Спасибо за помощь!

**Comment by Ahaenor** [comment]
Ок, договорились. Не забудьте добавить фильтр, когда выйдет новая версия плагина.
