### ISSUE TITLE
Подключение на Яндекс.Кассу CMS модуль «Wordpress (Лейка)»

### ISSUE THREAD

**Issue by oss62** [Teplitsa/Leyka#185]
Добрый день!

При попытке сделать тестовое пожертвование вот что получается.
Например, Банковская карта - дохожу до уровня , когда я ввожу данные карты, мне приходит пароль на телефон для подтверждения перевода, я ввожу пароль, деньги списываются (приходит смс), но через пару секунд смс, что отмена покупки и возврат на сайт на страницу с извинениями.
То же самое с другими способами.

Звонили в техподдержку Яндекс.Кассы, разбирались. У них идет ошибка 404. 
т.е. в параметрах настойки магазина Яндекс.Кассы стоит путь:
checkUrl https://sluzhenie.tomsk.ru/leyka/service/yandex/check_order/
avisoUrl https://sluzhenie.tomsk.ru/leyka/service/yandex/payment_aviso/

Но эти папки пустые. Они говорят, что при установке плагина (модуля) Лейки на сайт в эти папки автоматически должны вставляться скрипты. А их нет. Папки пустые. Поэтому и не проходят платежи.
Выслали нам лог с параметрами и результатом запроса на адрес https://sluzhenie.tomsk.ru/leyka/service/yandex/check_order/
Это лог при попытке совершить тестовый платеж на 15 рублей.

Высылаем вам. Просим поддержки.
[44335.txt](https://github.com/Teplitsa/Leyka/files/1698288/44335.txt)

С уважением, Дом сестринского ухода, г.Томск

**Comment by oss62** [comment]
По-моему мы разобрались в этой проблеме. Мы искусственно создали в хостинге эти папки, хотя в инструкции по установке этого не было написано. И все встало из-за этого. Когда убрали - тестовые платежи прошли...
Снимаю свою просьбу. Просим извинения. Но кто ж его знал!

**Comment by Ahaenor** [comment]
Добрый день!

Это немного искусственное решение) Но мы рады, что оно помогло.

**Альтернативный вариант решения** - включить для сайта режим постоянных ссылок (админ. раздел - Настройки - Постоянные ссылки - любой вариант, кроме по умолчанию).

Спасибо за обращение!
