### ISSUE TITLE
Рекуррентные платежи

### ISSUE THREAD

**Issue by Clowncare** [Teplitsa/Leyka#186]
Здравствуйте!

При платежах через Яндекс-Кассу первый платёж проходит, а для остальных возвращается ошибка error 28: connect() timed out! При этом Яндекс не видит попытки сделать пожертвование.
Яндекс сказал, что проблема в сертификате или неправильном ip. Сертификат у нас новый, а ip постоянный, его присылали Яндексу. Они просят логи, и сказали обратиться к вам.

Буду благодарен за помощь в решении проблемы!

**Comment by klylex** [comment]
Добрый день.
Ответил по почте.
