### ISSUE TITLE
Рекуррентные платжи Яндекс касса

### ISSUE THREAD

**Issue by karandashik** [Teplitsa/Leyka#188]
Здравствуйте, при тестировании рекуррентов через яндекс кассу возвращается ошибка error 58: unable to load client key -8178.
Сертификат и приватный ключ установлен, в яндексе рекурренты подключены и активированы, тестирование выполняется на только что выполненном повторяющемся платеже (прошел успешно).
Спасибо!

**Comment by klylex** [comment]
Добрый день.
Пришлите на нашу почту - support@te-st.ru:
1. Это описание проблемы.
2. Доступы в админ-панель вашего сайта (ссылка, логин и пароль). 
3. Доступы по FTP или SSH (хост, логин и пароль).
