### ISSUE TITLE
Leyka + WPML

### ISSUE THREAD

**Issue by joylord** [Teplitsa/Leyka#189]
Добрый день!

Есть ли решение проблемы связки с плагином мультиязычности WPML.
WPML создает новый id поста для переводов, что в свою очередь не видит Лейка.

**Comment by klylex** [comment]
Добрый день.
Ответим вам по почте.

**Comment by joylord** [comment]
Добрый день!
Так и не получил от вас письмо.

**Comment by klylex** [comment]
Добрый день.
Это же ваша почта - yuriy-osadchiy@ukr.net?

**Comment by klylex** [comment]
Добрый день.
Ответили на почту .
