### ISSUE TITLE
Проблема с разметкой айфрейма кампании

### ISSUE THREAD

**Issue by GenV** [Teplitsa/Leyka#19]
Добрый день! 
Прежде всего хочу сказать вам спасибо за ваш труд. А теперь к делу.
Мы хотели расшарить по дружественным сайтам код вставки айфрейма. Но обнаружили, что он криво отображается: заголовок "налазит" на описание.  Вот посмотрите на тестовой странице http://pravobraz.ru/testovaysbor/
Что можно сделать?

**Comment by Ahaenor** [comment]
Добрый день!

Ок, проблема понятна. Мы займёмся этим.
Ожидайте ответа в течение этой или начале будущей недели.

Л.

27 мая 2015 г., 12:41 пользователь GenV <notifications@github.com> написал:

**Comment by olegtkirov** [comment]
По поводу ифреймов это отдельная тема для обсуждения. Я встраивал кампанию на сайты с другим доменными именем и все получалось неоднородно. Дело в том, что на отображение ифреймов влияют параметры X-Frame-Options. Вот пока у меня было настроено на беспрепятственную отдачу во фреймы содержимого, было все нормально. Потом пришлось внести в файл .htaccess изменения, связанные с переадресацией доменов, и параметры X-Frame-Options слетели - фрейм показывается, но с полным содержимым исходного сайта с полосами прокрутки. Или вобще выдает ошибку. Браузер в инспекторе вечно ругается на внедренный во фрейм контент, считая такую технологию потенциально опасной.

Вобщем ифреймы штука капризная, и сомнительная по масштабированию на адаптивных шаблонах. 

Может есть возможность придумать другой механизм показа карточки кампании на сторонних сайтах? Может JS какой-нибудь, или еще что-нибудь, что будет выдавать содержимое не в капризном фрейме? Да хоть сгенерированный кусок статичного HTML, на худой конец, который бы вставлять на другой сайт. :)

**Comment by Ahaenor** [comment]
Да, это одно из текущих направлений нашей работы. В одной из ближайших версий встраивание получит новые возможности - в том числе для большей совместимости с темами.
