### ISSUE TITLE
Не работает PayPal

### ISSUE THREAD

**Issue by AlexAgapov1983** [Teplitsa/Leyka#190]
Здравствуйте. Возникла проблема плагин перестал работать с paypal в crome и opera в firefox все нормально. В консоль при этом выводится предупреждение "The SSL certificate used to load resources from https://www.paypal.com will be distrusted in Opera 57. Once distrusted, users will be prevented" как я понял дело в доверии к ssl сертификату paypal.

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за обращение.

На каких шаблонах формы пожертвования видна эта ошибка?

**Comment by AlexAgapov1983** [comment]
Вот например https://changeonelife.ru/campaign/valentina-zajtseva-est-tol-ko-mig-mezhdu-proshly-m-budushhim/ после заполнения имени и e-mail

**Comment by Ahaenor** [comment]
Ок, спасибо ещё раз. Берём в работу.

**Comment by shum16** [comment]
Добрый день!
Удалось исправить ошибку?

**Comment by klylex** [comment]
Добрый день!
К сожалению, ещё нет. Пока мы сильно загружены другими задачами.

**Comment by Ahaenor** [comment]
Добрый день!

Мы изучили эту проблему. Действительно, она на стороне самого PayPal - они должны обновить свой SSL.

Официальный ответ от их службы поддержки:
> We are aware of this issue and we are taking the necessary steps to resolve the problem.

Другими словами, мы можем только ждать их. Когда они обновят сертификат, проблема уйдёт сама собой.

Спасибо за обращение!

**Comment by shum16** [comment]
Хорошо, спасибо!
