### ISSUE TITLE
Поле: Варианты размеров пожертвований слишком ограничено

### ISSUE THREAD

**Issue by newsiberian** [Teplitsa/Leyka#192]
Добрый день.

Поле в админке "Варианты размеров пожертвований фиксированного поля суммы" разрешает слишком мало символов. Мы хотели бы больше вариантов предоставить людям, а вмещается только 6 опций (100,300,500,1000,300...)

Расширьте, пожалуйста, этот функционал.

**Comment by klylex** [comment]
Добрый день.
Для такого случая есть поле, где пользователь может ввести самостоятельно сумму, которую хочет пожертвовать.
А большее количество готовых вариантов только усложнит интерфейс Лейки.
