### ISSUE TITLE
Картинка способа оплаты наезжает на кнопку сабмита (моб.версия)

### ISSUE THREAD

**Issue by newsiberian** [Teplitsa/Leyka#194]
Добрый день.
Вот такой баг на телефоне:
тема: Customizr
![photo_2018-03-25_15-54-57](https://user-images.githubusercontent.com/11130487/37873341-3297eab4-3045-11e8-9098-101e4be24359.jpg)

**Comment by klylex** [comment]
Добрый день.
Какая у вас мобильная операционная система и версия?
Через какой браузер или приложение заходите на сайт?
И скиньте, пожалуйста, ссылку на эту кампанию.

**Comment by newsiberian** [comment]
Добрый день.
Пробовал в Chrome крайняя версия. ОС Андроид. Компания пока в тесовом режиме [тут](https://mercuriya.ru/campaign/podderzhat-rabotu-fonda/)

**Comment by klylex** [comment]
Добрый день.
Проблему увидели.
На данный момент наш разработчик сильно загружен, поэтому исправим проблему в одном из будущих релизов.
