### ISSUE TITLE
[Запрос]: leyka-template-sample

### ISSUE THREAD

**Issue by newsiberian** [Teplitsa/Leyka#195]
Добрый день,

Не являюсь специалистом по WP. Пытался сделать кастомный темплейт для Лейки и не осилил.

Было бы очень замечательно, если бы вы подготовили плагин с образцом темплейта, который легко было переиспользовать.

Вот проблемы с которыми я столкнулся:

В вашем подходе с полем для указания произвольной суммы меня не устраивает UX, потому что при использовании смешанного подхода, её значение заполняется после выбора какой-либо фиксированной суммы. Это **очень не очевидно** для пользователя, что там вообще поле для ввода и что-то можно менять. Вот пример на который я равняюсь: https://nuzhnapomosh.ru/donate/
Чтобы это реализовать, как оказалось, нужно менять бакэнд вашего плагина, а это не вариант. Если бы форма сабмитилась через fetch было бы гибче.

Затем, пришлось переиспользовать ваш public.js, но как оказалось, он использует глобальный объект `leyka` с переводами, который, я так и не нашёл где инициализируется, а без этого валидация не проходит.

Ещё в теме `customizr` не работает ваш плагин модального окна, это одна из причин, зачем свой public.js  понадобился.

**Comment by Ahaenor** [comment]
Добрый день.

Ок, вопросы понятны. Постараюсь ответить по порядку.

1. В кастомных шаблонах вполне можно использовать собственный JS-файл (или несколько). public.js изначально ориентирован только на встроенные шаблоны форм.

2. Изменить работу поля суммы - абсолютно легитимный повод создать собственный кастомный шаблон (с собственным js). Бэкенд плагина при этом менять не нужно - главное, чтобы форма отправляла на admin-ajax.php нужный набор аргументов.

3. Использование глобального объекта для локализации фронтенда - в WP нормальная практика. С помощью этого же объекта в js передаются значения некоторых параметров (например, ajaxurl). Изменить набор и значения полей объекта leyka можно через фильтр в бэкенде:

`add_filter('leyka_js_localized_strings', function($lines){
    // $lines['your_var'] = 'your_value';

    return $lines;
});`

P. S. В одной из ближ. версий планируется добавить шаблон формы на основе того, который вы привели в пример. Там же будет переработан API шаблоно форм - мы в курсе, что он порядочно устарел :)

Спасибо за обращение.
