### ISSUE TITLE
Не работает шаблон "Рево"

### ISSUE THREAD

**Issue by KaRMa4** [Teplitsa/Leyka#197]
При выборе шаблона "Рево" он весь растекается по странице, если его вставлять через шорткод.
Но если им пользоваться на странице, которая создается, при создании самой кампании, то все нормально. В чем проблема?
[Скриншот](https://i.imgur.com/ZNoWKhS.png)

**Comment by klylex** [comment]
Добрый день.
Пришлите, пожалуйста, ссылку на страницу с шорткодом и ссылку на саму кампанию.

**Comment by KaRMa4** [comment]
Снова здравствуйте, уже не нужно. Все решилось.
Проблема была в Базе данных, почистил и все стало окей.

**Comment by klylex** [comment]
Хорошо.
Вопрос закрываю.
