### ISSUE TITLE
Проблема с выбором шаблона сайдбара

### ISSUE THREAD

**Issue by GenV** [Teplitsa/Leyka#20]
По умолчанию в любой создаваемой записи на нашем сайте (Pravobraz.ru) есть возможность выбора шаблона сайдбара (причем, можно указать размещение его слева или справа, или вообще сделать пост без сайдбара). Если сайдбар есть в записи, то можно выбрать его шаблон.
Каждая из кампаний по сбору средств использует исключительно сайдбар по умолчанию. Его невозможно выбрать, отсутствуют настройки шаблона сайдбара, но и не только (например нельзя выбрать опции заголовка, которые предусмотрены в шаблоне темы). 
Что здесь можно сделать, чтобы в кампании не были отключены другие опции основного шаблона записей?
Для нас это важно, поскольку мы хотели разместить в сайдбарах записей (новостей) карточку кампаний, а она по дефолту также отражается и на странице кампании, что выглядит странно. 
Вот как изнутри админки выглядит проблема (стрелочками указаны настройки сайдбаров) и отсутствие настроек в кампании.
https://yadi.sk/i/26zjksC8h39EA
https://yadi.sk/i/uRh5qkMlh39FF

**Comment by Ahaenor** [comment]
Добрый день.

По умолчанию, кампании - максимально простой по своему отображению тип записей (post type). Страница отображения кампании выглядит как страница записи (post), установленная в настройках темы.

Чтобы присвоить кампании шаблон, отличный от шаблона одиночной записи (post), вы можете поступить следующим образом:
* либо добавить в вашу тему код, выбирающий и подключающий какой-то специфический шаблон при отображении записи типа leyka_campaign (кампания);
* либо для каждой вашей опубликованной кампании создать обычную страницу (page), настроить для неё шаблон и в контент страницы вставить шорткод для формы пожертвований: `[leyka_payment_form id=id_кампании]`

**Comment by olegtkirov** [comment]
Поставьте себе плагин https://wordpress.org/plugins/restrict-widgets/ и настройте отображение виджета с карточкой кампании у выбранных типов записей, различных разделах, для зарегистрированных или незарегистрированных пользователей.

**Comment by Ahaenor** [comment]
В этом даже не будет необходимости: ошибка уже устранена. Проблемы в
будущих версиях быть не должно.

1 июля 2015 г., 17:41 пользователь olegtkirov <notifications@github.com>
написал:

**Comment by GenV** [comment]
Устраниена? у меня пока все остается как и прежде. Шаблон записи, который определяется темой, не работает. Выбора шаблона сайдбара как не было, так и нет.
Или речь идет о будущих версиях?

**Comment by Ahaenor** [comment]
Речь о будущих версиях, начиная со следующей (2.2.7).
