### ISSUE TITLE
Сортировка платежей в кампании неверно сортирует

### ISSUE THREAD

**Issue by newsiberian** [Teplitsa/Leyka#201]
Добрый день.
Обратил внимание на сортировку платежей по дате на убывание:
Что-то с ней не так :smile: 
![leyka](https://user-images.githubusercontent.com/11130487/38299130-63ffa908-3823-11e8-821e-89e2f252b9e9.png)

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо. Добавим в бэклог.
Это список пожертвований в шаблоне "Рево", так?

**Comment by Ahaenor** [comment]
Добавили в бэклог. Спасибо за обращение!
