### ISSUE TITLE
404 на сервисные запросы с Cloud Payments на кириллический домен

### ISSUE THREAD

**Issue by st-sloth** [Teplitsa/Leyka#206]
Здравствуйте. В случае, когда адрес сайта на кириллице (http://пример.рф/), на некоторые сервисные запросы с Cloud Payments возвращается 404:
* `http://пример.рф/leyka/service/cp/fail/`
* `http://пример.рф/leyka/service/cp/complete/` для не первых рекуррентных платежей

При этом, 
* `http://пример.рф/leyka/service/cp/check/`
* `http://пример.рф/leyka/service/cp/complete/` для не рекуррентных и первых рекуррентных платежей

обрабатываются корректно.

При изменении адреса на ASCII Punycode (http://xn--e1afmkfd.xn--p1ai/)
* `http://xn--e1afmkfd.xn--p1ai/leyka/service/cp/fail/`
* `http://xn--e1afmkfd.xn--p1ai/leyka/service/cp/complete/` для не первых рекуррентных платежей

также обрабатываются корректно.

**Comment by Ahaenor** [comment]
Добрый день.

Строго говоря, мы не рекомендуем нашим бенефициарам кириллические домены, поэтому не очень тщательно тестили их.

Быстрое решение - punycode, как вы уже нашли.

Для более комплексного нам понадобятся доступы к сайту, на котором видна проблема (админ. раздел WP + FTP/SSH).
Эти доступы можно прислать на support@te-st.ru

Спасибо за обращение!
