### ISSUE TITLE
Не работает Яндекс Деньги для физ. лиц.

### ISSUE THREAD

**Issue by AlexSmith89** [Teplitsa/Leyka#208]
Здравствуйте, установил ваш шаблон, совместно с вашим плагином Лейка.
Столкнулся с проблемой что платежи не корректно работают.
Были корректно указаны данные, необходимые для работы яндекс деньги (физ. лица)
Но при попытке провести тестовый платеж скидывает на страницу Яндекса с надписью не указана сумма. https://clip2net.com/s/3UqohZV

Шаблон использовался Рево.

При попытке сменить шаблон на другой платежная система начинает работать, но внешний вид других шаблонов не соответствует тому какой он должен быть, шаблон НЕО - https://clip2net.com/s/3UqM7vG

Пробовал также на другом хостинге, аналогичная ситуация.

Прошу подсказать в чем проблема. 

Спасибо.

**Comment by klylex** [comment]
Добрый день.
Как я понял, вы писали в нашу поддержку от имени "Петр Сидоков"?
Вчера вам был дан ответ на эту почту - georgemartinss@outlook.com
