### ISSUE TITLE
На сайте не сразу отображается пожертвование

### ISSUE THREAD

**Issue by wenerever** [Teplitsa/Leyka#209]
Добрый день!
Столкнулись с проблемой, что Лейка очень тормозит сайт, но основная беда - дарители в течение часа просто не видят своих пожертвований в кампании, хотя письмо с уведомлением приходит сразу.
От количества пожертвований эта пауза не зависит. Возникают проблемы с дарителями - все хотят видеть своей пожертвование сразу.

**Comment by klylex** [comment]
Добрый день.
Пришлите, пожалуйста, ссылку на ваш сайт и кампанию на эту почту - support@te-st.ru.
