### ISSUE TITLE
Как прикрутить все возможности Яндекс Кассы?

### ISSUE THREAD

**Issue by GenV** [Teplitsa/Leyka#21]
Яндекс Касса позволяет принимать платежи также  
По коду через терминал
Сбербанк: оплата по SMS или Сбербанк Онлайн
Через Альфа-Клик
Через Промсвязьбанк
Через MasterPass
Сейчас в Лейке эти возможности Яндекс Кассы отсутствуют. Как их прикрутить или может быть вы дополнили бы этими возможностями Лейку в части Яндекс Кассы?

**Comment by Ahaenor** [comment]
Добрый день.

Все перечисленные способы платежей будут постепенно включаться в последующие релизы Лейки.
Самыми востребованными являются СМС-платежи.
