### ISSUE TITLE
На следующие сутки перестают работать рекурентные платежи и проблема с leyka-ajax.php

### ISSUE THREAD

**Issue by pyotr** [Teplitsa/Leyka#210]
Добрый день

Подписка на рекурентные платежи ( Yandex Kassa ) происходит, при ручном вызове после этого тоже, но если подождать до следующего дня, то ничего... как будто подписка пропадает... залезал в базу - по моему у пожертвования стоит флаг - отменено.. не помню точно ..

По поводу leyka-ajax.php - у меня работала ваша DEV версия предыдущая, а вот мастер последний нет.. При загрузке страницы оплаты Yandex Kassы ей в форме ничего не передавалось... То что проблема в leyka-ajax.php нашел методом тыка.. Сравнил в Diff - вообщем этот старый код работает у меня на сайте:

`$donation_id = leyka()->log_submission();

    leyka_remember_donation_data(array('donation_id' => $donation_id));

	if(empty($_POST['without_form_submission'])) {
		do_action('leyka_payment_form_submission-'.$pm[0], $pm[0], implode('-', array_slice($pm, 1)), $donation_id, $_POST);
	}

    $payment_vars = array(
        'status' => $donation_id && !is_wp_error($donation_id) ? 0 : 1,
        'payment_url' => apply_filters('leyka_submission_redirect_url-'.$pm[0], '', $pm[1]),
    );
    if($payment_vars['status'] == 0) {
        $payment_vars['donation_id'] = $donation_id;
    } else {
        $payment_vars['errors'] = $donation_id;
    }

    $payment_vars = array_merge(
        apply_filters('leyka_submission_form_data-'.$pm[0], $_POST, $pm[1], $donation_id),
        $payment_vars
    );

    die(json_encode($payment_vars));`

 а ваш последний нет ( к сожалению не умею дебагить json запросы ):

`if(empty($_POST['without_form_submission'])) { // Normal donation submit procedure

        $donation_id = leyka()->log_submission();

        leyka_remember_donation_data(array('donation_id' => $donation_id));

        do_action('leyka_payment_form_submission-'.$pm[0], $pm[0], implode('-', array_slice($pm, 1)), $donation_id, $_POST);

        $payment_vars = array(
            'status' => $donation_id && !is_wp_error($donation_id) ? 0 : 1,
            'payment_url' => apply_filters('leyka_submission_redirect_url-'.$pm[0], '', $pm[1]),
        );
        if($payment_vars['status'] == 0) {
            $payment_vars['donation_id'] = $donation_id;
        } else {
            $payment_vars['errors'] = $donation_id;
        }

        $payment_vars = array_merge(
            apply_filters('leyka_submission_form_data-'.$pm[0], $_POST, $pm[1], false),
            $payment_vars
        );

    } else { // Get payment vars without donation submit
        $payment_vars = array_merge(
            apply_filters('leyka_submission_form_data-'.$pm[0], $_POST, $pm[1], false),
            array('status' => 0, 'payment_url' => apply_filters('leyka_submission_redirect_url-'.$pm[0], '', $pm[1]),)
        );
    }

    die(json_encode($payment_vars));
`

**Comment by Ahaenor** [comment]
Ок, спасибо. Мы проверим.

**Comment by Ahaenor** [comment]
Пётр, добрый день.

По этому вопросу подробно ответил вам по почте.

Вкратце - да, это действительно баг.
Мы исправим его в ближ. новой версии (2.3.6.1).

Спасибо за обращение!
