### ISSUE TITLE
Не работает банковская квитанция на сайте

### ISSUE THREAD

**Issue by pyotr** [Teplitsa/Leyka#211]
Еще запрос забыл... 

При выборе банковской квитанции выпадает системное окно ( Уверены продолжить с небезопасной формой ) и на этом все заканчивается.. ничего не предлагает ни скачать, ни на почту ничего не приходит...

**Comment by Ahaenor** [comment]
Пётр, добрый день!

По этому вопросу мы подробно ответили вам по почте.

Вкратце: у вас очень специфический кейс. Проблема в работе PHP-функции json_encode(), которая по каким-то причинам превращает адрес HTTPS в HTTP. Возможная причина проблемы - работа плагина по редиректам на HTTPS.

Спасибо за обращение!

**Comment by pyotr** [comment]
Может кому будет полезно - сменил плагин Easy HTTPS (SSL) Redirection на плагин Really Simple SSL - проблема ушла.. @Ahaenor Скажите, а квитанция должна пользователю на почту приходить?

**Comment by Ahaenor** [comment]
> Может кому будет полезно - сменил плагин Easy HTTPS (SSL) Redirection на плагин Really Simple SSL - проблема ушла.. 

 - Ок, спасибо - мы внесём это в документацию по Лейке.

> @Ahaenor Скажите, а квитанция должна пользователю на почту приходить?

 - Нет, квитанция выводится для распечатывания только в браузере. На почту донору уходит только стандартное спасибо-письмо, но только после того, как организация получит перевод и переведёт пожертвование в статус "оплачено".

Но насчёт почты спасибо за идею - мы добавим эту функцию в бэклог.
