### ISSUE TITLE
Не корректная работа шаблона Рево с Яндекс Деньгами для физ. лиц. 

### ISSUE THREAD

**Issue by atikee** [Teplitsa/Leyka#214]
Добрый день, при попытке провести платеж через Яндекс Деньги для физических лиц, на стороне Яндекса возникает ошибка "Не указана сумма". Данная проблема возникает только при использовании шаблона "Рево". Подскажите пожалуйста решение проблемы.

**Comment by klylex** [comment]
Добрый день.
А это вы задавали аналогичный вопрос через наш форму?
https://leyka.te-st.ru/support/

Если так, то ваш вопрос был получен. И сегодня утром вам ответили на эту почту - appleriga@gmail.com.

**Comment by atikee** [comment]
Спасибо за быстрый ответ, но к сожалению я не получил письма на почту.

**Comment by klylex** [comment]
Странно. Проверяли папку "Спам"?

**Comment by atikee** [comment]
Не проверил, спасибо.
