### ISSUE TITLE
Не могу переключить плагин на русский

### ISSUE THREAD

**Issue by LazyFM** [Teplitsa/Leyka#215]
Приветствую!

Лейка почему-то поставилась на английском, хотя Wordpress (4.5.15) русский, и файлы leyka_ru_RU в wp-content/languages/plugins есть. Что и где копать?

Заранее спасибо!

**Comment by LazyFM** [comment]
проблему решил самостоятельно, добавив плагин Polylang

**Comment by Ahaenor** [comment]
Добрый день! Ок, прекрасно.

**Comment by LazyFM** [comment]
Увы, проблема не решилась. Плагин Polylang кривит мне заглавную страницу, переадресуя  index черте-куда, и форма Revo перестает работать корректно - пропадает кнопка ежемесячных платежей, а на следующем экране исчезают кнопки  выбора платежной системы (фото [раз](http://bytdob.ru/files/l-scr4.jpg) и [два](http://bytdob.ru/files/l-scr5.jpg)). Выключаешь Polylang - все отлично, но интерфейс плагина на английском, и черт бы с ним, что админский, но ведь и юзерский тоже, а это не гуд (фото [три](http://bytdob.ru/files/l-scr6.jpg) и [четыре](http://bytdob.ru/files/l-scr4.jpg)). Что можно сделать?

**Comment by klylex** [comment]
Добрый день.
А это же ваша почта - lazy@fmradio.ru?
11 июля вам отвечали на неё. Если письмо не получали, то проверьте папку "Спам".
