### ISSUE TITLE
Как сделать свою страницу успешного платежа?

### ISSUE THREAD

**Issue by LazyFM** [Teplitsa/Leyka#216]
Здравствуйте! в "настройках" - "разное" выставил заранее созданную страницу благодарности со встроенной в айфрейм гугл-формой, которую должен заполнить пользователь после платежа (адрес http://bytdob.ru/help/thankyou/ ) 
вместо нее Лейка подставляет свою страницу, да еще довольно странно выглядящую.
вот скриншот того, что мне надо:  http://bytdob.ru/files/l-scr2.jpg
ее код: http://bytdob.ru/files/l-scr3.jpg
вот то, что выдает плагин: http://bytdob.ru/files/l-scr1.jpg
как с этим бороться?

**Comment by klylex** [comment]
Добрый день.
А в разделе "Страницы" у вас только одна страница благодарности, которую вы сами сделали? Может там ещё есть шаблонная страница с такой же ссылкой?

**Comment by LazyFM** [comment]
C такой же ссылкой точно нет, для чистоты эксперимента я переменовал страницу в /thanx - абсолютно то же самое.

**Comment by klylex** [comment]
Добрый день.
Ответил на всё в общем письме.
