### ISSUE TITLE
Кнопка PayPal не производит никаких действий

### ISSUE THREAD

**Issue by oleg30** [Teplitsa/Leyka#217]
Здравствуйте!
Возникла проблема с платежной системой PayPal - все настроено по инструкции (https://leyka.te-st.ru/docs/nastrojka-paypal), но на странице платежа (где вводятся имя, email, комментарий) нажатие на кнопку PayPal ни к чему не приводит, даже не проверяет пустые поля (как на других платежных системах), а ведь вроде должна перейти на страницу платежа PayPal. 
Что мы делаем не так?

**Comment by klylex** [comment]
Добрый день.
Пришлите, пожалуйста, ссылку на вашу кампанию в Лейке, на эту почту - support@te-st.ru.
И в письмо также вставьте описание вашей проблемы.
