### ISSUE TITLE
Невозможно установить кампанию по умолчанию для mixplat

### ISSUE THREAD

**Issue by alekseysolo** [Teplitsa/Leyka#218]
Здравствуйте

Leyka/gateways/mixplat/leyka-class-mixplat-gateway.php
296 строка
было:
`'campaign_id' => leyka_options()->opt('mixplat-mobile_default_campaign_id'),`
нужно:
`'campaign_id' => leyka_options()->opt('mixplat-sms_default_campaign_id'),`
Первой опции (с mobile) в админ панели не существует, есть только вторая.
В результате не удавалось прикрепить кампанию по умолчанию для платежей через mixplat. После коррекции все работает корректно.

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо за репорт. Мы внесём эту правку.
