### ISSUE TITLE
Настройка оплаты для физ. лиц

### ISSUE THREAD

**Issue by Mamontosik** [Teplitsa/Leyka#22]
В настройках способа оплаты для физ лиц. необходимо указать ключ для API - "Пожалуйста, укажите секретную строку для API вашего аккаунта в системе Яндекс.Деньги". 

Подскажите, где его взять?

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за вопрос.

В инструкции по настройке платёжных систем есть информация о Яндекс.деньгах для физ. лиц. В том числе в ней поясняется, откуда можно взять секрет для проверки подлинности.
