### ISSUE TITLE
ip-адрес донора

### ISSUE THREAD

**Issue by iwizy** [Teplitsa/Leyka#220]
Здравствуйте! 

В было бы здорово добавить ip-адрес донора в информацию. Столкнулся с тем, что появились пожертвования, которые очевидно делались для тестирования того, как работает система. Для безопасности можно было бы блокировать особо настойчивых тестеров.

Спасибо!

**Comment by sidorenkoa** [comment]
iwizy, спасибо за предложение! Изучим, не нарушает ли это закон о ПДн и примем решение о том, включать ли такой функционал в бэклог
