### ISSUE TITLE
Виджет прогрессбара

### ISSUE THREAD

**Issue by xpandemia** [Teplitsa/Leyka#222]
Здравствуйте. Каким образом можно отобразить прогрессбар общий для всех кампаний?

**Comment by Ahaenor** [comment]
Добрый день.

Без дополнительного программирования, к сожалению, никак - обычно для пользователей плагина эта возможность неактуальна.

Но, технически, это несложная задача. Целевые суммы кампаний (в руб.) хранятся как post_meta у записей типа "leyka_campaign".

Спасибо за обращение!

**Comment by xpandemia** [comment]
Я имел в виду немного не это.
*Дано:*
Кампания 1 — Нужная сумма: 1000, собрано 250
Кампания 2 —   Нужная сумма: 5000 , собрано 1500
Кампания N —  Нужная сумма:  100, собрано 50

*Требуется: *
*1.*  автоматически подсчитать:
(Нужная сумма 1)+(Нужная сумма 2)+…+(Нужная сумма N)= *S*;
( собрано   1)+( собрано   2)+…+( собрано   N)= *M*.
*2.* Передать в виджет строку:
"Всего требуется собрать для всех кампаний: *S, *Уже собрано:* M*"




*С уважением. Андрей Калугин*




ср, 26 сент. 2018 г. в 14:58, Lev Zvyagintsev <notifications@github.com>:

**Comment by Ahaenor** [comment]
Да, мы так вас и поняли.

Сейчас виджет с прогрессбаром ориентирован на конкретную кампанию.
Чтобы сделать виджет "про все кампании, которые есть", нужно написать его самостоятельно.

Но это не оч. сложная задача - я бы рекомендовал скопировать виджет "карточка кампании" и изменить его параметры и код по вашему алгоритму выше. Метод для отображения карточки при этом можно не менять, если он вас устраивает.
