### ISSUE TITLE
Notice: Undefined index: show_donation_comments in 

### ISSUE THREAD

**Issue by 146754** [Teplitsa/Leyka#224]
После обновления сайта на wordpress на странице пожертвования, в блоке тех кто пожертвовал,
появилась надпись с ошибкой  

Notice: Undefined index: show_donation_comments in /var/www/deti39/data/www/deti39.com/wp-content/plugins/leyka/inc/leyka-shortcodes.php on line 396

Сейчас скрыл отображение ошибки, решить её нужно.
https://www.deti39.com/campaign/arina-anikina-17-let/#.W8CDo2gzbIX  Так же дублируется компания.

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо за репорт.

Ошибку с notice исправили - в будущей версии плагина её не будет.
Если важно исправить её на боевом сайте как можно быстрее, вы можете взять из гитхаба скрипт [/inc/leyka-shortcodes.php](https://github.com/Teplitsa/Leyka/blob/master/inc/leyka-shortcodes.php) и заменить им соотв. файл на сайте.

Насчёт дублирования кампаний - по указанному адресу мы видим страницу 404. Так должно быть?

**Comment by 146754** [comment]
Был откат системы.  Сейчас у нас С платежей не минусуется процент, оставшийся до сбора средств, хотя общая сумма сбора и сколько осталось - есть.
