### ISSUE TITLE
dataLayer Google Analytics

### ISSUE THREAD

**Issue by Mobilkanokia** [Teplitsa/Leyka#225]
Добрый день!
Подскажите, пожалуйста, есть ли возможность отсылать в аналитику детальные данные о пожертвованиях используя расширенную электронную торговлю или используя саму базу данных вордпресса?

**Comment by klylex** [comment]
Добрый день.
На данный момент такой функции нет.

**Comment by sidorenkoa** [comment]
от лица руководства Теплицы хотел бы добавить, что это важная функция и мы планируем ее внедрить до апреля 2019-го
