### ISSUE TITLE
Некорректная работа шаблона «Радио»

### ISSUE THREAD

**Issue by kakkoiirus** [Teplitsa/Leyka#227]
Добрый день!

В этом шаблоне всегда учитывается галочка «Ежемесячные пожертвования», даже если у этого метода оплаты регулярные платежи не поддерживаются.

Например:
Изначальное состояние «Оплата картой». Пользователь **ставит галочку** на ежемесячные пожертвования, переключает способ оплаты на «Альфа-клик», поле регулярных пожертвований исчезает. Пользователь нажимает оплатить и совершает разовое пожертвование.

В итоге в админке этот платёж записывается как «РЕГУЛЯРНОЕ: Альфа-Клик / Яндекс.Касса», хотя, по факту, это разовое пожертвование.

**Comment by klylex** [comment]
Добрый день.
Пришлите, пожалуйста, ссылку на вашу кампанию с проблемным шаблоном на эту почту - support@te-st.ru.
