### ISSUE TITLE
не открываются настройки выбранных платежных систем и не меняется их порядок в админке

### ISSUE THREAD

**Issue by 9301039** [Teplitsa/Leyka#23]
Крайний вордпрес, лейка 2.2.6, куки чистил, браузеры другие пробовал, инет и комп тоже

**Comment by Ahaenor** [comment]
Ок, спасибо за обращение.

Ситуация нетипичная - вероятно, конфликт между Лейкой и каким-либо другим плагином.
Можете дать доступ по FTP и в админку сайта? Пришлите, пожалуйста, на почту ahaenor@gmail.com

**Comment by Ahaenor** [comment]
Проблема была успешно разрешена, фикс войдёт в следующую версию плагина.

**Comment by 9301039** [comment]
Спасибо за оперативность! все же интересует когда будет фикс, т.к. подправили мне не на рабочем сайте а на тестовом :)

**Comment by Ahaenor** [comment]
Ответил по почте.
