### ISSUE TITLE
Лейка и Polylang

### ISSUE THREAD

**Issue by iwizy** [Teplitsa/Leyka#231]
Здравствуйте!
При включении Polylang приключается вот такая история
![2018-11-06 22 54 42](https://user-images.githubusercontent.com/7242327/48090066-fad1a000-e216-11e8-9e1b-bac3654c1bdf.png)

Стоит просто деактивировать и все встает на свои места. Polylang хотелось бы использовать, но не позволяет этот неприятный баг

**Comment by iwizy** [comment]
сейчас специально попробовал сделать голую установку. Поставил только Polylang и Лейку. Проблема аналогичная

**Comment by klylex** [comment]
Добрый день.
Другие шаблоны не пробовали? Там такая же проблема?
И скиньте, пожалуйста, ссылка на вашу кампанию.

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо, вопрос понятен.

Проблема с определёнными строками возникает из-за того, что в Лейке значения параметров плагина изначально внесены на языке локализации (в вашем случае, на русском).
**Уточним:** на английский переключаются только строки, которые вы можете поменять в настройках Лейки.

Полиланг позволяет переводить и статические строки, и значения настроек. Но он корректно переводит **только строки на английском** (базовом языке, не требующем локализации).

А при ситуации, когда сначала инсталлируется и настраивается Лейка (со значениями настроек на русском), а затем устанавливается Полиланг, последнему приходится иметь дело со значениями настроек **на русском**.

**Как это исправить**

1. Перейдите в настройки Лейки.

1.1. Измените значения всех настроек во вкладках "Вид" и "Валюта" с русскоязычных значений на англоязычные. Например, для параметра "Текст на кнопке отправки пожертвования" нужно изменить значение с "Пожертвовать" на "Donate".

1.2. На каждой вкладке сохраните изменения.

2. Перейдите в **Languages -> String translations**.

2.1. Вы видите список всех значений настроек ядра, всех тем и плагинов на сайте. Отфильтруйте этот список по домену "leyka" (вы получите все настройки Лейки).

2.2. В полученном списке найдите значения всех настроек, которые вы перевели на англ. язык на шаге 1.1 и 1.2.

2.3. Для каждой такой настройки в самом правом столбце списка укажите перевод на русский. Например, для параметра "Текст на кнопке отправки пожертвования" нужно указать перевод на русский "Пожертвовать".

2.4. Сохраните изменения.

После этого все переведённые вами поля настроек на всех формах для пожертвований будут на корректном текущем языке.

Спасибо за обращение!

**Comment by iwizy** [comment]
спасибо! буду пробовать!
