### ISSUE TITLE
Проблемы с платежами CloudPayments 

### ISSUE THREAD

**Issue by Ainur733** [Teplitsa/Leyka#233]
Здравствуйте. Помогите пожалуйста решить проблему с платежами. Установлен плагин Лейка, подключены платежи CloudPayments , все работало нормально уже год или два. Но с 26.11.18 почему то платежи не проходят. Не могу понять в чем проблема. В ЛК CloudPayments  выдает след ошибку: 
Request: POST http://lightinhands.ru/leyka/service/cp/check/
TransactionId=89297070&Amount=696.00&Currency=RUB&PaymentAmount=696.00&PaymentCurrency=RUB&OperationType=Payment&InvoiceId=6681&AccountId=100Rmage%40gmail.com&SubscriptionId=&Name=VLADIMIR+TSYBULSKIY&Email=100rmage%40gmail.com&DateTime=2018-11-27+12%3a05%3a48&IpAddress=92.63.93.6&IpCountry=LV&IpCity=&IpRegion=&IpDistrict=&IpLatitude=57&IpLongitude=25&CardFirstSix=535533&CardLastFour=1528&CardType=MasterCard&CardExpDate=08%2f22&Issuer=JSC+SEB+BANKA&IssuerBankCountry=LV&Description=%d0%9e%d0%bd%d0%bb%d0%b0%d0%b9%d0%bd+%d0%bf%d0%be%d0%b6%d0%b5%d1%80%d1%82%d0%b2%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d0%b5&TestMode=0&Status=Completed&Data=%7b%22cloudPayments%22%3a%7b%22recurrent%22%3a%7b%22interval%22%3a%22Month%22%2c%22period%22%3a1%7d%7d%7d
Response: {"code":"13","reason":"Unknown callback sender IP: 176.57.209.8 (IP permitted: 130.193.70.192, 185.98.85.109)"}

**Comment by Ahaenor** [comment]
Добрый день!

Судя по ошибке, CloudPayments сменили IP, с которого они отправляют Лейке служебные сообщения (коллбэки).

Это можно исправить:
 - либо добавив в настройках CloudPyaments в Лейке IP 176.57.209.8 (в поле списка разрешённых IP),
 - либо вообще убрав значение этого поля (тогда проверка на IP выполняться не будет).

Спасибо за обращение!

**Comment by Ainur733** [comment]
Спасибо большое! Помогло
