### ISSUE TITLE
CloudPayments: Размер платежа (amount) всегда "0.00"

### ISSUE THREAD

**Issue by newsiberian** [Teplitsa/Leyka#234]
Добрый день. Рамзер платежа обнулсяется после того, как данные вернутся с сервера. [Вот в этом месте](https://github.com/Teplitsa/Leyka/blob/cc6c2d8234be6f5793d8626fbab7669910e3756a/gateways/cp/js/leyka.cp.js#L53) размер соответствует выбранному, а дальне в коллбэке [вот здесь](https://github.com/Teplitsa/Leyka/blob/cc6c2d8234be6f5793d8626fbab7669910e3756a/gateways/cp/js/leyka.cp.js#L95) он всегда "0.00". Из за этого пользователи не могут перечислить нам деньги. Никаких ошибок не возникает, просто в консоль бросается исключение
```
Uncaught Error: Option 'amount' must be specified
    at r.auth (cloudpayments?ver=4.9.8:1)
    at r.charge (cloudpayments?ver=4.9.8:1)
    at Object.<anonymous> (leyka.cp.js?ver=2.3.9:91)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
```

**Comment by Ahaenor** [comment]
Добрый день!

Проблема ещё актуальна?
Если да, то на каком сайте её можно увидеть?

**Comment by newsiberian** [comment]
Добрый день, всё по прежнему.
https://mercuriya.ru/help-us/

**Comment by Ahaenor** [comment]
Спасибо, проблему видим.

Нам понадобится доступ в админ. панель сайта (уровня "администратор"), а также доступ к файлам сайта по FTP (лучше по SSH).

Эти доступы пришлите, пожалуйста, на почту support@te-st.ru

**Comment by Ahaenor** [comment]
Да, безусловно. Постараемся включить фикс в ближайший релиз (будет на днях).

Спасибо за обращение!
