### ISSUE TITLE
Ошибка после обновления

### ISSUE THREAD

**Issue by yurmar** [Teplitsa/Leyka#235]
Добрый день!
После обновления до 2.3.9 появилась ошибка:

Плагин не был активирован, потому что он вызвал фатальную ошибку.
Fatal error: Can't use method return value in write context in /home/p265836/www/bfrir.ru/wp-content/plugins/leyka/inc/leyka-ajax.php on line 148

Что делать?

**Comment by klylex** [comment]
Добрый день.
Ответили вам по почте.
