### ISSUE TITLE
Отображение оконченных кампаний

### ISSUE THREAD

**Issue by Mobilkanokia** [Teplitsa/Leyka#237]
Добрый день!
Подскажите, в новой третьей версии Лейки теперь не отображаются оконченные кампании выведенные на страницу при помощи шорткода? Если нет, то как можно вернуть отображение?
Спасибо!

**Comment by klylex** [comment]
Добрый день.
Пришлите, пожалуйста, ссылку на вашу страницу и сам шорткод, который вы используете.

**Comment by Mobilkanokia** [comment]
Страничка такая https://alsfund.ru/support/
Мы замапили этот шорткод [leyka_campaign_card id="xxx"] через Shortcode Mapper Visual Composer и уже давно пользуемся Visual Composer для добавления кампаний на эту страницу. После обновления Лейки перестали отображаться оконченные компании. Visual Composer версии 4.12, не обновляли. WordPress последней версии.

**Comment by Mobilkanokia** [comment]
Добрый день!
Подскажите, пожалуйста, существует ли у Лейки функционал для массового переноса регулярных платежей (не по одному) с закончившейся кампании на другую, не закончившуюся? Если существует, то как им пользоваться? 
И еще один вопрос:  в настройках Лейки в Оповещения указано, что при завершении кампании рассылается письмо-уведомление. Это во всех случаях (например, когда сумма собрана, но сбор закрыт) или только, если собрана целевая сумма?

**Comment by Ahaenor** [comment]
Добрый день!

Мы поправим это на днях и отпишем здесь.
После этого вы сможете обновить вручную, не дожидаясь релиза.

**Comment by Mobilkanokia** [comment]
Спасибо!
Будем ждать )

**Comment by Ahaenor** [comment]
Добрый день!

Попробуйте обновить плагин из ветки master.
Как минимум, достаточно будет обновить файл /inc/leyka-shortcodes.php

После этого добавьте к шорткодам завершённых кампаний на сайте атрибут show_finished="1":

`[leyka_campaign_card id="xxx" show_finished="1"]`

Такой шорткод должен выводить карточку кампании корректно.

**Comment by Mobilkanokia** [comment]
Спасибо за быструю помощь!
Обновили файл шорткодов, после этого отображение вернулось, атрибут show_finished="1" не добавляли, работает без него.

**Comment by Ahaenor** [comment]
Мы подумали и сделали значение "1" дефолтным для этого параметра)
Так что теперь нужно указывать show_finished="0" явно только если необходимо скрывать завершённые кампании.

Спасибо за обращение!
