### ISSUE TITLE
Перенос рекуррентных платежей с закончившейся кампании

### ISSUE THREAD

**Issue by Mobilkanokia** [Teplitsa/Leyka#238]
Добрый день!
Подскажите, пожалуйста, существует ли у Лейки функционал для массового переноса регулярных платежей (не по одному) с закончившейся кампании на другую, не закончившуюся? Если существует, то как им пользоваться?
И еще один вопрос: в настройках Лейки в Оповещения указано, что при завершении кампании рассылается письмо-уведомление. Это во всех случаях (например, когда сумма собрана, но сбор закрыт) или только, если собрана целевая сумма?

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо, вопросы понятны.

1. Массово перенести пожертвования в другую кампанию с помощью админ. раздела пока нельзя - это возможно только с помощью доп. программирования (хотя это несложная/недолгая задача).

1.1. Кроме того, можно изменить кампанию, на которую подписан рекуррент. При этом все последующие его списания будут относиться уже к новой кампании.

2. Уведомление, о котором вы упомянули, отправляется донорам кампании именно при достижении целевой суммы (таргета). Настройка кампании "кампания завершена" в этом не участвует.

Вас, возможно, смутил текст пояснения к этому полю в админ. разделе - мы переформулируем его.

Спасибо за обращение!
