### ISSUE TITLE
Поощрение доноров

### ISSUE THREAD

**Issue by olegtkirov** [Teplitsa/Leyka#24]
Хочется функцию создания в кампании поощрений для доноров. Думаю, функция понятна на примере больших краудфандинговых площадок.

В теле кампании конечно можно вручную нарисовать дополнительную информацию, но совершенно некуда записывать кто из доноров какой поощрительный бонус выбрал и как потом связаться с донором для доставки. 

Мне это видится каким-то дочерним от кампании типом записи, с набором полей. У приза есть заголовок, картинка, описание и поля для обратной связи (телефон, почтовый адрес, может что-то еще).

**Comment by Ahaenor** [comment]
Ок, спасибо за идею. Мы записали в список предложений.
