### ISSUE TITLE
Ошибка 502 при установке плагина Leyka

### ISSUE THREAD

**Issue by koshelkovnn** [Teplitsa/Leyka#240]
Пробовал установить плагин на 4-х разных хостингах, ошибка одна и таже, при установке плагина сайт недоступен. При удалении плагина через Ftp работа сайта возобновляется.

Ставил разные версии плагина и с офф. сайта и из репозитория Word Press.

Прошу вас помогите запустить плагин в работу. Спасибо!

**Comment by Ahaenor** [comment]
Добрый день!

Мы изучаем причину этой проблемы прямо сейчас, но пока не обнаружили её.

1. Какие хостинги вы использовали?

2. Есть ли у вас доступ к логам веб-сервера на каком-либо из этих хостингов? Если да, то что в логе ошибок при возникновении этой ошибки 502?

**Comment by koshelkovnn** [comment]
http://j941081.myjino.ru/wp-admin
логин/пароль
admin

Хостинг Джино, специально тестовый зарегистрировал.
https://cp-hosting.jino.ru/management/filemanager/files/domains

Логин:  j941081
Пароль:  6w7ydHXq

Сейчас плагин удален, попробуйте сами установить, уже третий день не получается. Спасибо.

**Comment by koshelkovnn** [comment]
До этого пробовал на реальном хостинге:  Джино, Хостия и Bget, решил что там с настройками не так что то и зарегистрировал еще один тестовый специально, но и тут никак не получается установить плагин. Спасибо.

**Comment by Ahaenor** [comment]
Ок, спасибо.

Вы могли бы переслать описание проблемы и доступы на почту support@te-st.ru?
Чтобы пароль не был виден посторонним)

**Comment by koshelkovnn** [comment]
Это тестовый аккаунт, ничего страшного, удалю его, как только вы решение предложите, как помочь в моей ситуации. Спасибо.

**Comment by koshelkovnn** [comment]
Добрый день, подскажите, получилось ли у вас решить мою проблему? Спасибо!

**Comment by Ahaenor** [comment]
Добрый день.

Нам всё-таки нужен доступ к вашему хостингу, где видна эта проблема.
Придётся узнавать детали у тех. поддержки хостинга.

Пришлите, пожалуйста, доступы в панель управления хостинга на email support@te-st.ru

В любом случае, сегодня проблему решить мы вряд ли успеем.

**Comment by koshelkovnn** [comment]
Хостинг Джино, специально тестовый зарегистрировал.https://cp-hosting.jino.ru/management/filemanager/files/domains Логин: j941081Пароль: 6w7ydHXq08.02.2019, 13:45, "Lev Zvyagintsev" <notifications@github.com>:Добрый день.
Нам всё-таки нужен доступ к вашему хостингу, где видна эта проблема.
Придётся узнавать детали у тех. поддержки хостинга.
Пришлите, пожалуйста, доступы в панель управления хостинга на email support@te-st.ru
В любом случае, сегодня проблему решить мы вряд ли успеем.

**Comment by koshelkovnn** [comment]
Только что, специально активировал плагин Лейка на сайте, и всё... Ошибка, сайт недоступен. Ссылка на сайт ниже: http://j941081.myjino.ru08.02.2019, 13:45, "Lev Zvyagintsev" <notifications@github.com>:Добрый день.
Нам всё-таки нужен доступ к вашему хостингу, где видна эта проблема.
Придётся узнавать детали у тех. поддержки хостинга.
Пришлите, пожалуйста, доступы в панель управления хостинга на email support@te-st.ru
В любом случае, сегодня проблему решить мы вряд ли успеем.

**Comment by Ahaenor** [comment]
Нам также понадобится доступ в админ. раздел сайта.

**Comment by koshelkovnn** [comment]
Логин и пароль admin13:56, 8 февраля 2019 г., Lev Zvyagintsev <notifications@github.com>:Нам также понадобится доступ в админ. раздел сайта.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Отправлено из  Яндекс.Почты.

**Comment by Ahaenor** [comment]
Ок, мы отправили заявку в техн. поддержку хостинга.
Сообщите нам, пжлст, когда они ответят.

**Comment by koshelkovnn** [comment]
Хорошо, спасибо.08.02.2019, 14:07, "Lev Zvyagintsev" <notifications@github.com>:Ок, мы отправили заявку в техн. поддержку хостинга.
Сообщите нам, пжлст, когда они ответят.

**Comment by koshelkovnn** [comment]
Пришел ответ от тех поддержки хостинга, посмотрите пожалуйста. Спасибо.08.02.2019, 14:07, "Lev Zvyagintsev" <notifications@github.com>:Ок, мы отправили заявку в техн. поддержку хостинга.
Сообщите нам, пжлст, когда они ответят.

**Comment by koshelkovnn** [comment]
Добрый день, прислали ответ: 1. Сколько указано в настройках сейчас?memory_limit 256 мб 2. Проблема точно в нехватке памяти?Нам, неизвестно в чем проблема. Обычно подобная проблема часто связана с нехваткой памяти на процесс. В Вашем случае это проблему не решает. Какая версия php требуется ?08.02.2019, 14:07, "Lev Zvyagintsev" <notifications@github.com>:Ок, мы отправили заявку в техн. поддержку хостинга.
Сообщите нам, пжлст, когда они ответят.

**Comment by Ahaenor** [comment]
Добрый день.

Проблема решена, в будущем она проявляться не будет.

Спасибо за обращение!
