### ISSUE TITLE
проверка настройки реккурентных платежей

### ISSUE THREAD

**Issue by DenisChuprov** [Teplitsa/Leyka#241]
Добрый день. Из инструкции непонятно:
 

> Создать новую рекуррентную подписку, сделав пожертвование через Яндекс.Кассу и отметив галочку «ежемесячные списания». Платёж должен быть доведён до статуса «оплачено».
> Вызвать в браузере адрес https://your-website.org/leyka/service/do_recurring/. После вызова проверьте состояние пожертвований в админ. разделе Лейки (страница «Пожертвования»).
> Если всё правильно, вы увидите новое пожертвование с размером, который вы указали ранее при создании рекуррентной подписки. Это новое пожертвование также должно быть в статусе «оплачено».

Если cron job выполняется раз в сутки, то исходя из логики вышесказанного получается, что с карт всех подписантов каждые сутки платеж будет списываться? Ну если я оплатил, тут же взаимодействую с нужным файлом и это влечет повторное списание... Объясните, пожалуйста.

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за вопрос.

В описанном вами случае средства будут списываться не со всех рекуррентных подписантов вообще, а только с тех, чьи подписки должны списываться текущего числа каждого месяца.

Поэтому вызывать УРЛ для рекуррентных списаний нужно каждый день.

**Comment by DenisChuprov** [comment]
ага, теперь понятно, почему нужно cron настраивать на ночью. Спасибо за инструмент, Вы очень помогли нашему фонду

**Comment by Ahaenor** [comment]
Пжлст, мы рады, что Лейка полезна для вас.

Спасибо за обращение!
