### ISSUE TITLE
статус платежа в лейке один и тот же всегда

### ISSUE THREAD

**Issue by DenisChuprov** [Teplitsa/Leyka#242]
Сайт sofiafond.ru
Подключаемся через вас к яндекс кассе. новое API . При пожертвованиях успешных и неуспешных один и тот же статус в лейке "Попытка пожертвовать".
URL для уведомлений прописан https://www.sofiafond.ru/leyka/service/yandex/process/
Что может быть не так?

**Comment by DenisChuprov** [comment]
проблема была в том, что url уведомления стоял с www.sofiafond.ru, а на сайте стоит переадресация на sofiafond.ru (без www). Убрали из урл www и все заработало

**Comment by Ahaenor** [comment]
Ок, прекрасно.

У разных платёжных операторов разные правила по поводу редиректов в адресах коллбэков.
Но общее правило здесь - чем их (редиректов) меньше, тем лучше.
