### ISSUE TITLE
Only revo template is working

### ISSUE THREAD

**Issue by alex-krasnyansky** [Teplitsa/Leyka#243]
Hi Team,

I am trying to use Neo template at https://angelbf.ru/campaign/tselevoj-sbor-20000/

However the page comes without a content. Could you advice, why? Tried all the templates, only Revo works, but we want Neo or at least Blocks.

I ruled out plugin incompatibility, for which I deactivated all the plugins except Leyka.

The system info:
WordPress 5.0.3 с темой оформления BF Angel.
Running PHP version: 7.2.15

**Comment by Ahaenor** [comment]
Hello,

it's a known issue, already fixed in the "master" branch.
You can update the plugin manually from the current master code, or wait for the official plugin release 3.0.4 (planned for the feb 25th).

Thank you for the report!

**Comment by alex-krasnyansky** [comment]
Thanks!
