### ISSUE TITLE
Language alert when redirecting to payment portal

### ISSUE THREAD

**Issue by alex-krasnyansky** [Teplitsa/Leyka#244]
When using a payment portal (Яндекс & Робокасса) right after clicking Donate button, the following alert window appears, asking to select a locale. ru is populated in the window, and the payment proceeds normally if Ok is clicked.
See the screenshot:
[https://c.radikal.ru/c13/1902/af/5a0db14b71c6.png](https://c.radikal.ru/c13/1902/af/5a0db14b71c6.png)

**Comment by klylex** [comment]
Hello,

Please write to our mail support@te-st.ru. With a description of the problem and a screenshot.

P.S. И можно писать на русском языке.
