### ISSUE TITLE
Платёж завершён с ошибкой

### ISSUE THREAD

**Issue by DenisChuprov** [Teplitsa/Leyka#245]
добрый день. Более двух лет лейка работала без возможности приема реккурентных платежей. Сейчас мы их подключили и систематически в час ночи (на это время у нас настроен Cron) система пытается списать деньги с карт людей, которые пытались настроить реккурентные платежи пару лет назад, все эти платежи (около 5ти подряд) завершаются с ошибкой "Платёж завершён с ошибкой ". Как нам обнулить всех подписантов, ведь они могут уже и не помнить, что они подписывались на нас и репутация Фонда пострадает. Спасибо

**Comment by Ahaenor** [comment]
Добрый день!

Если речь о рекуррентных подписках в Яндекс.Кассе, то отменить подписку донора можно так:

1. зайти на страницу редактирования пожертвования в админ. разделе Лейки,
2. снять галочку "рекуррентная подписка активна",
3. сохранить.

Это отменит подписку для данного донора.
Такую операцию нужно повторить для всех подписок, которые нужно отменить.
