### ISSUE TITLE
Как вывести данные плагина на страницу через php?

### ISSUE THREAD

**Issue by pvlomtev** [Teplitsa/Leyka#246]
Добрый день!

Есть сайт: aliot-fond.ru 
Заказчик дал задачу сделать все, как у WorlVita. 

Я успешно вывел название компании, ID.
Поля диагноз и возраст сделал через доп поля.  

Вопрос в том, как вывести прогрессбар пожертвований отдельно путем программирования? Какой код отвечает за вывод? Искал в виджетах, понял что scale, но так и не разобрался как вывести. 

Также вопрос по виджету "История пожертвований". Я так понимаю, что она для каждой компании своя. А можно сделать общую? И как вывести имя донора, сумму доната?

**Comment by Ahaenor** [comment]
Добрый день!

**1. Прогрессбар**

Если вас устроит разметка, которую использует сама Лейка, то прогрессбар можно вывести с пом. функции leyka_get_scale() - она определена в /inc/leyka-shortcodes.php.
Обратите внимание, что результат функциии - HTML прогрессбара - можно отфильтровать.

Если же разметка прогрессбара Лейки вас не устроит, вы можете написать собственный кастомный код для получения пожертвований из БД сайта.

**2. Общий список пожертвований**

Лейка создаёт страницу списка пожертвований как архив записей типа leyka_donation.
Адрес этого архива по умолчанию your-site.org/donations/.
Но эта страница (по умолчанию) использует шаблон вашей темы:

- либо index.php,
- либо, если вы хотите сделать кастомный шаблон страницы архива, archive-leyka_donation.php.

**Comment by pvlomtev** [comment]
Спасибо! А как вывести в архиве по адресу: aliot-fond,ru/donations/ сумму пожертвования, имя донора, дату пожертвования и систему платежную??14.03.2019, 13:17, "Lev Zvyagintsev" <notifications@github.com>:Добрый день!
1. Прогрессбар
Если вас устроит разметка, которую использует сама Лейка, то прогрессбар можно вывести с пом. функции leyka_get_scale() - она определена в /inc/leyka-shortcodes.php.
Обратите внимание, что результат функциии - HTML прогрессбара - можно отфильтровать.
Если же разметка прогрессбара Лейки вас не устроит, вы можете написать собственный кастомный код для получения пожертвований из БД сайта.
2. Общий список пожертвований
Лейка создаёт страницу списка пожертвований как архив записей типа leyka_donation.
Адрес этого архива по умолчанию your-site.org/donations/.
Но эта страница (по умолчанию) использует шаблон вашей темы:

либо index.php,
либо, если вы хотите сделать кастомный шаблон страницы архива, archive-leyka_donation.php.

**Comment by Ahaenor** [comment]
По образцу других страниц архивов.

1. В скрипте шаблона страницы архива, скорее всего, будет цикл, который перебирает объекты WP_Post.
2. В нашем случае эти объекты - посты типа leyka_donation (пожертвование).
3. У Лейки есть внутренний API для работы с пожертвованиями. Он позволяет создать из объекта WP_Post объект `Leyka_Donation: $donation = new Leyka_Donation($post);`
4. Далее вы можете использовать поля объекта Leyka_Donation для получения указанных вами атрибутов пожертвований (суммы, имени донора, способа оплаты и др.).
5. Полный список полей пожертвования, которые доступны через объект Leyka_Donation, вы можете увидеть в скрипте /inc/leyka-class-donation.php, в методе __get() класса Leyka_Donation.

**Comment by pvlomtev** [comment]
Добрый день! Вопрос: почему при оплате через Яндекс деньги (банковской картой) не меняется статус пожертвования на "Оплачено", а висит попытка пожертвовать!Хотя оплата успешно прошла. Как это поправить?14.03.2019, 13:17, "Lev Zvyagintsev" <notifications@github.com>:Добрый день!
1. Прогрессбар
Если вас устроит разметка, которую использует сама Лейка, то прогрессбар можно вывести с пом. функции leyka_get_scale() - она определена в /inc/leyka-shortcodes.php.
Обратите внимание, что результат функциии - HTML прогрессбара - можно отфильтровать.
Если же разметка прогрессбара Лейки вас не устроит, вы можете написать собственный кастомный код для получения пожертвований из БД сайта.
2. Общий список пожертвований
Лейка создаёт страницу списка пожертвований как архив записей типа leyka_donation.
Адрес этого архива по умолчанию your-site.org/donations/.
Но эта страница (по умолчанию) использует шаблон вашей темы:

либо index.php,
либо, если вы хотите сделать кастомный шаблон страницы архива, archive-leyka_donation.php.

**Comment by Ahaenor** [comment]
Добрый день.

Вероятно, не настроены адреса для системных уведомлений (коллбэков) Яндекс.Кассы.
Проверьте, пожалуйста, всё ли настроено как в [инструкции по подключению ЯК](https://leyka.te-st.ru/docs/yandex-dengi/).

**Comment by pvlomtev** [comment]
Я использую Яндекс деньги для физических лиц. 
--
Отправлено из Mail.Ru для Android четверг, 14 марта 2019г., 15:15 +03:00 от Lev Zvyagintsev  notifications@github.com :

**Comment by Ahaenor** [comment]
Тогда ответ аналогичен, но с поправкой на Яндекс.Деньги для физ. лиц.

Однако этот способ оплаты давно не тестировали - он может не работать.
С другой стороны, мы вообще крайне не рекомендуем его для НКО (из-за
потенциальных проблем с налогообложением).

чт, 14 мар. 2019 г. в 15:17, pvlomtev <notifications@github.com>:

**Comment by pvlomtev** [comment]
Добрый день, ещё вопрос, как мне сделать, чтобы в виджете оплаты люди могли сами указывать какая программа?У нас есть виджет HTML, как его настроить на оплату через Лейку? 1) как передать значения input  дальше2) Как подцепить кнопку оплатить на оплату? Два варианта: 1) Выпадающий список активных компаний2) Руками вбивают И ещё вопрос: можно ли как-то потестировать CloudPayments без долгого подключения по шагам? По тестовому ID?14.03.2019, 15:30, "Lev Zvyagintsev" <notifications@github.com>:Тогда ответ аналогичен, но с поправкой на Яндекс.Деньги для физ. лиц.



Однако этот способ оплаты давно не тестировали - он может не работать.

С другой стороны, мы вообще крайне не рекомендуем его для НКО (из-за

потенциальных проблем с налогообложением).



чт, 14 мар. 2019 г. в 15:17, pvlomtev <notifications@github.com>:

**Comment by pvlomtev** [comment]
Добрый день. Скажите, пожалуйста, где найти документацию по инпутам платежной формы?Как мне из свой формы передавать значения в лейку? И как сделать, чтобы не надо было выбирать ID компании, а человек сам в инпуте указывал назначение (кампанию из выпадающего списка). И можно ли у вас подобное заказать на платной основе?14.03.2019, 15:30, "Lev Zvyagintsev" <notifications@github.com>:Тогда ответ аналогичен, но с поправкой на Яндекс.Деньги для физ. лиц.



Однако этот способ оплаты давно не тестировали - он может не работать.

С другой стороны, мы вообще крайне не рекомендуем его для НКО (из-за

потенциальных проблем с налогообложением).



чт, 14 мар. 2019 г. в 15:17, pvlomtev <notifications@github.com>:

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо за вопросы.

Просьба к вам - создайте под каждый вопрос отдельную тему, пжлст.
Данный топик получил ответ и уже неактуален.
