### ISSUE TITLE
Как вывести все активные компании в выпадающем списке?

### ISSUE THREAD

**Issue by pvlomtev** [Teplitsa/Leyka#247]
Очень нужно сделать, чтобы человек мог выбрать выбрать определённую компании в платежном виджете из активных в выпадающем списке? Подскажите, пожалуйста, как можно обратиться к списку? И как реализовать?

**Comment by pvlomtev** [comment]
Потом выбранную компанию нужно будет передать в input платежного виджета. 

Вообще, в целом, хотелось бы, чтобы был виджет общий для пожертвований, с возможностью выбора компании.

**Comment by Ahaenor** [comment]
Добрый день.

1. Шаблоны форм пожертвований, встроенные в Лейку, всегда расчитаны на 1 кампанию.

Чтобы реализовать возможность выбирать кампанию на форме, вам необходимо создать собственный (кастомный) шаблон кампании - по образцу тех шаблонов, которые уже есть в плагине (см. папку /templates/ в корне плагина).

Кампании для списка можно получать с помощью стандартных функций WP - например, get_posts(array('post_type' => 'leyka_campaign')).

2. Добавить возможность выбирать кампанию на встроенные шаблоны форм в наши цели не входит, к сожалению. Эта фича бывает нужна очень редко.

Спасибо за обращение!
