### ISSUE TITLE
Списание на следующий день после реккурентной подписки

### ISSUE THREAD

**Issue by DenisChuprov** [Teplitsa/Leyka#248]
Добрый день. У нас проблема. Подключили реккурентные платежи, настроили крон задание. выявили проблему. Человек платит, подписываясь на ежемесячное пожертвование, на следующий день в час ночи у него списывается та же  сумма. То есть не через месяц, а на следующий день. С чем это связано? Есть одна мысль, что может на хостинге сбито время или установлен другой часовой пояс и крон задание выполняется не в 01.00 нового дня, а, например, в 23.00 текущего после платежа?

**Comment by DenisChuprov** [comment]
посмотрел по логам, крон обращение действительно идет в час ночи. Да и в спике пожертвований написано, час ночи.
Что делать? Сегодня у нас было много подписок на регулярные платежи?

**Comment by klylex** [comment]
Добрый день.
Да, дело в часовых поясах. Это можно исправить так:
– настроить крон лучше на более позднее время - где-то на 04.00.
– при этом в настройках сайта WordPress лучше указать часовой пояс не просто "+N", а по городу, в котором соответствует смещение времени.
