### ISSUE TITLE
Шорткод для получения списка кампании по тегу

### ISSUE THREAD

**Issue by ikruglov** [Teplitsa/Leyka#249]
Здравствуйте,

Меня интересует шорткод который выдавал бы список кампании по заданному тэгу. Как я понимаю, Лейка пока такого пока не умеет. Я прав? Если да, то я хочу добавить его. С вашей помощью конечно :-)

**Comment by klylex** [comment]
Добрый день.
А что вы имеете в виду под фразой "по заданному тэгу"?

**Comment by ikruglov** [comment]
Здравствуйте. У меня есть ряд кампаний у которых проставлены метки (или теги). Например: кампания А с меткой А, кампания АА с меткой А и кампания Б с меткой Б. Я хочу сделать (или использовать существующий) шорткод типа:

```
[leyka_campaigns_list tag="A"]
```

который показал бы все кампании с меткой/тегом А. Т.е. кампании А и АА из примера выше.

**Comment by ikruglov** [comment]
@klylex, ответ в посте выше. Я не вижу как я могу переоткрыть этот issue.

**Comment by klylex** [comment]
Добрый день.
Ясно, спасибо.
Да, такого функционала в Лейке нет.
