### ISSUE TITLE
Плагин отключает настройку внешнего smtp сервера

### ISSUE THREAD

**Issue by a-s-k** [Teplitsa/Leyka#25]
При использовании плагина для отправки почты сервером через сторонний сервис (например Gmail) после установки лейки пишет:
Postman: wp_mail has been declared by another plugin or theme, so you won't be able to use Postman until the conflict is resolved.
и данная настройка отправки почты не работает.
Данное решение актуально, если используется отдельный IP и желания (возможности изменить PTR запись) прописывать его в днс нет.
В частности у я использую Postman SMTP Mailer/Email Log для WP https://wordpress.org/plugins/postman-smtp/

**Comment by Ahaenor** [comment]
Добрый день, спасибо за замечание. Мы займёмся этим вопросом.

**Comment by Ahaenor** [comment]
Ошибка несовместимости исправлена. Исправление вошло в версию 2.2.7.2.

**Comment by calliko** [comment]
Скажите, как исправили, пожалуйста. В моем плагине такая же проблема. Спасибо
