### ISSUE TITLE
Вставка кнопки "Пожертвовать" в любом месте шаблона

### ISSUE THREAD

**Issue by MihMihich** [Teplitsa/Leyka#250]
Добрый день.

Возникла необходимость вставки только кнопки "Пожертвовать" в определенном месте в шаблоне. По нажатию на неё должно всплывать окно пожертвований из шаблона Revo.
Ознакомился с данной веткой обсуждения, разобрался и научился выводить нужные данные из кампаний по сбору (прогресс, суммы и т.д.) в нужных местах, но с кнопкой никак не выходит такой трюк.
Это возможно? Как это сделать?
Заранее спасибо.

**Comment by klylex** [comment]
Добрый день.
Ответили на вашу почту.

**Comment by Centrtruda** [comment]
Добрый день,
интересует такая же функция. Как это сделать?
Благодарю.

**Comment by MihMihich** [comment]
Добрый день

По вашему сообщению на гите лейки.
То служба поддержки мне ничего не подсказала, мол разбирайтесь сами,
функционала такого нет.
Но я у себя через костыль всё таки сделал эту функцию. Костыль заключается
в том, что я просто скрываю куски формы через CSS и вывожу только кнопку. А
во всплывающей форме снова показываю всё.

-----
С уважением,
Мазур Михаил Михайлович

+---------------------------------+
Tel.: +7 914 706-44-04
ICQ: 8128889
Skype: Cefirovod256
Mail agent: mike256@mail.ru
Email: mihailmm@gmail.com
Jabber: mikelangelo@jabber.ru
+---------------------------------+


пт, 26 апр. 2019 г. в 04:02, Centrtruda <notifications@github.com>:

**Comment by Ahaenor** [comment]
Да, это вполне рабочий вариант. В будущем мы попробуем поддержать эту функцию средствами плагина.

Спасибо за комментарий.
