### ISSUE TITLE
Не срабатывает do_shortcode

### ISSUE THREAD

**Issue by MihMihich** [Teplitsa/Leyka#251]
Добрый день

Вывожу кампанию через do_shortcode('[leyka_campaign_form id="2160"]') в нужном месте страницы в шаблоне. Внешний вид всё ок, но кнопка пожертвовать не вызывает всплывающее окно. Использую Рево.

А вот если дополнительно к этому вывести в тексте страницы через шорткод [leyka_campaign_form id="2160"] в админке во время редактирования страницы, то всё работает. И на первом варианте и на втором. 

Почему  так? Почему do_shortcode не срабатывает? Что-то не подгружается?

**Comment by klylex** [comment]
Добрый день.
Ответили по почте.
