### ISSUE TITLE
Настройка платежей - Пошаговая инструкция

### ISSUE THREAD

**Issue by MihMihich** [Teplitsa/Leyka#252]
Добрый день

Пытаюсь настроить системы платежей CloudPayments и Яндекс.Касса.
В админке на нужном способе горит кнопка "Пошаговая инструкция", на которую я нажимаю и выдает ошибку "Извините, вам не разрешено просматривать страницу". Что не так? Как настроить платеж? Скрины приложил.
![2019-04-19_20-59-23](https://user-images.githubusercontent.com/4371715/56448712-05ab6780-6355-11e9-836d-c265ff5ca102.png)
![2019-04-19_20-59-12 (2)](https://user-images.githubusercontent.com/4371715/56448743-502ce400-6355-11e9-9912-1f1c4e735449.png)

**Comment by klylex** [comment]
Добрый день.
Ответили по почте.
