### ISSUE TITLE
Лейка не работает, если в качестве сервера используется caddy

### ISSUE THREAD

**Issue by asm0dey** [Teplitsa/Leyka#253]
Если вместо обычного nginx в качестве сервера использовать [caddy](https://caddyserver.com/) — то всё в вордпрессе работает, а вот лейка — почему-то нет. php-fpm 7.3 в качестве fastcgi.

**Comment by klylex** [comment]
Добрый день.
А что именно не работает? Выдаёт какую-то ошибку?

**Comment by asm0dey** [comment]
Да, обсуждали проблему в чате поддержки.
Как минимум через Яндекс-кассу когда пытаешься внести деньги всё ломается
после подтверждения в интернет-эквайринге. Яндекс-касса говорит, что не
получила подтверждения от банка, но на самом деле это от лейки не приходит
подтверждения

пн, 22 апр. 2019 г., 10:06 Alexey Klyosov <notifications@github.com>:

**Comment by foralien** [comment]
Павел, здравствуйте!

Мы с коллегами обсудили вашу проблему. Мы, разумеется, постараемся
исправить явные ошибки с переменными окружения в будущих версиях Лейки.
Но причину ошибки интеграции с Яндекс.Кассой по присланным вами в чат
данным установить не удалось.
Если в логах есть информация по этой ошибке, пришлите пожалуйста.

В целом, что решить проблему, мы рекомендуем вам использовать nginx или
apache в качестве веб-сервера.


С уважением, Денис Ч.
служба поддержки
«Теплица социальных технологий»
te-st.ru
https://www.facebook.com/TeplitsaST


пн, 22 апр. 2019 г. в 09:21, Paul <notifications@github.com>:

**Comment by asm0dey** [comment]
Ну да, я так и сделал — откатился на nginx. Найти ошибок в логе, которые могут  чём-то сказать нам всем вместе не удалось. 
Так что подозреваю что есть какая-то странность во взаимодействии caddy с fastcgi, которая ломает лейку. 
Ну и фичереквест, соответственно, о том, чтобы воспроизвести у себя и попробовать разобраться где проблема — в caddy, fastcgi модуле caddy или лейке. 
Например всегда есть вероятность того, что настройки SSL, по умолчанию настроенные в caddy слишком строги для банков.

**Comment by foralien** [comment]
Павел, мы учтем ваш запрос.
Но в ближайшее время подробная отладка плагина для совместимости с caddy не
планируется.

С уважением, Денис Ч.
служба поддержки
«Теплица социальных технологий»
te-st.ru
https://www.facebook.com/TeplitsaST


пн, 22 апр. 2019 г. в 13:00, Paul <notifications@github.com>:
