### ISSUE TITLE
Вывод кампании в меню

### ISSUE THREAD

**Issue by svetlana-ems** [Teplitsa/Leyka#255]
Добрый день! 

Нам для вывода кампаний ( конечного элемента) нужно что бы шаблон вывода был не single.php . Через принудительное редактирование в сингле для категории лейка никак не реагирует и все равно выводит шаблон по умолчанию. Где мы можем изменить путь к шаблону что бы для компании брался шаблон single-happy.php
Пример страницы http://fond.web2dev.site/campaign/vasilev-matvej-3/
Страница должна относится к разделу "Дети" - Нужна помощь

Спасибо!

**Comment by Ahaenor** [comment]
Добрый день!

В целом, для вывода страницы кампании служит шаблон single-leyka_campaign.php

Если его не достаточно (т.е. в ряде случаев нужен какой-то другой), это можно сделать через код - с помощью фильтра template_redirect.

Если нужно, мы готовы пояснить подробнее.
