### ISSUE TITLE
Подключение платежных систем

### ISSUE THREAD

**Issue by svetlana-ems** [Teplitsa/Leyka#256]
Добрый день! Два вопроса
1. Я правильно понимаю, что я могу одновременно подключить Хронопей, Яндекс. Кассу и Робокассу? Хронопей мне нужен для регулярных платежей
2. На старом сайте у знакомых есть лейка, сейчас хотят делать новый сайт. Что нужно чтобы подключить аккаунт со старого сайта на новый?

**Comment by Ahaenor** [comment]
Добрый день!

1. Да, всё так. Одновременно может быть подключено любое количество платёжных операторов.
Однако оператор не обязательно должен использоваться (т.е. быть доступным для платежа) на формах для пожертвований - он может быть, например, резервным.

2. Это зависит от того, какие платёжные операторы у них используются.
Самой Лейке почти всегда достаточно просто перенести настройки оператора.

2.1. Но если у сайта меняется домен (адрес), то нужно будет менять настройки адресов коллбэков. Это делается в Личном кабинете соотв. платёжного оператора.

Если нужно, мы поясним подробнее.

**Comment by svetlana-ems** [comment]
Поясните, пожалуйста, второй пункт по подключению. Мне нужно знать какие доступы нужно предоставить программисту для подключения лейки на новом сайте

**Comment by Ahaenor** [comment]
2.1. Обычно для подключения на новом сайте нужны следующие доступы:

- К сайту по FTP (лучше по SSH).
- В админ. раздел сайта (аккаунт уровня "администратор").
- В Личный кабинет каждого из используемых вами платёжных операторов (например, CloudPayments или Яндекс.Касса).
