### ISSUE TITLE
Warning: illegal string offset 'yandex-yandex_card'

### ISSUE THREAD

**Issue by MihMihich** [Teplitsa/Leyka#258]
Добрый день

Столкнулся с предупреждением. Вопрос, влияет ли оно как то на работу или нет? И как устранить?

Проблема встречается на Лейке 3.1 и WP 4.9 и на Лейке 3.2 и WP 5.0.1. Разница только в номерах строк.

Скрин приложил. Появляется при сохранении настроек платежного модуля Яндекс.Кассы.

![2019-04-26_15-04-45 (2)](https://user-images.githubusercontent.com/4371715/56785426-7ad8da00-6838-11e9-889e-8894f3b1f333.png)
![2019-04-26_15-14-18](https://user-images.githubusercontent.com/4371715/56785427-7b717080-6838-11e9-997c-fc835c896632.png)

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо, мы проверим.

**Comment by Ahaenor** [comment]
Добрый день!

Мы проверили условия, которые вы описали.
На WP 5.0.1+ и Лейке 3.2.1 проблемы не видно.

Ошибка проявляется на последней версии Лейки и ядра WP?
