### ISSUE TITLE
Платеж не проходит 

### ISSUE THREAD

**Issue by svetlana-ems** [Teplitsa/Leyka#259]
Добрый день!
Ситуация следующая. 
Сделали для клиента новую версию сайта на тестовом домене, подключили лейку с параметрами, которые присутствуют на старой версии сайта, но на тестовом домене платежи не проходят. Пишет, что ошибка банка. 

Я правильно понимаю, что проблема именно в том, что мы пытаемся провести платеж на тестовом домене?

**Comment by Ahaenor** [comment]
Добрый день!

Да всё так.

Для корректного взаимодействия сайта с платёжным оператором в настройках оператора должны быть указаны адреса для служебных запросов (коллбэки).
Эти адреса, естественно, включают домен сайта.
Если они указаны неправильно, то сайт делает попытку платежа с одного домена, а оператор обращается за подтверждением к другому.
Отсюда и ошибки.

Спасибо за обращение!
