### ISSUE TITLE
Договор-оферта, чекбокс не работает.

### ISSUE THREAD

**Issue by nesutulsa** [Teplitsa/Leyka#26]
Друзья, у нас не работает чекбокс с подтверждением условий сбора пожертвований.

Пример, https://fond39.com/campaign/agunina/ - чекбокс не реагирует.

К сожалению, все сборы и компании пришлось остановить.
Будем благодарны за помощь.

//upd - required находится в классе

**Comment by DenisCherniatev** [comment]
Занимаемся поиском и решением проблемы.

**Comment by DenisCherniatev** [comment]
Повторить ошибку не удалось, но предполагаемая причина ошибки найдена и устранена. На github выложено обновление. Ожидайте обновление плагина на сайте WP в ближайшее время.

**Comment by nesutulsa** [comment]
Спасибо, будем ждать. Кстати, верстали на бутстрэпе. Если не ошибаюсь, css лейки грузится в подвале? В итоге стили конфликтуют, Бутстрап перекрывает. Может в шапку по default грузить?

**Comment by Ahaenor** [comment]
Добрый день.

Новая версия вышла - 2.2.7.1. Попробуйте обновить плагин на вашем сайте.

**Comment by nesutulsa** [comment]
Только что, спасибо.

После обновления проблема с "реквауред" исчезла, спасибо.
Кастыль по css как раз слетел ) Чекбокс поехал, в бутстрапе https://fond39.com/campaign/save-kashtan/

Сброс всех стилей происходит. Это поправило, но вам на заметку, плагин же должен быть идеальным?) Спасибо за поддержку.
