### ISSUE TITLE
Обрезанные значки в форме оплаты 

### ISSUE THREAD

**Issue by svetlana-ems** [Teplitsa/Leyka#260]
Добрый день! 

В форме значки "виза" "сбербанк" - там обрезаный текст. Это можно исправить в настройках или нет? 
![image](https://user-images.githubusercontent.com/49938725/57066687-87947c80-6cd5-11e9-93e8-3d3f1ad273a5.png)

**Comment by avdeeva-nataliya** [comment]
Добрый день! 

Скажите, пожалуйста, версию вашего браузера, попробуем проверить. У меня в Chrome форма выглядит нормально: 

![2019-05-06_09-43-01](https://user-images.githubusercontent.com/46969290/57209963-638daf80-6fe3-11e9-89ca-9a6ebdb8c8aa.png)

**Comment by svetlana-ems** [comment]
Наталья, добрый день! 

Хром Версия 73.0.3683.103. Сейчас отображается ок
Проверьте пожалуйста еще Оpera

**Comment by avdeeva-nataliya** [comment]
В Opera тоже всё хорошо, не получается воспроизвести. 
Если ещё раз возникнет проблема, напишите, пожалуйста.
