### ISSUE TITLE
Qiwi для физических лиц

### ISSUE THREAD

**Issue by zikkuratvk** [Teplitsa/Leyka#261]
Привет.
Для физ лиц qiwi открыла прием платежей с уведомлением об оплате.
Ключи генерируются, форма генерируется правильно, платеж проходит, но почему то указанный калбек по аналогии с платежами физ лиц для яндекса не срабатывает.

**Comment by Ahaenor** [comment]
Добрый день!

Пока поддержка платежей Qiwi на счёт физ. лиц не планируется.
Но возможно, однажды мы её добавим - спасибо за сообщение.
