### ISSUE TITLE
Формы пожертвования на разных языках

### ISSUE THREAD

**Issue by svetlana-ems** [Teplitsa/Leyka#262]
Добрый день! 

На сайте есть английская версия, на которую мы хотим добавить форму оплаты на английском языке
Уточните, пожалуйста, можно ли на сайте использовать несколько форм на разных языках?

**Comment by avdeeva-nataliya** [comment]
Добрый день! Да, это возможно с помощью плагина Polylang. Вот тут есть небольшая инструкция про него: https://leyka.te-st.ru/docs/kak-perevesti-vash-sajt-plagin-lejka-rabota-s-plaginom-polylang/
