### ISSUE TITLE
Отображение суммы пожертвований

### ISSUE THREAD

**Issue by svetlana-ems** [Teplitsa/Leyka#263]
Добрый день! 
В предыдущей версии пользователей видел сумму, которую он перечислил и сумму, которую получил фонд с учетом комиссии
![image](https://user-images.githubusercontent.com/49938725/57697077-1486f080-765b-11e9-9f87-b44d0240e6e5.png)
В новой версии отображается общая сумма
![image](https://user-images.githubusercontent.com/49938725/57697139-397b6380-765b-11e9-9e7c-61c4b702eb27.png)

**Уточните, пожалуйста, как можно настроить отображение пожертвований, чтобы пользователь видел как раньше две суммы**

Спасибо!

**Comment by avdeeva-nataliya** [comment]
Добрый день! Дайте, пожалуйста, ссылку на кампанию.

**Comment by svetlana-ems** [comment]
Новая кампания https://fond-providenie.ru/campaign/finagina-elena/#leyka-payment-form
Старая кампания http://new.fond-providenie.ru/campaign/vasilev-matvej/#leyka-payment-form

**Comment by avdeeva-nataliya** [comment]
А комиссия указана в настройках платёжных систем?

**Comment by svetlana-ems** [comment]
Наталия, в новой кампании комиссию не прописывали. В старой версии не было вообще поле комиссия. 
Я правильно понимаю, если прописать % комиссии для каждой системы, то пользователь  увидит сумму, которую он перечислил и сумму, которую получил фонд с учетом комиссии

**Comment by avdeeva-nataliya** [comment]
Я сейчас проверила на тестовом сайте: да, если указать комиссию, то в истории пожертвований видно две суммы, как на первом вашем скриншоте.
