### ISSUE TITLE
nothing found for leyka

### ISSUE THREAD

**Issue by vertjs** [Teplitsa/Leyka#265]
здравствуйте! 
Не работает ни одна платежная система. При открытии стандартного окна Лейки с надписью "Благодарим вас!
Через несколько секунд вы будете перенаправлены на страницу платёжной системы, где вы сможете подтвердить ваше пожертвование." в консоли ошибка:

**Mixed Content: The page at 'https://barrier-free.ru/leyka-process-donation' was loaded over HTTPS, but requested an insecure favicon 'http://barrier-free.ru/wp-content/uploads/2018/09/7726379409_.jpg'. This request has been blocked; the content must be served over HTTPS.**

Затем открывается окно Яндекс.Деньги с надписью "Что-то не так
К сожалению, заплатить этим способом не получится. Пожалуйста, вернитесь и выберите другой способ оплаты." При чем не важно какой платежной системой была попытка оплаты.

**Comment by avdeeva-nataliya** [comment]
Здравствуйте! Вы могли бы поменять ссылку на логотип (на https)?

**Comment by vertjs** [comment]
подскажите пожалуйста, где это нужно сделать? jpg файл, который здесь указан, на самом деле отсутствует

**Comment by avdeeva-nataliya** [comment]
Видимо, где-то в коде страницы есть ссылка на него. Если посмотреть page source https://barrier-free.ru/howtohelp/, то в 168 строке видна ссылка на него.

**Comment by Ahaenor** [comment]
Добрый день!

Проблема в том, что тема вашего сайта выводит фавикон явно с http (и не реагирует, по какому протоколу работает весь остальной сайт).

Проблему можно исправить, например, установив плагин [WP Force SSL](https://ru.wordpress.org/plugins/wp-force-ssl/) или один из его аналогов.

**Comment by vertjs** [comment]
Спасибо за подсказки, исправила фавикон на https вручную, т.к. установка WP Force SSL ни к чему не привела. Визуально ситуация не улучшилась, а в консоли теперь другие 2 ошибки:
**Ресурс на «https://www.tns-counter.ru/V13a****yandex_ru/ru/CP1251/tmsec=yandex_money/882937717» был заблокирован, так как включена блокировка содержимого.**

**Ресурс на «https://ssl.google-analytics.com/ga.js» был заблокирован, так как включена блокировка содержимого.**

**Comment by avdeeva-nataliya** [comment]
Эти ошибки не должны влиять на работу Лейки. Проверьте, пожалуйста, всё ли у вас настроено по инструкциям: https://leyka.te-st.ru/instruction/

**Comment by vertjs** [comment]
Настроено по инструкциям, удалила другие плагины, сменила тему на grassroots - ничего не помогло. Единственное, при смене шаблонов форм, если поставить Рево или Радио - то ошибка меняется со **"Что-то не так"** на **"Слишком маленькая сумма. Пожалуйста, вернитесь в магазин, чтобы выбрать другой способ оплаты или изменить сумму. Операция: 247883cc-000f-5000-a000-12ad72d9815b"** (при чем смена  платежной системы или суммы не меняет ошибки, хоть самую максимальную поставь). Кстати, если выбрать сумму платежа, а потом указать имя, то выделение платежа слетает, добавляется ли сумма в form не понятно (отмечается при любом виде форм).

**Comment by avdeeva-nataliya** [comment]
Пришлите, пожалуйста, на support@te-st.ru учётную запись уровня "Админ" для доступа к сайту.
