### ISSUE TITLE
Ошибка при попытке выполнения рекуррентного платежа при неверной настройке Яндекс.Кассы

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [Teplitsa/Leyka#266]
Привет!

Сайт сбора платежей менял адрес и для этого был заведён новый магазин на Яндекс.Кассе. При настройке Лейки была проверена только работа обычных платежей - казалось, что возможность рекуррентных списаний была включена для этого магазина в Яндекс.Кассе. Но, как теперь выяснилось, не была :)

При попытке проведения рекуррентного платежа в таком случае (в Лейке отмечена галочка "Доступны рекуррентные ежемесячные пожертвования", а Яндекс.Кассой они не разрешены) после нажатия кнопки "Пожертвовать" (шаблон Нео) браузер не перекидывает клиента на другую страницу, но в конце адреса добавляется `#leyka-submit-errors`. Никакой ошибки нет, и поэтому непонятно, что произошло.  

Только через логи Яндекс.Кассы (подключена по API) увидел, что на попытку пожертвовать возвращается JSON такого вида:
```
{
	"type": "error",
	"id": "54a8a492-1d00-43c3-82ef-280000cd6a00",
	"code": "forbidden",
	"description": "Forbidden to save payment method"
}
```  
Наверное, в таких случаях клиенту стоит выводить человекопонятную ошибку о том, что следует обратиться к администратору сайта - возможно она и предусмотрена, но на текущий момент как минимум в шаблоне "Нео" не выводится :)

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо, это хорошее замечание.
Мы постараемся добавить это в будущих обновлениях плагина.

**Comment by Ahaenor** [comment]
Добавлено в бэклог.
