### ISSUE TITLE
Вывести select для выбора назначения

### ISSUE THREAD

**Issue by AlexScop** [Teplitsa/Leyka#267]
Здравствуйте! Скажите, как я могу вывести на страницу Select для выбора назначения платежа? Возможно ли это?

**Comment by Ahaenor** [comment]
Добрый день!

В целом, у каждой кампании предполагается всего 1 назначение платежа.

Чтобы реализовать выбор назначения (или кампании) на форме пожертвования, вам понадобится создать отдельный (кастомный) шаблон формы.

Лейка поддерживает создание собственных шаблонов, независимых от встроенных.
Однако, к сожалению, документации по разработке таких шаблонов ещё нет.
Вы можете взять за основу один из существующих шаблонов форм пожертвований.

Спасибо за обращение!
