### ISSUE TITLE
Личный кабинет

### ISSUE THREAD

**Issue by sagidinov** [Teplitsa/Leyka#269]
Подскажите можно подключать личный кабинет донора по "галочке" при осуществления любого платежа, а рекурсивного оставить как было
Спасибо

**Comment by Ahaenor** [comment]
Добрый день!

В настоящий момент этой функции нет - ЛК донора создаётся только при рекуррентной подписке.
Мы рассматриваем введение этого в будущих версиях плагина - мы учтём ваш запрос.

Спасибо за обращение!
