### ISSUE TITLE
Ошибка при активации плагина.

### ISSUE THREAD

**Issue by 428000** [Teplitsa/Leyka#27]
Fatal error: Invalid opcode 153/1/8. in /pub/home/china4/sags/wp-content/plugins/leyka/inc/leyka-polylang.php on line 199

WP - Версия 4.2.3

**Comment by 428000** [comment]
Ошибки меняются
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 418275321 bytes) in /pub/home/china4/sags/wp-includes/plugin.php on line 882

**Comment by 428000** [comment]
Увеличение памяти не помогает.
тех служба отписалась:
Дорогой Клиент,
Cпасибо за Ваше письмо.

Судя по всему, проблема в плагине, или он не совместим с этой версией вордпресс, так как 256M должно вполне хватить. 

С Уважением,
Компания ValueHost

**Comment by foralien** [comment]
Спасибо, за информацию проверим.
Скажите, ошибка возникает при установке Лейки заново или она уже была устрановлена раньше и это апдейт? Вы устанавливаете ее на "чистый" WordPress или нет. Какую тему (если это готовая тема) вы используете, спасибо.

**Comment by 428000** [comment]
Цикл ошибок был следующий:
php 5.3 - установка нормально. активация ошибка Fatal error: Invalid opcode 153/1/8. in /pub/home/china4/sags/wp-content/plugins/leyka/inc/leyka-polylang.php on line 199
 php 5.4 - установка нормально.  Но при активации ошибка меняется на Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 418275321 bytes) in /pub/home/china4/sags/wp-includes/plugin.php on line 882

Увеличение памяти не помогает.

**Comment by 428000** [comment]
Установка на чистый WP - Версия 4.2.3

**Comment by 428000** [comment]
Тема по умолчанию WP - Версия 4.2.3

**Comment by 428000** [comment]
Жду рекомендаций. Спасибо.

**Comment by DenisCherniatev** [comment]
Занимаемся решением проблемы. О решении сообщим.

**Comment by DenisCherniatev** [comment]
Повторить ошибку при тестах на разных версиях PHP(в связке с apache2) не удалось. Все тесты проводились с ограничениями памяти до 256МБ и прошли успешно. В вашем случае скрипту требуется более 400МБ. Это может быть связано:
1. с особенностями способа запуска PHP
2. с особенностями настройки PHP или расширений PHP на вашем сервере
3. с плагинами WP, которые установлены на сайте
