### ISSUE TITLE
About Payment Form

### ISSUE THREAD

**Issue by zhunus1** [Teplitsa/Leyka#270]
Здравствуйте! Хотел бы добавить дополнительное поле (Ваш номер телефона) под полем Ваш Имэйл. Возможно ли это? Заранее благодарю.

**Comment by avdeeva-nataliya** [comment]
Добрый день! Встроенной возможности нет, вы можете добавить поле с помощью php-разработки (https://github.com/Teplitsa/Leyka/wiki#Кастомизация см. вопрос 2)

**Comment by Ahaenor** [comment]
Вопрос получил ответ, закрываю.
