### ISSUE TITLE
проблема с shoppassword в яндекс кассе

### ISSUE THREAD

**Issue by DenisChuprov** [Teplitsa/Leyka#272]
при подключении яндекс кассы возникла проблема на этапе создания shoppassword. Лейка просит вставить в личном кабинете shoppassword со знаком %, а яндекс касса пишет, что пароль не должен содержать этот знак, что делать?

**Comment by foralien** [comment]
Денис, спасибо за сообщение.

Добавили проблему в бэклог.

Сейчас вы можете придумать свой shopPassword и указать его в Яндекс.Кассе.
После завершения визарда укажите этот shopPassword в настройках
Яндекс.Кассы в админке: Лейка - Настройки - Платежные системы
- Яндекс.Касса.

С уважением, Денис Ч.
служба поддержки
«Теплица социальных технологий»
te-st.ru
https://www.facebook.com/TeplitsaST


сб, 27 июл. 2019 г. в 07:45, DenisChuprov <notifications@github.com>:

**Comment by DenisChuprov** [comment]
скажите, у нас сейчас яндекс касса видит платежи с лейки, а вот лейка не видит, что платеж прошел успешно, может эта проблема быть из-за shopPassword?

**Comment by avdeeva-nataliya** [comment]
Скорее всего, проблема в настройках уведомлений (коллбеках): https://leyka.te-st.ru/faq/#ask10

**Comment by Ahaenor** [comment]
Проблема рассматривается в другом тикете: https://github.com/Teplitsa/Leyka/issues/273
Этот можно закрыть.
