### ISSUE TITLE
leyka-submit-errors

### ISSUE THREAD

**Issue by DenisChuprov** [Teplitsa/Leyka#273]
Доброго дня. Прошу помочь, при попытке пожертвовать любым способом, вылетает ошибка leyka-submit-errors . В чем может быть проблема? Раньше все работало, после обновления перестало.

**Comment by foralien** [comment]
Денис, здравствуйте!

Это происходит при разовом пожертвовании или регулярном, и каким платежным
методом и оператором вы при этом пользуетесь?

В качестве быстрого решения можно откатиться на ту версию Лейки, которая
работала. Вы помните, какая версия Лейки у вас была до обновления?
Вот тут https://wordpress.org/plugins/leyka/advanced/ можно скачать
предыдущие версии.

С уважением, Денис Ч.
служба поддержки
«Теплица социальных технологий»
te-st.ru
https://www.facebook.com/TeplitsaST


пн, 29 июл. 2019 г. в 21:59, DenisChuprov <notifications@github.com>:

**Comment by DenisChuprov** [comment]
яндекс касса, не работает при всех платежах на всех формах. Пытался переустановить лейку и вордпресс - ничего не помогает. Сайт  https://voskreseniye.ru/

**Comment by DenisChuprov** [comment]
недавно был переезд к другму хостеру, у старого хостера была проблема с ssl сертификатом и яндекс касса заворачивала платежи

**Comment by foralien** [comment]
Вероятно, дело в новом хостинге.

Пройдите в админке в раздел "Лейка - Панель управления" и посмотрите, нет
ли красных модулей в секции "Диагностические данные".
Также там указана версия PHP, убедитесь, что она соответствует минимальным
требованиям Лейки.
Для корректной работы плагина необходим PHP версии не ниже 5.6.

Также, если вы отправите нас сообщение из формы обратной связи Лейки, мы
получим больше данных о вашем сервере для диагностирования проблемы.

С уважением, Денис Ч.
служба поддержки
«Теплица социальных технологий»
te-st.ru
https://www.facebook.com/TeplitsaST


вт, 30 июл. 2019 г. в 07:43, DenisChuprov <notifications@github.com>:

**Comment by DenisChuprov** [comment]
Красные ereg, mysql, simplexml, spl
Хостеру писать?

**Comment by foralien** [comment]
Это не критичные недостатки и не должны вызывать такую проблему.

С уважением, Денис Ч.
служба поддержки
«Теплица социальных технологий»
te-st.ru
https://www.facebook.com/TeplitsaST


вт, 30 июл. 2019 г. в 08:30, DenisChuprov <notifications@github.com>:

**Comment by DenisChuprov** [comment]
отправил запрос через админку Вам

**Comment by DenisChuprov** [comment]
Приносим извинения, не тот секретный ключ вводили. Но теперь платежи проходят и яндекс касса их видит, а лейка нет. В разделе пожертвований пусто

**Comment by avdeeva-nataliya** [comment]
Проверьте настройки уведомлений (коллбеки), пожалуйста (https://leyka.te-st.ru/faq/#ask10)

**Comment by Ahaenor** [comment]
Добрый день!

Проблема ещё актуальна?
