### ISSUE TITLE
Ошибка платежа в Я.Кассе

### ISSUE THREAD

**Issue by pionerkaru** [Teplitsa/Leyka#274]
Установлен модуль Яндекс.Кассы для WooCommerce и Лейка. 
Платежи не обрабатываются из-за разных checkUrl и avisoUrl, прописанных в настройках на Я.Кассе. При настройках модуля Я.Касса Woocommerce не работает Лейка, с настройками Лейки не работает модуль Яндекс.Кассы для WooCommerce.

В настройках Я.Кассы прописан `https://сайт-организации.ру/?yandex_money=check`. Возможно ли поставить этот параметр и в Лейке?

Подскажите, пожалуйста, как быть

**Comment by Ahaenor** [comment]
Добрый день!

Это возможно, но точно не средствами Лейки.
Для этого вам понадобится кастомный обработчик хука "parse_request", который должен: 

- распознавать указанный вами адрес как коллбэк Лейки, относящийся к Яндекс.Кассе,
- и выполнять код, который Лейка обычно выполняет при этом.

Но сама описанная вами ситуация кажется нестандартной. Сразу два платёжных модуля на одном сайте, которые работают одновременно - это точно сознательное решение?
