### ISSUE TITLE
Robokassa или другой платежный сервис открыть в новом окне.

### ISSUE THREAD

**Issue by Anton1922** [Teplitsa/Leyka#275]
Добрый вечер! Подскажите, пожалуйста, как сделать, чтобы при нажатии кнопки "пожертвовать", робокасса или другой платежный сервис открывались в новом окне?

**Comment by Ahaenor** [comment]
Добрый день.

Работа плагина не предполагает такой функции.
Более того, это может повредить работе некоторых шаблонов форм и платёжных операторов - они ориентированы именно на редирект пользователя.

Тем не менее, вы можете добиться такого эффекта через добавление на страницу с формой дополнительного CSS или JS-кода, который добавит кнопке отправки пожертвования нужное вам поведение.
