### ISSUE TITLE
Убрать из формы внесения пожертвования  поля с именем и email.

### ISSUE THREAD

**Issue by Anton1922** [Teplitsa/Leyka#276]
И второй вопрос, в каком файле необходимо изменить код, чтобы убрать из формы внесения пожертвования  поля с именем и email?

**Comment by Ahaenor** [comment]
Добрый день.

Работа плагина не предполагает такой функции. Напротив, в данный момент поля имени и email являются обязательными для заполнения - это было намеренным решением на стадии проектирования.

Возможно, в будущих версиях станет возможно сделать поле email необязательным. Но по срокам пока ничего сказать не можем - эта функция только обсуждается.

Чтобы дать возможность выполнять пожертвования без заполнения обязательных полей вам понадобится разработка отдельного ("кастомного") шаблона и обработчика для него.
Такой проект можно, например, заказать какому-либо wordpress-разработчику на коммерческой основе.
