### ISSUE TITLE
Не приходят письма с квитанцией на почту

### ISSUE THREAD

**Issue by Marnotratstvo** [Teplitsa/Leyka#277]
Здравствуйте!
При попытке сделать пожертвование не приходят письма с квитанцией на почту.
Сайт на https.
Для отправки писем чекбоксы установлены.

**Comment by Ahaenor** [comment]
Добрый день.

Вы могли бы рассказать о ситуации подробнее? В частности:

1. Какой у вас сайт?
2. Какой платёжный оператор вы используете для платежа?
3. Письма не приходят при разовом или ежемесячном платеже?
4. Какую "квитанцию" вы имеете в виду?

**Comment by Marnotratstvo** [comment]
Сайт на wordpress
Способ платежа: - Банковская платёжная квитанция. Нажимаем - "Пожертвовать".  Открывается страница с квитанцией и есть кнопка: "Ок, я получил(-а) квитанцию". Но ничего не приходит.
Разовый платеж.

**Comment by Ahaenor** [comment]
Ок, спасибо за уточнение.

"Банковские квитанции" - нестандартный способ оплаты, поскольку выдать донору квитанцию ещё не значит, что он реально выполнит оплату по ней.

Поэтому при попытке "платежа по квитанции" Лейка создаёт пожертвование, но не выполняет автоматического перевода этого пожертвования в статус "оплачено" и не отправляет письма-уведомления донору.

Предполагается, что НКО будет самостоятельно отслеживать платежи, поступившие по квитанциям, и затем переводить соответствующие пожертвования в "оплачено" вручную. Это касается и отправки писем донорам.

Спасибо за обращение!

**Comment by Marnotratstvo** [comment]
Я имею в виду, что донор не получает письма с квитанцией на почту, хотя на кнопке написано, "Ок, я получил(-а) квитанцию"

**Comment by Ahaenor** [comment]
Предполагается, что донор получил квитанцию в браузере)

Ок, мы поняли суть запроса. Мы добавим эту функцию в очередь задач на разработку в будущих версиях Лейки.

Спасибо за обращение ещё раз.
