### ISSUE TITLE
Не отображается список платежных систем

### ISSUE THREAD

**Issue by brokrash** [Teplitsa/Leyka#28]
Установил лейку на вордпресс, не могу настроить платежные системы, не отображается список платежных систем в соответствующей вкладке
скрин http://new.duep42.ru/csr_leyka.jpg

**Comment by DenisCherniatev** [comment]
Проводим проверку.

**Comment by DenisCherniatev** [comment]
Ошибка исправлена. На github выложено обновление. Ожидайте обновление плагина на сайте WP в ближайшее время.
