### ISSUE TITLE
Задвоение платежей

### ISSUE THREAD

**Issue by MihMihich** [Teplitsa/Leyka#281]
Добрый день.

Лейка 3.2. Вордпресс 5.2.2
Заметили, такую вещь, происходят задвоения платежей, каждую минуту происходит пополнение, но при этом реальных денег нет. Смотрите скрин.

![WhatsApp Image 2019-08-18 at 23 19 03](https://user-images.githubusercontent.com/4371715/63568569-fcf3c800-c5b8-11e9-9fc6-e16ef7dab04d.jpeg)
![2019-08-23_15-17-41](https://user-images.githubusercontent.com/4371715/63568593-1c8af080-c5b9-11e9-923a-65c025f69006.png)

В чем может быть причина? Куда копать?

**Comment by Ahaenor** [comment]
Добрый день!

Ок, проблема понятна. Она иногда возникала, если при ответе на коллбэк CloudPayments сайт выдавал ошибку.

В последней версии Лейки (3.3.0.1 и далее) проблема, ориентировочно, исправлена.
Если вы увидите её после обновления, сообщите, пжлст, нам - мы постараемся оперативно исправить.

Спасибо за обращение!
