### ISSUE TITLE
Галочка "Рекуррентный"

### ISSUE THREAD

**Issue by MihMihich** [Teplitsa/Leyka#282]
Добрый день.

Подскажите, а как работает эта галочка и нет ли в ней ошибки.
Делаю кампанию, ставлю галку только "Разовые" платежи, но в форме все равно есть кнопка "Ежемесячно". См. скрин.
![2019-08-23_15-19-07](https://user-images.githubusercontent.com/4371715/63568650-53610680-c5b9-11e9-8ab2-6274631a06ac.png)

Ставлю, убираю галку на рекуррентные, ничего не меняется. Это баг или так должно быть?

**Comment by Ahaenor** [comment]
Добрый день!

На скриншоте шаблон формы "Рево" - на данный момент он не поддерживает ограничение "только разовые/только рекуррентные платежи".

В Рево вариант "ежемесячно" отображается, если у вас доступен хотя бы один способ оплаты с возможностью рекуррентной подписки.

Если убрать ежемесячные платежи для вас принципиально, используйте шаблон "Стар" - он работает так, как вы ожидали.

Спасибо за обращение!
