### ISSUE TITLE
RBK.money рекуррентные платежи

### ISSUE THREAD

**Issue by megagosha** [Teplitsa/Leyka#283]
Я правильно понял, что текущая версия не поддерживает регулярные платежи в этой платежной системе? Можно ли расчитывать на поддержку регулярных платежей в этой платежной системе в будущем?

**Comment by Ahaenor** [comment]
Добрый день!

Да, всё так. Сейчас рекарринг через RBK Money не поддерживается, но мы готовимся к началу работ над этим.

Очень возможно, что в одном из ближайших обновлений плагина рекарринг через этот оператор будет добавлен. Хотя это точно не в ближайшей версии (3.4).

Спасибо за обращение!
