### ISSUE TITLE
В переводе оферты используется отключенный плейсхолдер

### ISSUE THREAD

**Issue by st-sloth** [Teplitsa/Leyka#284]
[В переводе оферты](https://github.com/Teplitsa/Leyka/blob/f8024db19b8f1015e1c6fa350322298055ed31a1/languages/leyka-ru_RU.po#L5395) используется плейсхолдер `#LEGAL_FACE_RP#`, который [закомментирован в хуках](https://github.com/Teplitsa/Leyka/blob/b321912d490177a5806983615ff5d089b270cbb1/inc/leyka-hooks.php#L10), и таким образом в конечном тексте оферты отображается именно плейсхолдер.

**Comment by Ahaenor** [comment]
Ок, спасибо, принято. Мы исправим в ближайшем обновлении плагина.

**Comment by Ahaenor** [comment]
Плейсхолдер был убран в обновлении 3.5.
