### ISSUE TITLE
Импорт электропочты доноров из лейки в UniSender & SendPulse

### ISSUE THREAD

**Issue by stanislavpankov** [Teplitsa/Leyka#288]
Собственно вопрос по теме - каким образом можно автоматически забирать адреса электропочты из лейки в указанные сервисы?
Заранее спасибо за ответ.
Станислав

**Comment by stanislavpankov** [comment]
И после обновления нельзя автоматически выгружать? Тоже надо будет руками?

вт, 1 окт. 2019 г., 15:31 avdeeva-nataliya <notifications@github.com>:

**Comment by avdeeva-nataliya** [comment]
Да, вручную. С csv-файлами работает большинство сервисов рассылок и crm-подобных систем, а делать полноценные интеграции у нас пока нет возможности, т.к. фонды используют слишком много разных инструментов.
