### ISSUE TITLE
не работают комментарии на странице кампаний

### ISSUE THREAD

**Issue by DenisChuprov** [Teplitsa/Leyka#289]
Здравствуйте, я использую на сайте комментарии через плагин AnyComment. На старницах записей комментарии работают, а на страницах кампаний лейки всплывает сообщение "извини, комментарии выключены". Можно ли решить проблему?

**Comment by avdeeva-nataliya** [comment]
Добрый день. Взаимодействие Лейки с другими плагинами не входит в наше соглашение об уровне услуг (https://leyka.te-st.ru/sla/), не сможем помочь с этой проблемой.
