### ISSUE TITLE
Нет стилей когда лейка выводится с помошью шорткода.

### ISSUE THREAD

**Issue by sgarmash** [Teplitsa/Leyka#290]
Здравствуйте! В плагине используется новая тема Стар. Когда я вывожу через шорткод на кастомной странице у меня нет стилей к форме вообще никаких. Но если выведу компанию через меню и перейду по ссылке на страницу со стилями проблем нет. Мне хочется вывести шортод на кастомной странице с вашими стилями. Скажите это возможно или може я что-то упустил?

**Comment by Ahaenor** [comment]
Добрый день!

Это известная ошибка. Она будет исправлена в версии 3.5 (выйдет в ближайшие дни).

В отсутствие фикса мы рекомендуем использовать шорткод leyka_campaign_form (вместо leyka_payment_form) - он работает так же, и не должен иметь проблемы с CSS.

Спасибо за обращение!
