### ISSUE TITLE
Syntax error после обновления версии Wordpress

### ISSUE THREAD

**Issue by Grandspb** [Teplitsa/Leyka#293]
Добрый день! 

Обновил сайт до новой версии WP , после чего плагин невозможно активировать, вот фатальная ошибка: 

Warning: include(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-admin/includes/plugin.php on line 1897

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 91

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 92

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 93

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 94

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 95

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 96

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 97

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 98

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 99

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 100

Warning: require_once(): Unable to allocate memory for pool. in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/leyka.php on line 101

Parse error: syntax error, unexpected '(int)' (int) (T_INT_CAST) in /var/www/spbfavo1/data/www/favor78.ru/wp-content/plugins/leyka/inc/leyka-ajax.php on line 219

 Плагин переустанавливал, но ошибка та же. Если нужны доп. данные, готов предоставить!

прошу помочь в устранении ошибки!

**Comment by Ahaenor** [comment]
Добрый день!

Какая у вас версия Лейки?

**Comment by Grandspb** [comment]
Здравствуйте! Версия 3.5

**Comment by Ahaenor** [comment]
И ошибка возникает даже если выключены все остальные плагины?
Какую тему сайта вы используете?

**Comment by Grandspb** [comment]
Тема Root Версия: 2.3.2? раньше работало все хорошо, пока не обновил версию вордпресс, после ошибки 500 internal server error я отключил все плагины и стал подключать по одному. 

Только Лейка выдала такую ошибку

**Comment by Grandspb** [comment]
Сейчас попробую отключить все плагины и активировать Лейку

**Comment by Grandspb** [comment]
Не помогло - все плагины деактивировал, но ошибка при активации Лейки та же

**Comment by Ahaenor** [comment]
Попробуйте, пожалуйста, переключить тему на любую другую.
Это нужно для диагностики проблемы.

**Comment by Grandspb** [comment]
Хорошо!

**Comment by Grandspb** [comment]
Переключил на другую тему, и снова та же ошибка Лейки ((

**Comment by Ahaenor** [comment]
У вас явно специфический случай. 
Пришлите, пжлст, на почту support@te-st.ru:
 * доступ в админ. раздел сайта уровня "администратор",
 * доступ к файлам сайта по FTP (лучше по SSH).

После завершения наших работ пароли от этих доступов можно (и даже нужно) будет сменить.
