### ISSUE TITLE
Не работают рекуррентные платежи

### ISSUE THREAD

**Issue by donknaze** [Teplitsa/Leyka#294]
Добрый день, коллеги,

Заметил, что не работают рекуррентные платежи.
Яндекс Касса со своей стороны сообщает, что не получает от нас запросов.
Прошу помочь разобраться с этим вопросом. 

Ранее Вы сообщали, что все настроено корректно и исправно работает.

По возможности, прошу ответить срочно.

Благодарю.

**Comment by avdeeva-nataliya** [comment]
Добрый день. Пришлите, пожалуйста, на support@te-st.ru подробности: адрес сайта, как именно не работают (не списываются через месяц? В Лейке при этом отображаются как рекуррентные?)
