### ISSUE TITLE
Не проходят платежи через cloudpayments

### ISSUE THREAD

**Issue by LexDonowan** [Teplitsa/Leyka#295]
Добрый день!
Версия WP 4.9.12, версия лейки 3.5
При отпракве данных карт на сайте, в ответ от _widget.cloudpayments.ru/Payments/Charge_ приходит:
`{"Success":false,"Message":"Неверный номер заказа"}`
В личном кабинете cloudpayments в логах ошибки "Запрос проверки платежа (check)"
`Response: {"code":"10"}`

**Comment by Ahaenor** [comment]
Добрый день!

Как давно появилась эта ошибка?
Были ли ранее примеры успешных (до статуса "оплачено") платежей через СР?

**Comment by LexDonowan** [comment]
Здравствуйте!
Благодарю за ответ, уже решили проблему с помощью поддержки cloudpayments.
Дело было в настройках в личном кабинете cloudpayments.

**Comment by Ahaenor** [comment]
Ок, прекрасно. Спасибо за обращение!
