### ISSUE TITLE
Не получается создать кампанию с рекуррентными платежами

### ISSUE THREAD

**Issue by MariaHague** [Teplitsa/Leyka#296]
Добрый день,

Каждый раз, когда я выбираю в "Какие пожертвования будем принимать"
"Рекуррентные" и обновляю страницу, все настройки возвращаются к только разовым платежам. Подскажите, пожалуйста, как можно это решить?

Спасибо,
Мария
![Opera Snapshot_2019-11-09_200132_xn-----clcjfab0ae9agpzpf xn--p1ai](https://user-images.githubusercontent.com/57572161/68533681-1a207300-032c-11ea-84aa-40e4eafffa9b.png)
![Opera Snapshot_2019-11-09_200011_xn-----clcjfab0ae9agpzpf xn--p1ai](https://user-images.githubusercontent.com/57572161/68533682-1ab90980-032c-11ea-888e-187a2e0422af.png)

**Comment by Ahaenor** [comment]
Добрый день!

Ранее мы не встречали такой проблемы - мы исследуем её и исправим, если нужно.

Для этого пришлите, пожалуйста, на почту support@te-st.ru:
* доступ в админ. раздел сайта (аккаунт уровня "администратор") на почту support@te-st.ru (пароль любой),
* доступ к файлам сайта по FTP (ещё лучше по SSH).
