### ISSUE TITLE
Проблемы на iphone

### ISSUE THREAD

**Issue by Marnotratstvo** [Teplitsa/Leyka#297]
Добрый день!
На iphone не работает форма для пожертвований.
Каждый раз зависает на разных этапах. Пройти дальше выбора оплаты квитанцией/картой не получалось. Чаще всего зависает при попытке указать желаемую сумму перевода.
На других устройствах всё в порядке.
Форма в модальном окне.

**Comment by avdeeva-nataliya** [comment]
Добрый день. Дайте, пожалуйста, ссылку на ваш сайт с формой.

**Comment by Marnotratstvo** [comment]
https://bf.org.ru/campaign/stroitelstvo-ekateriniskogo-hrama-v-g-simferopole/
Проблемы только на iphone

**Comment by avdeeva-nataliya** [comment]
Какая тема у вас используется на сайте? Она стандартная (из репозитория WordPress)?

**Comment by Marnotratstvo** [comment]
Нет, самописная

**Comment by avdeeva-nataliya** [comment]
Мы не гарантируем корректную работу формы с нестандартными темами (https://leyka.te-st.ru/sla/). Можем решить только в рамках платной поддержки.
