### ISSUE TITLE
атака ботов на форму пожертвований danilovcy.ru

### ISSUE THREAD

**Issue by kogan76** [Teplitsa/Leyka#298]
Здравствуйте!
Сегодня целый день идет атака ботов на форму пожертвований, несколько тестовых пожертвований в минуту, плюс реальным жертвователям приходит по 20 писем подтверждений. 
Нам пришлось отключить плагин.
Что нам делать? Помогите пожалуйста!

**Comment by avdeeva-nataliya** [comment]
Михаил, давайте продолжим в почте, чтобы не множить переписки.
