### ISSUE TITLE
Выборка текущих/завершенных кампаний

### ISSUE THREAD

**Issue by danaxy** [Teplitsa/Leyka#299]
Добрый день, подскажите пожалуйста как можно осуществить вывод отдельно действующих и завершенных сборов. Может можно какой то параметр использовать в query_post

текущий код таков:
```
query_posts( array( 'post_type' => 'leyka_campaign', 'posts_per_page' => 6 ) );
while ( have_posts() ) : the_post(); ?>
	<div class="col-lg-4 ">
	<? echo do_shortcode('[leyka_campaign_card id="'.get_the_ID().'" show_finished="0" show_title=1 show_thumb=1 show_excerpt=0 show_scale=1 show_button=0]'); ?>
	</div>
<? endwhile; ?>
```

**Comment by danaxy** [comment]
Похоже у меня получилось. Для архива (завершенных) кампаний:
`
			query_posts( array( 'post_type' => 'leyka_campaign', 'meta_key'     => 'is_finished', 'meta_value'   => 0, 'meta_compare' => '!=','meta_type' => 'NUMERIC' ) );		
			while ( have_posts() ) : the_post(); ?>
			
					
					<div class="col-lg-4 ">
					
						<? echo do_shortcode('[leyka_campaign_card id="'.get_the_ID().'" show_finished="1" show_title=1 show_thumb=1 show_excerpt=0 show_scale=1 show_button=0]'); ?>
							
					</div>
				

			<? endwhile; `?>``
Для текущих кампаний:
`
			query_posts( array( 'post_type' => 'leyka_campaign', 'meta_key'     => 'is_finished', **'meta_value'   => 1**, 'meta_compare' => '!=','meta_type' => 'NUMERIC' ) );		
			while ( have_posts() ) : the_post(); ?>
			
					
					<div class="col-lg-4 ">
					
						<? echo do_shortcode('[leyka_campaign_card id="'.get_the_ID().'" show_finished="1" show_title=1 show_thumb=1 show_excerpt=0 show_scale=1 show_button=0]'); ?>
							
					</div>
				

			<? endwhile; ?>`

**Comment by avdeeva-nataliya** [comment]
Добрый день. Помощь не нужна больше?

**Comment by danaxy** [comment]
> Добрый день. Помощь не нужна больше?

Спасибо, уже нет. Вроде работает. Может решение пригодится кому-нибудь
