### ISSUE TITLE
[Insight] Global variable or function should never be used - in gateways/cp/leyka-class-cp-gateway.php, line 483

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#30]
**[in gateways/cp/leyka-class-cp-gateway.php, line 483](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/gateways/cp/leyka-class-cp-gateway.php#L483)**

> `leyka_add_gateway_cp()` adds to the global scope. Prefer class properties or methods to let other developers know what this relates to.

```php
            ),
        );
    }
}

function leyka_add_gateway_cp() {
    leyka()->add_gateway(Leyka_CP_Gateway::get_instance());
}
add_action('leyka_init_actions', 'leyka_add_gateway_cp');

add_action('wp_enqueue_scripts', 'leyka_enqueue_scripts_cp');
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
