### ISSUE TITLE
Экспорт комментариев в CSV

### ISSUE THREAD

**Issue by barashenkov** [Teplitsa/Leyka#300]
Из списка "Пожертвования" экспортируются все колонки, кроме комментариев. Есть ли возможность как-то реализовать их экспорт? Если нет, то планируется ли такая функция в будущем?

Спасибо!
Антон

**Comment by Ahaenor** [comment]
Добрый день!

Добавить поля в экспорт можно с помощью кода - используя программные фильтры "leyka_donations_export_headers" (для заголовка столбца в excel-таблице) и "leyka_donations_export_line" (для содержимого столбца).

Мы рассмотрим автоматическое добавление поля комментария в будущих релизах, но не можем обещать, что это появится в ближайшем обновлении.

Спасибо за обращение!
