### ISSUE TITLE
Вопрос про стили.

### ISSUE THREAD

**Issue by kulkoff** [Teplitsa/Leyka#301]
Подскажите, а как активируются стили у плагина?
Если добавляю шорткод в запись через редактор,  то все отображается нормально.
Если вставляю в шаблон через echo do_shortcode() , то стили не применяются.

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо, вопрос понятен.

Причина в том, что в случае с **do_shortcode()** решение "подключать стили Лейки или нет" принимается до того, как WP подключает шаблон страницы (в который вставлен вызов do_shortcode()). Поэтому Лейка не может знать, что она должна подключить стили - ей неоткуда узнать об этом на момент принятия ею решения.

Этой проблемы нет, если форма Лейки вставляется через редактор контента. При этом плагин автоматически сканирует контент на предмет "своих" шорткодов, и если они найдены, стили подключаются.

Однако эта проблема решаема. Вот несколько способов:

1. Через код вручную указать Лейке, что на данной странице стили нужно подключать. Для этого можно использовать хук-фильтр **"leyka_modern_template_displayed"** (без параметров, возвращается true/false).

2. Через код, используя хук-экшн **"wp_enqueue_scripts"** и проверяя, что отображается нужная страница.

3. Просто выводить стили Лейки на всех страницах сайта. Для этого нужно в настройках Лейки (раздел "для разработчиков", блок "дополнительно") снять чекбокс "Загрузка скриптов и стилей плагина по необходимости".

Спасибо за обращение!

**Comment by kulkoff** [comment]
Спасибо.
