### ISSUE TITLE
Ошибка Cannot modify header information при подключённом PayPal

### ISSUE THREAD

**Issue by campusboy87** [Teplitsa/Leyka#303]
Здравствуйте.

- WordPress 5.3.2
- PHP 7.1
- Лейка 3.6.1

Выскакивает такая ошибка
```
Cannot modify header information - headers already sent by (output started at ...\wp-content\themes\alive-front\templates\header.php:6)
```

С помощью дебага дошёл до функции `leyka_remembered_data()`. Где-то она используется, где уже выведен html и сработало внутри `setcookie()`. Попробовал на 5 темах (в том числе и дефолтных) - результат один и тот же.

**Comment by Ahaenor** [comment]
Добрый день!

На каких страницах и при каких обстоятельствах можно увидеть эту ошибку?

**Comment by campusboy87** [comment]
Это происходит на главной странице сайта. Пока не разобрался как воспроизвести ошибку, так как поднял тестовый сайт с чистым WP, поставил Query Monitor и Лейку, постарался повторить настройки Лейки как на оригинале, вывел виджет даже - ошибок нет.

На оригинале решил всё сделать с нуля:
- Удалил и перекачал все файлы WP.
- Отключил все плагины, кроме Query Monitor и Лейки;
- Удалил Query Monitor и Лейку, установил заново;
- Проверил все файлы, чтобы были UTF8 без BOM;
- Проверил корректность wp-config.php;
- Проверил наличие must-use плагинов и других вкраплений;
- Установил все дефолтные темы WP и попеременно попробовал.

Ничего не помогло, ошибка осталась.

Занимаясь дебагом дальше, пришёл к следующему:
- `/leyka/gateways/paypal/leyka-class-paypal-gateway.php:1498`
- Метод `localize_js_strings()`
- Используется leyka_get_success_page_url() и так доходит до `setcookie()`
- Если вписать `echo 1111111;` в начале метода `localize_js_strings()`, то единицы выводятся в html сразу после <title>Названия сайта</title>, то есть вот тут и генерируется ошибка, так как `setcookie()` срабатывает, когда уже выведен 1 байт информации.

Пока не понимаю, почему это происходит именно на этом сайте, а на тестовом всё нормально.

**Comment by Ahaenor** [comment]
Спасибо за подробность. Такой ошибки мы ранее не видели - пжлст, держите нас в курсе.

**Comment by Ahaenor** [comment]
Добрый день!

Есть ли какие-то новости по поводу этой проблемы?

**Comment by campusboy87** [comment]
@Ahaenor Здравствуйте. Нет, я пока не разобрался дальше того, о чём писал выше. Займусь этим после сдачи проекта.

**Comment by campusboy87** [comment]
Вернулся к изучение проблемы. Ну тут что сказать, ничего особо не поменялось :-) всё, что рассказал до этого, то могу повторить и сейчас. Хотя попробую другими словами и с новыми знаниями.

#### Проблема возникает при включенном методе оплаты PayPal.
Файл `../leyka/gateways/paypal/leyka-class-paypal-gateway.php:1497`
```
if( ! Leyka_Paypal_All::get_instance()->active ) {
    return;
}
```
То есть, если **PayPal НЕ настроен**, то условие не выполняется и работа метода прерывается - ошибка не возникает.

Если **PayPal настроен**, то метод продолжает выполнятся, добавляет на вывод скрипты доходит до
```
add_filter('leyka_js_localized_strings', array($this, 'localize_js_strings'));
```

В методе `localize_js_strings` выполняется функция `leyka_get_success_page_url()`, которая вызывает `leyka_get_current_template_data()`. Мой случае она возвращает массив:

```
Array
(
    [name] => Toggles
    [description] => Toggled options for each payment method
    [debug_only] => 
    [deprecated] => true
    [file] => F:\server\sites\livefund.edit\wp-content\plugins\leyka/templates/leyka-template-toggles.php
    [basename] => leyka-template-toggles.php
    [id] => toggles
)
``

Далее идёт код:

```
if ( ! empty( $leyka_template_data['id'] ) ) {
    leyka_remembered_data( 'template_id', $leyka_template_data['id'] );
}
```

То есть наряду с первым аргументом (`$name`) передаётся второй аргумент (`$value`), а это значит что `leyka_remembered_data()` это `$value` пытается записать в куку через `setcookie()`.

Так как этот весь процесс происходит в момент вывода скриптов, то есть кода уже часть html выведена на экран, то само собой `setcookie()` генерирует notice.

**Comment by Ahaenor** [comment]
Добавили проверку header_sent(). Проблема более не должна проявляться.
