### ISSUE TITLE
Undefined index: show_total_amount_as

### ISSUE THREAD

**Issue by campusboy87** [Teplitsa/Leyka#304]
Приветствую. Сообщаю об ошибке (уровень notice):
```
Undefined index: show_total_amount_as
```

Происходит при использовании шорткода из [документации](https://leyka.te-st.ru/docs/shortcodes-v-3-6/):
```
[leyka_donations_list campaign_id="0"]
```

Параметр show_total_amount_as в документации не описан, а [в shortcode_atts() закомментирован](https://github.com/Teplitsa/Leyka/blob/master/inc/leyka-shortcodes-new.php#L181), хотя по коду ниже [используется](https://github.com/Teplitsa/Leyka/blob/master/inc/leyka-shortcodes-new.php#L229).

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо за обращение. Мы подтверждаем ошибку, исправим в ближайшем обновлении плагина.
