### ISSUE TITLE
Дополнительное поле

### ISSUE THREAD

**Issue by d-nikolaev** [Teplitsa/Leyka#305]
Хочу добавить дополнительное поле. Как добавить его в шаблоне я нашел. А вот как настроить остальную механику. Отображение в админке, выгрузку csv и т.д. знаний php не хватает. Можете создать механизм для добавления полей или написать инструкцию какие файлы править и участки кода?

**Comment by Ahaenor** [comment]
Добрый день! Ответили в чате телеграма.

**Comment by d-nikolaev** [comment]
Да, спасибо.
