### ISSUE TITLE
Chrome, leyka-submit-errors и проблема с кэшированием

### ISSUE THREAD

**Issue by iwizy** [Teplitsa/Leyka#306]
Добрый день!

Это не баг, а скорее информация для проверки и изучения. В некоторых случаях, когда пользователь пытается пожертвовать, то переброс на страницу Яндекс.Кассы не происходит и вылетает leyka-submit-errors. По моим наблюдениям происходит это в конфигурации, когда также установлен плагин Hummingbird, который отвечает за кэширование сайта. Помогает в настройках кэширования страниц указать страницу, где расположена форма и очистить кэш плагина. Проблему улавливали на Хроме, тот же Сафари прекрасно работает и происходит переход к оплате.

Если найду еще проблемы по вопросу, обязательно отпишусь сюда.

**Comment by Ahaenor** [comment]
Добрый день!

Да, это известная проблема. Точнее, технически это не проблема, а особенность.

В WP есть система контроля уникальности данных форм через "соли" (nonce) - она защищает формы от брутфорса. Использовать её очень рекомендуется самим WP - Лейка (и др. плагины) её, безусловно, используют.

Но побочный эффект - если плагин кэширования (любой) закэширует страницу с формой Лейки, появится описанная вами ошибка. Причина самая логичная - закэшированная страница не уникальна (по определению).

Решение - настроить исключения из кэширования так, чтобы страницы с формами Лейки не попадали в кэш. Обычно это только страницы кампаний, но иногда ещё и другие (зависит от того, где вы выводите форму Лейки).

Мы ищем, как обойти эту проблему более системно. Идеи есть, но это не вопрос ближайших обновлений. В любом случае, спасибо за привлечение внимания к вопросу :)

**Comment by iwizy** [comment]
Спасибо за ответ! Ждем обновлений!
