### ISSUE TITLE
Не работает отправка писем + настройка целей

### ISSUE THREAD

**Issue by dushenina** [Teplitsa/Leyka#307]
Добрый день! 
1. Не работает отправка никаких писем через Лейку, даже в поддержку. Остальные письма через формы сайта приходят. Что это и как исправить?

2. Как настроить регистрацию цели при клике на эту кнопку? Желательно для каждой кампании отдельную цель. 
https://www.screencast.com/t/tAtZ5Vjj

**Comment by avdeeva-nataliya** [comment]
Добрый день! 

1. Уточните версию Лейки, пожалуйста. 
2. Вы можете использовать нашу интеграцию с GA для отслеживания пожертвований: https://leyka.te-st.ru/docs/ga-3-8/
Подойдёт такое решение?

**Comment by dushenina** [comment]
Добрый день! 
1. Лейка 3.8
2. Изучу, спасибо! Вроде бы должно быть ок.

**Comment by avdeeva-nataliya** [comment]
1. А как вы поняли, что письма не работают? Какая-то ошибка выводится? Можете попробовать ещё раз в саппорт отправить?

**Comment by dushenina** [comment]
Я делала оплату и сама же должна получать почту как админ. Нет ни того, ни другого письма. Когда пытаюсь отправить сообщение через форму связи в Лейке то вот: https://www.screencast.com/t/J8HXFCr9Bn

**Comment by avdeeva-nataliya** [comment]
Для диагностики нам понадобятся доступы к сайту. 
Пришлите, пожалуйста, на адрес support@te-st.ru (нужен пользователь уровня «Админ» и доступ к файлам сайта по ssh/ftp).

**Comment by Ahaenor** [comment]
Перешли в почту техн. поддержки.
