### ISSUE TITLE
Как отвязать карту от подписки?

### ISSUE THREAD

**Issue by ostulov** [Teplitsa/Leyka#308]
Добрый день!

Для подключения рекуррентных платежей через Яндекс.Кассу необходимо предоставить скриншот функционала отвязки банковской карты от рекуррентных платежей. 
Где в вашем плагине находится этот функционал?

**Comment by avdeeva-nataliya** [comment]
Добрый день! 
У доноров есть два способа отвязать платежи: 1) через ссылку в письме, которое они получают после оформления рекуррентного платежа 2) через [Личный кабинет](https://leyka.te-st.ru/docs/lk/), если он включен. Обычно пользователям советуем отправить в поддержку Кассы скриншот, на котором виден url сайта и активный чекбокс "Включить личный кабинет доноров".
