### ISSUE TITLE
Ошибка при активации плагина

### ISSUE THREAD

**Issue by glebglebosik** [Teplitsa/Leyka#309]
Вот такая:
Плагин не был активирован, потому что он вызвал фатальную ошибку.
Parse error: syntax error, unexpected '[' in /home/bh51120/public_html/wp-content/plugins/leyka/inc/leyka-functions.php on line 1870

Версия Вордпресса: 5.3.29
Версия ПХП:  5.1.1

**Comment by Ahaenor** [comment]
Добрый день!

Причина проблемы в недостаточной версии PHP.
Для работы Лейки _необходимо иметь PHP 5.6 или выше_ - это официальное требование.
В случае самого ядра WordPress это необязательно, но _крайне_ желательно.

Спасибо за обращение!
