### ISSUE TITLE
Два блока "section--static" в платёжной форме

### ISSUE THREAD

**Issue by kakkoiirus** [Teplitsa/Leyka#312]
В функции toggleStaticPMForm (assets/js/public.js) не предусмотрен случай наличия более одного блока "section--static" в платёжной форме. Например, «mixplat» и «Текстовое сообщение».

При переключении с одного блока с классом "section--static" на другой блок с таким же классом, первый блок не скрывается.

![2020-06-29_16-12](https://user-images.githubusercontent.com/20063991/85997808-718e6300-ba23-11ea-9ec9-03f385aca100.png)

**Comment by Ahaenor** [comment]
Добрый день! Ошибку подтверждаем, она будет исправлена в ближайшем обновлении плагина (v.3.11).
