### ISSUE TITLE
Дубликаты в отчетах.

### ISSUE THREAD

**Issue by ALSupport** [Teplitsa/Leyka#316]
Доброго дня. 
В отчётах о пожертвованиях появилось много дубликатов. Некоторые жертвователи дублируются по 10-15 раз, что сильно усложняет процесс сбора и анализа отчетности. Прошу помочь найти причину поломки и как можно скорее исправить. С такими данными работать не возможно. 
Благодарю.
С ув. Богданов Сергей.
Благотворительный Фонд "Живи Сейчас"

![image](https://user-images.githubusercontent.com/70202496/91162736-287e2680-e6d5-11ea-9ce1-06e20577b6a0.png)
![image](https://user-images.githubusercontent.com/70202496/91162801-4055aa80-e6d5-11ea-891f-777dc41bd245.png)

**Comment by avdeeva-nataliya** [comment]
Добрый день! Записи дублируются только в csv-выгрузках или в интерфейсе (в разделе "Пожертвования") тоже?

**Comment by Ahaenor** [comment]
Добрый день! Ещё вопросы.

1. К какой дате (примерно) относятся дубликаты?
2. Появлялись ли они ранее?

**Comment by ALSupport** [comment]
Записи дублируются и в выгрузках, и в интерфейсе. В период 11-18.08 дублируются регулярные пожертвования.
Проверили июль - там тоже дублируются, но в разные дни.
Вот, например: 13, 24, 27...

**Comment by ALSupport** [comment]
И тишина...

**Comment by Ahaenor** [comment]
Добрый день! Мы ответим подробно, когда доберёмся до вашей заявки. Она в очереди по техн. поддержке.

**Comment by ALSupport** [comment]
Здравствуйте. А там очередь большая? Как долго ждать ответ? Спасибо.

**Comment by Ahaenor** [comment]
Ориентировочно, мы займёмся этим сегодня-завтра.

**Comment by ALSupport** [comment]
:/ Свежо питание...

**Comment by Ahaenor** [comment]
Добрый день!

Мы уже в процессе решения, ищем причину проблемы.

С тех пор есть аналогичные случаи дублей платежей?
Навскидку, мы не видим такого в списке пожертвований.

**Comment by Ahaenor** [comment]
Вы успели удалить дубликаты?
Мы не видим на сайте пожертвований, которые вы привели в скриншотах CSV.

При этом их ID используются, но это пожертвования совсем других доноров, и с ними нет проблем.

**Comment by ALSupport** [comment]
Посмотрели выгрузку за август - до сих пор остались дубляжи, они и в интерфейсе и в выгрузке. Прикладываю скрин.
![Без названия (2)](https://user-images.githubusercontent.com/70202496/93477906-3ace3780-f904-11ea-9de6-3bd7d3defb39.png)

**Comment by ALSupport** [comment]
Ещё недельку подождать?

**Comment by Ahaenor** [comment]
Добрый день.

1. Пришлите, пожалуйста, на почту support@te-st.ru доступы к сайту:
* в админ. раздел - аккаунт уровня "администратор" на почту support@te-st.ru,
* к файлам сайта по FTP либо по SSH,
* в ЛК CloudPayments.

Также для отладки, вероятнее всего, понадобятся более свежие "дубли" - где-то в пределах недели-двух.
Причина - нужно будет найти их в системном журнале СР, чтобы проверить, что сайт отвечает на коллбэки оператора.
Этот журнал, к сожалению, имеет ограниченную длину.

2. Альтернативный вариант поиска причины проблемы - вы можете спросить у техн. поддержки СР детали коллбэков по платежам с указанными ID.
Желаемые сведения:
* когда и сколько раз вызывался коллбэк по нескольким из "дублированных" пожертвований,
* что сайт отвечал на эти коллбэки.

Если выяснится, что это ошибка из-за какого-либо пограничного поведения Лейки, мы, безусловно, исправим её.
