### ISSUE TITLE
Вывод на странице кампаний только с открытым сбором средств.

### ISSUE THREAD

**Issue by Anton1922** [Teplitsa/Leyka#318]
Здравствуйте! Буду очень благодарен за помощь! Я реализовал вывод всех кампаний Лейки на странице по определенному тегу. Но соответственно выводятся кампании и с открытым сбором(сумма не достигнута) средств и с закрытым(сумма достигнута). Как мне сделать вывод только кампаний с открытым сбором? Я так понял, что есть параметр 'campaign_state'. Указываю его, как 'is_open', но результат тот же - выводятся все кампании, вне зависимости от статуса сбора.

**Comment by Ahaenor** [comment]
Добрый день!

При запросе кампаний вам нужно фильтровать их по мета-полю "is_finished".
Если оно задано и имеет значение true (или 1), сбор у соотв. кампании завершён.

**Comment by Anton1922** [comment]
Спасибо! Всё получилось!

вт, 8 сент. 2020 г. в 13:16, Lev Zvyagintsev <notifications@github.com>:
