### ISSUE TITLE
Открытие кампании Лейка через pop-up

### ISSUE THREAD

**Issue by 1totom1** [Teplitsa/Leyka#320]
При открытии формы сбора средств через pop-up, не подгружаются все способы оплаты. 

Пример: "«РОЖДЕСТВЕНСКАЯ ЁЛКА» — СБОР СРЕДСТВ НА ПОДАРКИ ДЛЯ ДЕТЕЙ" https://ruka-pomoshi.ru/kak-pomoch.html 
Используем WordPress 
![image](https://user-images.githubusercontent.com/25531191/96358667-f963be80-1133-11eb-869c-9784fa793348.png)
должно быть так:
![image](https://user-images.githubusercontent.com/25531191/96358693-3d56c380-1134-11eb-9fb1-dc6455c01a3f.png)

**Comment by Ahaenor** [comment]
Добрый день!

У вас используется кастомная страница для пожертвований (она отличается от встроенных страниц кампаний).
Этот способ применения Лейки допустим, но техническая поддержка его не обслуживает.

Мы бы рекомендовали обратиться с этим вопросом к разработчикам, которые реализовали эту страницу на вашем сайте.
Немного вводных данных: способы оплаты во всплыв. окне подгружаются. Но их не видно из-за CSS. Это не проблема  Лейки, а задача для разработчика "формы в поп-апе".

Спасибо за обращение!
