### ISSUE TITLE
Не отображается поле "Комментарии" в разделе пожертвования

### ISSUE THREAD

**Issue by Evgenii-Nikitin** [Teplitsa/Leyka#321]
Добрый вечер! 
Не могли бы помочь с таким вопросом- 
в разделе пожертвования не отображается поле "комментарии", хотя при этом если делать выгрузку файла в таблицу xls, то в файлике комментарии будут. 

Что не так делаю, где-то включается отображение этого поля? 
Благодарю заранее и сердечно за помощь!

**Comment by avdeeva-nataliya** [comment]
Добрый день! Поле не отображается в таблице, комментарий можно увидеть на странице пожертвования.

**Comment by Evgenii-Nikitin** [comment]
На

> Добрый день! Поле не отображается в таблице, комментарий можно увидеть на странице пожертвования.

Наталия, добрый день!
В том то и дело, что на странице пожертвования не отображаются комментарии
![image](https://user-images.githubusercontent.com/73200320/96703232-45fd0300-139b-11eb-9021-2a32890aba67.png)

**Comment by avdeeva-nataliya** [comment]
Я имела ввиду индивидуальную страницу пожертвования (на которую можно попасть, если кликнуть "на Уставную деятельность". В таблице сейчас нельзя вывести.

**Comment by Evgenii-Nikitin** [comment]
Наталья, благодарю вас! 
доброго вам дня
![image](https://user-images.githubusercontent.com/73200320/96705925-93c73a80-139e-11eb-9e96-0639d34eba78.png)
