### ISSUE TITLE
ЮKassa

### ISSUE THREAD

**Issue by putnik** [Teplitsa/Leyka#323]
Яндекс.Касса теперь стала ЮKassa, и произошли изменения в протоколах: поменялся домен API на https://api.yookassa.ru/v3 и код оплаты на `yoo_money`. Как долго будет поддерживаться старая конфигурация, пока непонятно.

**Comment by avdeeva-nataliya** [comment]
Спасибо, внесём изменения.

**Comment by Ahaenor** [comment]
Изменения внесены, они войдут в релиз v3.14.
