### ISSUE TITLE
Type juggling в проверке сигнатуры

### ISSUE THREAD

**Issue by kiriknik** [Teplitsa/Leyka#324]
В коде часто встречается такой кусок (параметры для md5 могут быть разные)
```
$params_signature = md5($response['payment_id'].leyka_options()->opt('mixplat_secret_key'))
```
И далее происходит проверка хеша 
```
if($params_signature != $response['signature'])
```
Из за нечеткого сравнения существует вероятность обойти проверку сигнатуры
Например, если полученный хеш начинается на 0e, а  $response['signature'] мы получаем через json в POST запросе (и можем выставить в 0), то 
```
var_dump(md5("aew")==0);
bool(true)
```

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо за замечание - это разумно. Мы поправим в ближайшем обновлении плагина - проверка будет строгой.

**Comment by kiriknik** [comment]
А можете,когда запатчите, зарегистрировать как адвизу?
https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory
https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/publishing-a-security-advisory

**Comment by Ahaenor** [comment]
Да, ок. Поставить вас там коллаборатором?

**Comment by kiriknik** [comment]
Да,если можно,спасибо)

**Comment by Ahaenor** [comment]
Добавили вас в credits) Спасибо ещё раз.
