### ISSUE TITLE
Result Url

### ISSUE THREAD

**Issue by kajur7** [Teplitsa/Leyka#325]
ДД!
Поясните — эту страницу надо делать самому или её создаст Лейка или Робокасс?
    Result Url – адрес технической страницы, на которую отправляется сообщение от Робокассы об успешном или неуспешном пожертвовании (т.н. коллбек). Это поле должно содержать следующее значение: [http://your-site.ru]/leyka/service/robokassa/response/.
    Метод отсылки данных по Result Url — выберите вариант POST.
Success Url и Fail Url создала Лейка.
Если самому, то просто создать папки в корне и путь до страницы response прописать как url при создании страницы в Вордпресс
СУ!
Админ сайта http://vmeste2020.ru
Александр

**Comment by avdeeva-nataliya** [comment]
Добрый день! 
Страницу делать не надо, это технический адрес, настоящей wp-страницы там не будет. Когда Робокасса будет посылать уведомление на этот адрес, то Лейка его получит.

**Comment by kajur7** [comment]
Спасибо. 💢☺
--
Отправлено из Mail.ru для Android среда, 09 декабря 2020г., 12:38 +03:00 от avdeeva-nataliya  notifications@github.com :
