### ISSUE TITLE
Leyka International

### ISSUE THREAD

**Issue by iasl-github** [Teplitsa/Leyka#327]
Добрый день, уважаемые коллеги и соратники! Международная академия космического права - российская некоммерческая организация, ориентированная на международную аудиторию. Надеемся внести свой вклад в дело укрепления мира и безопасности на планете посредством развития потенциала в области космического права, недопущения милитаризации космоса, снижения конфликтогенности космического пространства. Независимость исследований и разработок, труд профессорско-преподавательского состава и мероприятия общественной дипломатии планируем финансировать за счёт пожертвований как от россиян, так и иностранных граждан и международных организаций. Подскажите, пожалуйста, локализуется ли Лейка в части языка интерфейса под регион (страну) оплаты (внесения пожертвования)? Если да, то данный процесс автоматический или настраиваемый? Реализован ли в платёжной форме мультивалютный ввод с "вшитой" на уровне программного решения конвертацией в рубли и на рублёвый расчётный счёт? Буду признателен за поддержку. С уважением, Артём.

**Comment by avdeeva-nataliya** [comment]
Добрый день! Мультивалютность сейчас не поддерживается в Лейке.

**Comment by iasl-github** [comment]
![Резервная валюта](https://user-images.githubusercontent.com/76431867/106140930-787b8080-6180-11eb-88c3-631534b3130f.png)
Подскажите, пожалуйста, а как работает функционал "резервная валюта". Спасибо!

**Comment by avdeeva-nataliya** [comment]
Это legacy-функциональность, делалась для одной определённой платёжной системы с поддержкой мультивалютности. Давно не тестировалась, скорее всего, сейчас никак не работает.
