### ISSUE TITLE
Не все платежи проходят

### ISSUE THREAD

**Issue by nikonorchiik** [Teplitsa/Leyka#331]
Добрый день! Использую плагин Лейка на сайте благотворительного фонда https://sodeistvieorel.ru/
Платежи проходят через раз. Заполняю данные: почта и фамилия, всё верно, но в виджете отражается строка "данные формы некорректны". Через день приходят жалобы от доноров((

**Comment by avdeeva-nataliya** [comment]
Добрый день! Эта проблема может возникать, если используете плагины для кэширования (подробнее https://leyka.te-st.ru/docs-faq/oshibki/#ask5488). Надо добавить страницу кампании в исключения.
