### ISSUE TITLE
на плагине лейка не работают рекуррентные платежи

### ISSUE THREAD

**Issue by dushamamy** [Teplitsa/Leyka#332]
добрый день. на моем сайте (душамамы.рф) , он на wp установлен плагин лейка и он блокирует возможность проведения рекуррентных платежей. с плагином синхронизирована робокасса, в ее настройках нет ограничений на прием таких платежей. Пожалуйста, помогите исправить это, это очень влияет на фандрайзинговую кампанию.

**Comment by avdeeva-nataliya** [comment]
Добрый день. В Лейке сейчас нет поддержки рекуррентных платежей через Робокассу. Мы планируем её сделать до конца мая.

**Comment by dushamamy** [comment]
Наталья, спасибо! очень ждем!

**Comment by dushamamy** [comment]
А на чем работают уже сейчас?

**Comment by avdeeva-nataliya** [comment]
CloudPayments, ЮKassa, RBKmoney, Chronopay, эквайринг от Сбербанка и Tinkoff.

**Comment by Ahaenor** [comment]
Добрый день. В версии 3.17 в Лейку была добавлена поддержка рекуррентных платежей для Робокассы.

**Comment by dushamamy** [comment]
добрый день! СПАСИБО!

пт, 25 июн. 2021 г. в 13:24, Lev Zvyagintsev ***@***.***>:
