### ISSUE TITLE
Как стать Вашим партнером?

### ISSUE THREAD

**Issue by ckassa** [Teplitsa/Leyka#334]
Здравствуйте.
Вас приветствует онлайн-сервис по приёму безналичных платежей Ckassa.
Подскажите пожалуйста, как стать вашим партнёром и появится в списке платежных систем в продукте "Онлайн-Лейка"?
Какие требования предъявляете к своим партнерам по приему платежей? Какие платежные задачи должны быть решены?
Контакты
моб: + 7 (922) 31 031 27 (WhatsApp, Viber и Telegram)
тел: + 7 (342) 240 40 22
e-mail: makarova-na@ckassa.ru
сайт: www.ckassa.ru

**Comment by avdeeva-nataliya** [comment]
Общаемся в другой переписке.
