### ISSUE TITLE
[Wordpress] Шаблона страницы для компании

### ISSUE THREAD

**Issue by HZ-labs** [Teplitsa/Leyka#336]
Сейчас при использовании компании выбирается шаблон, который перезатирает header.php от сайта на котором установлен.
- Есть ли возможность все же использовать header.php от самого сайта?
- Для этого шаблона что у вас, не хватает <title> https://github.com/Teplitsa/Leyka/blob/4aa3d9f228cfa83da91fe078b302cde7ae7492fa/templates/campaign/type-persistent.php#L46

**Comment by Ahaenor** [comment]
Добрый день!

Этот шаблон используется только для постоянных (persistent) кампаний - в данном случае это сделано намеренно.
Чтобы использовать шапку от сайта, укажите тип кампании "срочная" - тогда будет использоваться шаблон, указанный в теме сайта (в т.ч. включающий header.php).

Насчёт <title> у постоянных кампаний - ок, спасибо, это мы добавим.

**Comment by Ahaenor** [comment]
Добрый день. Мы проверили <title> у постоянных кампаний. В шаблоне вызывается функция wp_head(), в которой вызывается хук-action wp_head. Этот хук выводит в т.ч. <title> - то есть этот тэг должен выводиться, если повесить на этот хук соотв. код.
