### ISSUE TITLE
Не работает кабинет донора

### ISSUE THREAD

**Issue by wycliffesite** [Teplitsa/Leyka#337]
При попытке войти в кабинет или сбросить пароль, начинает крутится анимация, но ничего не происходит. Пробовал отключить все плагины, не помогло. Чистил cookies и заходил с разных устройств, не помогло. 

wycliffe.ru/donor-account
логин: kvaklbrodakl@gmail.com
пароль: vision2025

В консоле пишет:
Uncaught TypeError: $.post(...).done(...).error is not a function
    at HTMLFormElement.<anonymous> (public.js?ver=3.17:442)
    at HTMLFormElement.dispatch (jquery.min.js?ver=3.5.1:2)
    at HTMLFormElement.v.handle (jquery.min.js?ver=3.5.1:2)

Заранее спасибо за помощь!

**Comment by Ahaenor** [comment]
Добрый день!

Проблему видим. Возможно, она не из-за Лейки, а из-за Кандинского, но это необходимо проверить.

Пожалуйста, продублируйте описание проблемы на почту support@te-st.ru.
Также в письме нам понадобится доступ к файлам сайта (по FTP) для диагностики - пришлите его, пожалуйста.

Спасибо за обращение.
