### ISSUE TITLE
После установки и при попытке настройки получаю "Fatal Error" и теряю доступ к консоли сайта

### ISSUE THREAD

**Issue by Dobroreg** [Teplitsa/Leyka#340]
Сайт http://dobroregion.ru/

После установки плагина, при попытке его настройки (конкретно - пункт об отправке данных для улучшения работы плагина, где я выбрал нет), сайт частично ломается и выдает следующую ошибку:

Fatal error: Uncaught Error: Undefined constant "MB_OVERLOAD_STRING" in phar:///home/u3819/dobroregion.ru/WWW/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php:915 Stack trace: #0 phar:///home/u3819/dobroregion.ru/WWW/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php(757): ParagonIE_Sodium_Core_Util::isMbStringOverride() #1 phar:///home/u3819/dobroregion.ru/WWW/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Compat.php(947): ParagonIE_Sodium_Core_Util::strlen('.\x11\x01c\xB3\xC8'\x91\xE3{\xEAV\xB1e\xEB...') #2 phar:///home/u3819/dobroregion.ru/WWW/wp-content/plugins/leyka/bin/sodium-compat.phar/lib/sodium_compat.php(292): ParagonIE_Sodium_Compat::crypto_box_seal('0', '.\x11\x01c\xB3\xC8'\x91\xE3{\xEAV\xB1e\xEB...') #3 /home/u3819/dobroregion.ru/WWW/wp-content/plugins/leyka/inc/leyka-usage-stats-functions.php(43): Sodium\crypto_box_seal('0', '.\x11\x01c\xB3\xC8'\x91\xE3{\xEAV\xB1e\xEB...') #4 /home/u3819/dobroregion.ru/WWW/wp-content/plugins/leyka/inc/leyka-core.php(102): leyka_sync_plugin_stats_option() #5 /home/u3819/dobroregion.ru/WWW/wp-includes/class-wp-hook.php(292): leyka_sync_stats_option('') #6 /home/u3819/dobroregion.ru/WWW/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #7 /home/u3819/dobroregion.ru/WWW/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #8 /home/u3819/dobroregion.ru/WWW/wp-admin/admin.php(175): do_action('admin_init') #9 /home/u3819/dobroregion.ru/WWW/wp-admin/plugins.php(10): require_once('/home/u3819/dob...') #10 {main} thrown in phar:///home/u3819/dobroregion.ru/WWW/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php on line 915
На сайте возникла критическая ошибка. Пожалуйста, проверьте входящие сообщения почты администратора для дальнейших инструкций.
Узнайте больше про решение проблем с WordPress.

В итоге пропадает доступ к консоли. Чтобы его вернуть, приходится удалять плагин через FTP. Сам плагин естественно не работает. 

Как можно решить данную проблему и заставить плагин работать?

**Comment by Ahaenor** [comment]
Добрый день!

Константа MB_OVERLOAD_STRING удалена из PHP [начиная с версии 8.0.0](https://www.php.net/manual/ru/mbstring.constants.php). 

С этой версией плагин в любом случае не тестировался и официально её не поддерживает.
Как следствие, если вы понизите версию PHP до более разумной (например, 7.3), проблема должна исчезнуть.

Спасибо за обращение!

**Comment by Dobroreg** [comment]
Со мной связалась поддержка и решила проблему советом понизить PHP версию с 8.0 до 7.3
