### ISSUE TITLE
тестовый платеж не возвращает текст ошибки

### ISSUE THREAD

**Issue by noxonsu** [Teplitsa/Leyka#342]
![](https://screenshots.wpmix.net/MessageCenterUI_RHvUWXSjZpNjxOf6iVdBGxXTaelmBsXf.png)

**Comment by Ahaenor** [comment]
Добрый день!

Что содержит текст ошибки в аяксе? Как вызвать такую ошибку?

**Comment by noxonsu** [comment]
вот эта похоже https://t.me/leykadev/15818

**Comment by Ahaenor** [comment]
Да, проблема решена в чате.
