### ISSUE TITLE
Проблемы с ежемесячной подпиской на пожертвования

### ISSUE THREAD

**Issue by AlenaDS** [Teplitsa/Leyka#344]
Люди не могут подписаться на ежемесячные пожертвования. Разовый платеж списывается, но подписки на ежемесячный платеж не происходит. Сайт voicesforanimals.ru

Недавно мы поменяли банк (сменили реквизиты). Но в банке платежи проходят, поступают нам на счет. Но регулярно не списываются. 

В чем может быть причина?

**Comment by anabiev** [comment]
Добрый день!

Уточните, пожалуйста, статус платежей — "Оплачено" или "Попытка пожертвовать"?

Если статус "Оплачено", скорее всего ошибка в cron. Проверьте настройки по инструкции: https://leyka.te-st.ru/docs/cronjob/ 

Если статус "Попытка пожертвовать", вероятно, ошибка связана с настройками уведомлений. Проверьте настройки по инструкции в зависимости от платежной системы:

- CloudPayments: https://leyka.te-st.ru/docs/podklyuchenie-cloudpayments/
- ЮKassa: https://leyka.te-st.ru/docs/yookassa/ https://leyka.te-st.ru/docs/yandex-kassa-recurring/
- Сбербанк: https://leyka.te-st.ru/docs/podklyuchenie-sber-acquiring/
- Тинькофф: https://leyka.te-st.ru/docs/tinkoff/
- PayPal: https://leyka.te-st.ru/docs/nastrojka-paypal/
- Робокасса: https://leyka.te-st.ru/docs/podklyuchenie-robokassa/ 
- Хронопей: https://leyka.te-st.ru/docs/chronopay/
- RBKMoney: https://leyka.te-st.ru/docs/podklyuchenie-rbk/

**Comment by Ahaenor** [comment]
Добрый день.

Проблема может быть ещё и в том, что возможность рекуррентных платежей должна быть включена не только в Лейке, но и в Личном кабинете ЮКассы. С этим вам нужно будет обратиться к вашему менеджеру в ЮКассе - ему нужно сказать, что вы хотите подключить регулярные платежи для вашего магазина.
