### ISSUE TITLE
Как удалить поле name на форме оплаты?

### ISSUE THREAD

**Issue by kirill270990** [Teplitsa/Leyka#348]
Здравствуйте, Подскажите а как именно удалить полк name ? Нигде не могу найт ответ. Я пытался поставить required= “false” , но не вышло. может что – то еще нужно? Подскажите, пожалуйста. Заранее спасибо

**Comment by Ahaenor** [comment]
Добрый день. Насколько я понимаю, вам ответили в другой переписке.
