### ISSUE TITLE
[Insight] Global variable or function should never be used - in inc/leyka-admin.php, line 552

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#35]
**[in inc/leyka-admin.php, line 552](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-admin.php#L552)**

> `set_html_content_type()` adds to the global scope. Prefer class properties or methods to let other developers know what this relates to.

```php
        ) {
            die('2');
        }

        if( !function_exists('set_html_content_type') ) {
            function set_html_content_type(){ return 'text/html'; }
        }
        add_filter('wp_mail_content_type', 'set_html_content_type');

        $res = true;
        foreach((array)explode(',', LEYKA_SUPPORT_EMAIL) as $email) {
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
