### ISSUE TITLE
Рекуррентный платеж 

### ISSUE THREAD

**Issue by Xakcc** [Teplitsa/Leyka#354]
Здравствуйте (опять), возник вопрос по поводу рекуррентных платежей, можно ли настроить их в тестовом режиме на выполнение хотя бы раз в час? (а то месяц для тестирования это многовато, хотелось бы сократить время ожидания)

**Comment by Ahaenor** [comment]
Добрый день. Это зависит от того, какой гейт (платёжный оператор) вы используете.

- ЮКасса или другие, требующие cron job: вы можете вызывать скрипт списания по рекуррентам вручную сколько угодно раз за день. Если в Лейке включён режим отладки, рекуррентное пожертвование будет списываться при каждом вызове.
- CloudPayments: рекуррентное списание по активной подписке можно вызвать из ЛК гейта, в настройках подписки.
