### ISSUE TITLE
Рекуррентные подписки в сбербанке сразу становятся неактивными

### ISSUE THREAD

**Issue by byte916** [Teplitsa/Leyka#356]
Пытаюсь создать рекуррентный платёж - деньги снимаются, но сразу после этого мне (как администратору) приходит письмо с ошибкой, а в админке платёж отмечен как не активный
![изображение](https://user-images.githubusercontent.com/1929437/142437082-162896dd-5e95-4328-8062-fc74fe7b2b1e.png)
![изображение](https://user-images.githubusercontent.com/1929437/142437898-0ee9040c-15f6-4acc-ba49-6fce94928014.png)

Общение со сбербанком идёт медленно, на вопрос включены ли рекуррентные платежи они пока что не ответили, зато прислали инструкцию, как оно должно работать под капотом

<details>
<summary>Ответ сбербанка</summary>

 Добрый день.
 
 Подскажите реализована схема работы автоплатежей таким образом:
 
Добрый день.

Подскажите реализована схема работы автоплатежей таким образом:

1. GET запрос register.do на предварительный платеж для создания связки. Обязательно должен быть указан параметр clientID, features=AUTO_PAYMENT не нужен. После оплаты покупателем создается связка.

2. GET запрос getBindings.do для получения ID связки (параметр bindingID в ответе от сервера {"errorCode":"0","errorMessage":"Успешно","bindings":[{"bindingId":"123456ab-cdef-1234-abcd-abcdef012345","maskedPan":"411111XXXXXX1111","expiryDate":"201912"}]} )

3. GET запрос register.do на регистрацию автоплатежа. Обязательно указывается параметр clientID и features=AUTO_PAYMENT. Данный заказ не оплачивается, только регистрируется для последующих списаний в автоматическом режиме. В ответе от сервера получаем параметр mdOrder. ( {"orderId":"012345ab-cdef-0123-4567-89abcdef0123","formUrl":"https://3dsec.sberbank.ru/payment/merchants/sbersafe_cardholder/payment_ru.html?mdOrder=456789ab-cdef-0123-4567-89abcdef0123"} )

4. POST запрос на проведение автоплатежа. В данном запросе используется 4 параметра: логин и пароль -api пользователя, bindingID и mdOrder. Пункты 3-4 используются при каждой последующей регистрации и проведении автоплатежа. Данный функционал требует согласования. Первоначальный платеж для создания связки проходит по 3ds, если не передан параметр FORCE_SSL - Принудительное проведение платежа через SSL (без использования 3-D Secure), документация размещена на ресурсе: https://securepayments.sberbank.ru/wiki/doku.php/integration:api:rest:requests:register Последующие платежи не требуют использования 3ds, алгоритм представлен выше. Пункт "сохранить карту" - на платежной странице не относится к автоплатежам, это возможность покупателя сохранить карту для последующих оплат в любом магазине партнере Сбербанка.
 </details>

**Вопрос:** Может ли это быть ошибка Лейки?

**Comment by anabiev** [comment]
Добрый день!

Уточните, ваше обращение еще актуально? Если да, пожалуйста, продублируйте информацию на нашу почту (help@te-st.ru) и приложите к письму доступы к сайту. Мы все проверим.

**Comment by byte916** [comment]
> Добрый день!
> 
> Уточните, ваше обращение еще актуально? Если да, пожалуйста, продублируйте информацию на нашу почту ([help@te-st.ru](mailto:help@te-st.ru)) и приложите к письму доступы к сайту. Мы все проверим.

Добрый день! Да, проблема актуальна. На почту написал.

**Comment by byte916** [comment]
Проблема была решена.
