### ISSUE TITLE
Фатальная ошибка при установке

### ISSUE THREAD

**Issue by AfricBarmaley** [Teplitsa/Leyka#360]
При первой установке с темой Кандинский все закончилось фатальной ошибкой:
Fatal error: Uncaught Error: Undefined constant "MB_OVERLOAD_STRING" in phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php:915 Stack trace: #0 phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php(757): ParagonIE_Sodium_Core_Util::isMbStringOverride() #1 phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Compat.php(947): ParagonIE_Sodium_Core_Util::strlen('\xF1N\xA8\xDB\xBF\e\x05f\x88\xC5\x08\x84\xAC\x90\x9A...') #2 phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/lib/sodium_compat.php(292): ParagonIE_Sodium_Compat::crypto_box_seal('0', '\xF1N\xA8\xDB\xBF\e\x05f\x88\xC5\x08\x84\xAC\x90\x9A...') #3 /home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/inc/leyka-usage-stats-functions.php(43): Sodium\crypto_box_seal('0', '\xF1N\xA8\xDB\xBF\e\x05f\x88\xC5\x08\x84\xAC\x90\x9A...') #4 /home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/inc/leyka-core.php(121): leyka_sync_plugin_stats_option() #5 /home/c/ca63338/wordpress_1/public_html/wp-includes/class-wp-hook.php(303): leyka_sync_stats_option('') #6 /home/c/ca63338/wordpress_1/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #7 /home/c/ca63338/wordpress_1/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #8 /home/c/ca63338/wordpress_1/public_html/wp-admin/admin.php(175): do_action('admin_init') #9 /home/c/ca63338/wordpress_1/public_html/wp-admin/themes.php(10): require_once('/home/c/ca63338...') #10 {main} thrown in phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php on line 915
Появляется с PHP 8.0, При откате на PHP 7.4 установка завершилась без ошибки.

**Comment by anabiev** [comment]
> При первой установке с темой Кандинский все закончилось фатальной ошибкой: Fatal error: Uncaught Error: Undefined constant "MB_OVERLOAD_STRING" in phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php:915 Stack trace: #0 phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php(757): ParagonIE_Sodium_Core_Util::isMbStringOverride() #1 phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Compat.php(947): ParagonIE_Sodium_Core_Util::strlen('\xF1N\xA8\xDB\xBF\e\x05f\x88\xC5\x08\x84\xAC\x90\x9A...') #2 phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/lib/sodium_compat.php(292): ParagonIE_Sodium_Compat::crypto_box_seal('0', '\xF1N\xA8\xDB\xBF\e\x05f\x88\xC5\x08\x84\xAC\x90\x9A...') #3 /home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/inc/leyka-usage-stats-functions.php(43): Sodium\crypto_box_seal('0', '\xF1N\xA8\xDB\xBF\e\x05f\x88\xC5\x08\x84\xAC\x90\x9A...') #4 /home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/inc/leyka-core.php(121): leyka_sync_plugin_stats_option() #5 /home/c/ca63338/wordpress_1/public_html/wp-includes/class-wp-hook.php(303): leyka_sync_stats_option('') #6 /home/c/ca63338/wordpress_1/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #7 /home/c/ca63338/wordpress_1/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #8 /home/c/ca63338/wordpress_1/public_html/wp-admin/admin.php(175): do_action('admin_init') #9 /home/c/ca63338/wordpress_1/public_html/wp-admin/themes.php(10): require_once('/home/c/ca63338...') #10 {main} thrown in phar:///home/c/ca63338/wordpress_1/public_html/wp-content/plugins/leyka/bin/sodium-compat.phar/src/Core/Util.php on line 915 Появляется с PHP 8.0, При откате на PHP 7.4 установка завершилась без ошибки. 

Добрый день! Пожалуйста, продублируйте ваше обращение нам на help@te-st.ru и приложите к письму доступы к сайту (к админке) и к файлам сайта (FTP). Мы все проверим.
