### ISSUE TITLE
Почему не происходит попытки повторного снятия после ошибки  declinedByTimeout?

### ISSUE THREAD

**Issue by byte916** [Teplitsa/Leyka#361]
Иногда рекуррентные платежи заканчиваются ошибкой  declinedByTimeout.
Логично было бы попробовать провести такие платежи повторно, но таких попыток нет.
Почему?

**Comment by foralien** [comment]
Здравствуйте,

Спасибо за ваше письмо! В связи с
отпусками ожидается замедленная
реакция на ваши сообщения.

Спасибо,

С уважением,

Служба поддержки

Теплица социальных технологий

**Comment by anabiev** [comment]
> Иногда рекуррентные платежи заканчиваются ошибкой declinedByTimeout. Логично было бы попробовать провести такие платежи повторно, но таких попыток нет. Почему?

Добрый день! Пожалуйста, продублируйте ваше обращение нам на почту help@te-st.ru, а также уточните в письме сколько всего пожертвований и как часто воспроизводится эта ошибка. По возможности приложите к письму доступы к сайту. Мы все проверим.
