### ISSUE TITLE
the plugin does not work

### ISSUE THREAD

**Issue by egorov79** [Teplitsa/Leyka#362]
It gives errors when activated
https://ru.wordpress.org/plugins/leyka/

**Comment by Ahaenor** [comment]
Hello.

1. What errors exactly?
2. Please check your PHP & Wordpress version against the plugin requirements (PHP >= 5.6, Wordpress core >= 3.6.1).

**Comment by egorov79** [comment]
Everything has already been fixed-- С Уважением, Николай Николаевич +79042159385 ***@***.***, 22:57, "Lev Zvyagintsev" ***@***.***>:
Hello.

What errors exactly?
Please check your PHP & Wordpress version against the plugin requirements (PHP >= 5.6, Wordpress core >= 3.6.1).
