### ISSUE TITLE
Rename placeholders

### ISSUE THREAD

**Issue by Vladimir-srgv** [Teplitsa/Leyka#365]
Добрый день, подскажите, можно ли как-то переименовать поля формы "Стар", в частности интересует поле "Имя и фамилия", хотелось бы переименовать в просто "Имя". У меня удалось это сделать через функцию $translated, но может есть более правильное решение?

**Comment by Ahaenor** [comment]
Добрый день!

Изменить название поля имени донора на форме можно с помощью хука-фильтра "leyka_star_donor_name_field_label". Фильтр принимает 2 аргумента - саму строку названия поля (которое вы хотите изменить) и кампанию, форма которой выводится.
