### ISSUE TITLE
Добавить возможность одновременной работы нескольких интеграций Cloudpayments с одного сайта

### ISSUE THREAD

**Issue by Bigmanekb** [Teplitsa/Leyka#368]
С одного сайта на Wordpress необходимо отправлять платежи для нескольких public_id от Cloudpayments

Но интеграция только одна и поле ввода настроек piblic_id тоже только одно. Соответственно в текущей реализации нет возможности использовать разные настройки для отправки платежей для разных назначений.

**Comment by anabiev** [comment]
Добрый день!

Сейчас такой возможности нет. Для того, чтобы мы могли добавить такой функционал, нам нужно понять, в каких условиях должны использоваться различные значения public ID — например, в зависимости от кампании, или от типа платежа (разовые/рекуррентные).

Пожалуйста, продублируйте ваш запрос нам на почту help@te-st.ru и опишите подробнее условия, в которых должны использоваться различные значения public ID.
