### ISSUE TITLE
[Insight] Global variable or function should never be used - in inc/leyka-class-donation.php, line 74

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#37]
**[in inc/leyka-class-donation.php, line 74](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-class-donation.php#L74)**

> `$current_screen` adds to the global scope. Prefer class properties or methods to let other developers know what this relates to.

```php
        return $messages;
    }

    public function row_actions($actions, $donation) {

        global $current_screen;

        if( !$current_screen || !is_object($current_screen) || $current_screen->post_type != self::$post_type ) {
            return $actions;
        }

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
