### ISSUE TITLE
Здравствуйте! Как добавить в форму возможность подкрепления файла(Картинки)?

### ISSUE THREAD

**Issue by Badretdinov-badrik** [Teplitsa/Leyka#370]
Здравствуйте, хочу подключить ваш плагин на сайт, но столкнулся с проблемой, что у вас нет возможности добавить Прикрепленный файл в форму, как это можно решить?

**Comment by anabiev** [comment]
Добрый день! 

Пожалуйста, расскажите подробнее в письме на нашу почту help@te-st.ru, какой именно функционал вы хотите реализовать.
