### ISSUE TITLE
Не хватает полей в экспорте в csv

### ISSUE THREAD

**Issue by Arsennikum** [Teplitsa/Leyka#372]
Добрый день!
При экспорте пожертвований в csv не хватает полей, которые есть на основной странице пожертвований
![изображение](https://user-images.githubusercontent.com/15987480/164892612-e9ec47f1-bd49-46de-9afb-93070e13f24c.png)
В csv экспортируются только эти поля
![изображение](https://user-images.githubusercontent.com/15987480/164892632-d7cb89ba-82d6-4ea8-9174-8012e090dc8b.png)

Вижу здесь, что колонки жестко заданы 
https://github.com/Teplitsa/Leyka/blob/a5a568c3ba9004902a6758083f012651850342a2/inc/admin-lists/leyka-class-donors-list-table.php#L842

Очень нужны поля телефон, дата рождения, комментарий, можно их добавить или сделать настройку выбора полей для экспорта?

**Comment by Ahaenor** [comment]
Добрый день!

Да, мы уже приняли этот баг в работу. Собственно, фикс уже в ветке master.
В публичный код исправление попадёт с ближайшим релизом (3.26).

**Comment by Arsennikum** [comment]
@Ahaenor Супер, спасибо!!
