### ISSUE TITLE
Лейка перестала принимать пожертвования. 

### ISSUE THREAD

**Issue by anoapparel** [Teplitsa/Leyka#373]
![2022-04-26_16-33-17](https://user-images.githubusercontent.com/104442894/165318079-488255b8-b25f-464a-9984-f37ef5e6f6bd.jpg)

Пишет вот такое!

**Comment by anabiev** [comment]
Добрый день!

Пожалуйста, уточните, какая платежная система? Не обращались еще к ним в поддержку?
