### ISSUE TITLE
Конкретизировать текст ошибки в эксепшне (Invalid description value)

### ISSUE THREAD

**Issue by rodion-m** [Teplitsa/Leyka#375]
Обновите, пожалуйста, текст ошибки в случае если указано слишком длинное назначение платежа:
```php
            if ($length > Payment::MAX_LENGTH_DESCRIPTION) {
                throw new InvalidPropertyValueException(
                    'Invalid description value', 0, 'CreatePaymentRequest.description', $value
                );
            }
```
С `'Invalid description value'` на `'Description cannot be longer than ' . Payment::MAX_LENGTH_DESCRIPTION`. Так сразу понятно в чем проблема.
Вот тут:
https://github.com/Teplitsa/Leyka/blob/19649e847e938bb198acf30e37f5b6144c31f479/gateways/yandex/lib/Model/Payment.php#L305

**Comment by Ahaenor** [comment]
Добрый день! К сожалению, это не наш код - это SDK ЮКассы. Мы не можем вмешиваться в него - даже чтобы сделать что-то лучше.

**Comment by rodion-m** [comment]
@Ahaenor Да, действительно, это часть SDK ЮКассы. Я проверил и оказалось, что в актуальной версии SDK они конкретизировали текст ошибки: https://git.yoomoney.ru/projects/SDK/repos/yookassa-sdk-php/browse/lib/Model/Payment.php#322 \
Обновите, пожалуйста, SDK ЮКассы в лейке. Можно открыть issue и переименовать ее в "Обновить SDK ЮКассы".
