### ISSUE TITLE
Интеграция с WordPress: проблема с отображением страницы об успешном платеже

### ISSUE THREAD

**Issue by knst-kotov** [Teplitsa/Leyka#378]
После платежа через Лейку страница с сообщением об успешном пожертвовании отображается с нарушением форматирования, без заголовка стандартной темы сайта. Аналогичная проблема с отображением страницы об ошибке при оплате

Лейка 3.25
Шаблон по умолчанию Стар
PHP 7.4.15
WordPress 5.9.3
Протокол: HTTPS
Тема Twenty Twenty-One Версия: 1.5

![Снимок экрана от 2022-05-21 10-27-06](https://user-images.githubusercontent.com/84069574/169641407-ecbc05c0-858d-4776-9fbd-9c68faf9cd77.png)
![Снимок экрана от 2022-05-21 10-17-41](https://user-images.githubusercontent.com/84069574/169641424-4d1a40c4-e6de-4374-a6c9-5e16757ece9a.png)

**Comment by anabiev** [comment]
Добрый день! 

Пожалуйста, продублируйте ваше обращение на нашу почту help@te-st.ru и приложите к письму доступы к сайту. Мы все проверим.
