### ISSUE TITLE
[Insight] Global variable or function should never be used - in inc/leyka-class-donation.php, line 118

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#38]
**[in inc/leyka-class-donation.php, line 118](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-class-donation.php#L118)**

> `$pagenow` adds to the global scope. Prefer class properties or methods to let other developers know what this relates to.

```php
        }
    }

    public function manage_filters() {

        global $pagenow;

        if(
            $pagenow == 'edit.php' &&
            isset($_GET['post_type']) &&
            $_GET['post_type'] == self::$post_type &&
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено в 2.2.8.
