### ISSUE TITLE
Лейка не добавляет доп поля в платежку для сбера

### ISSUE THREAD

**Issue by ChupakabraMSK** [Teplitsa/Leyka#381]
Добрый день, доп поля добавили в платежную форму - это супер - но в платежку для сбера они не добавляются, да и те что естьт сокращаются. А для полит партий это очень критично.

http://yabloko-donate.ru/campaign/test-priema-pozhertvovanij-politicheskoj-partii/

![Uploading Screenshot_4.jpg…]()

**Comment by ChupakabraMSK** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/88263306/174245224-098940b8-9724-4625-847f-f47381cb87bf.jpg)

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за вопрос.

1. Строго говоря, Лейка не "сокращает" поля - она просто не вписывает в квитанции никакие значения доп. полей формы. В поле "ФИО плательщика" всегда идёт полное значение поля "имя и фамилия" (это не доп. поле), а поле "адрес плательщика" донор должен заполнить от руки и сам (даже если на форме есть доп. поле "адрес", квитанция об этом не знает).
2. Добавить такой функционал возможно, это хороший фичреквест. Но мы точно не сможем реализовать его в ближ. месяц-полтора (очень много работы по основному рабочему плану).
3. Если у вас есть PHP/WordPress-разработчики, мы готовы их консультировать и принимать от них pull request-ы. Если нет, вы можете попробовать найти их в чате техн. поддержки Лейки или на нашей платформе [it-волонтёр](//itv.te-st.ru).
