### ISSUE TITLE
При нажатие на кнопку ничего не происходит(не открываеться форма заполнения карты.)

### ISSUE THREAD

**Issue by Andersone1347** [Teplitsa/Leyka#385]
![photoeditorsdk-export (1)](https://user-images.githubusercontent.com/71489996/180241346-23efce99-db3a-434b-941f-9604ebc94698.png)

**Comment by anabiev** [comment]
Добрый день!

Пожалуйста, продублируйте ваше обращение на нашу почту help@te-st.ru и приложите к письму доступы к сайту (к админке) и к файлам сайта (FTP). Мы все проверим.
