### ISSUE TITLE
Передача данных в DashaMail

### ISSUE THREAD

**Issue by MaximmPachin** [Teplitsa/Leyka#386]
Привет! Подскажите, есть ли у вас возможность интегрировать плагин с сервисом рассылок DashaMail? Чтобы данные о платежах уходили в сервис? У Даши есть API, а также CDP, которая с помощью скрипта позволяет отправлять события (посмотрел страницу и подписался, например).

API: https://dashamail.ru/api/

**Comment by anabiev** [comment]
Добрый день! 

Сейчас такая интеграция не планируется, но мы можем принять pull request, если вы реализуете интеграцию силами своей команды или сторонних разработчиков. 

У нас есть чат поддержки в telegram: https://t.me/leykadev 

Возможно, кто-нибудь из других пользователей будет готов помочь.

**Comment by MaximmPachin** [comment]
Здравствуйте! Супер, спасибо, будем разбираться.

А не подскажите, в какой именно момент нужно отправлять асинхронный запрос
в Дашу? Где именно происходит сбор и сохранение всех данных?

пт, 29 июл. 2022 г. в 18:51, anabiev ***@***.***>:

**Comment by MaximmPachin** [comment]
Или, возможно есть возможность отправлять данные на сторонний API? Как это сделано с Юнисендером
