### ISSUE TITLE
Пожертвования не отображаются в админке

### ISSUE THREAD

**Issue by kostyasud** [Teplitsa/Leyka#387]
Добрый день! Подключили к Лейке эквайринг Сбера. Сами платежи проходят успешно, но почему-то после платежи не отображаются в админке, а людям, сделавшим пожертвования, не приходят оповещения об успешном платеже (только от банка). Подскажите, пожалуйста, как это исправить?

**Comment by anabiev** [comment]
Добрый день! Подскажите, статус пожертвований — "Попытка пожертвовать" или платежи совсем не отображаются в списке пожертвований? Если платежи отображаются с ошибочным статусом, вероятно, Лейка не получает данных по итоговому статусу платежа. Это может быть связано с ошибками в настройках — чтобы это исправить, необходимо в личном кабинете Сбера через форму связи с поддержкой попросить указать адрес callback-уведомления — значение «https://your-site.org/leyka/service/sber/process» (вместо your-site.org подставьте адрес вашего сайта).

Если это не поможет или пожертвования совсем не отображаются в админке, пожалуйста, продублируйте ваше обращение на нашу почту help@te-st.ru и приложите к письму доступы к сайту (к админке) и к файлам сайта (FTP)

**Comment by kostyasud** [comment]
Большое спасибо за обратную связь! Выяснилось, что не подгружалась страница "Спасибо", теперь всё работает. Спасибо!
