### ISSUE TITLE
[Insight] Global variable or function should never be used - in inc/leyka-class-options-controller.php, line 20

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#39]
**[in inc/leyka-class-options-controller.php, line 20](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-class-options-controller.php#L20)**

> `$options_meta` adds to the global scope. Prefer class properties or methods to let other developers know what this relates to.

```php

    private function __construct() {

        require_once(LEYKA_PLUGIN_DIR.'inc/leyka-options-meta.php');

        global $options_meta;

        foreach($options_meta as $name => &$data) {

            $data['value'] = get_option("leyka_$name");

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
