### ISSUE TITLE
Не работаю платежи, не отображаются суммы

### ISSUE THREAD

**Issue by nikonorchiik** [Teplitsa/Leyka#394]
Добрый день! Сайт https://sodeistvieorel.ru/
Пользователи начали жаловаться, что не проходят платежи. Хотела сейчас проверить. Но не отображается выбор/ввод суммы. Помогите, пожалуйста 
![Screenshot1](https://user-images.githubusercontent.com/82496695/193657265-fd1c8443-3479-46e9-9691-680d47a0c03e.png)

**Comment by avdeeva-nataliya** [comment]
Добрый день! Попробуйте, пожалуйста, переустановить плагин (деактивировать, удалить и поставить заново).

**Comment by alex-pobeditel-2004** [comment]
Проблема замечена также на сайте https://help.mmdc.ru/campaign/help/ - началось после обновления на версию 3.29.  
Вот, что выводится в консоли JS при нажатии кнопки "Подарить" (пожертвовать):  
![изображение](https://user-images.githubusercontent.com/14791483/194015409-501458dc-97c4-41ea-9994-996392a370b9.png)
Чуть позже попробуем переустановить плагин.

**Comment by alex-pobeditel-2004** [comment]
Откат плагина на 3.28, а потом установка 3.29 заново решили проблему 👍

**Comment by avdeeva-nataliya** [comment]
Отлично!
