### ISSUE TITLE
Не работает платежная форма

### ISSUE THREAD

**Issue by direktorik** [Teplitsa/Leyka#396]
Здравствуйте! У нас школьный сайт на wordpress 6.0.3, темы "Hestia". При нажатие на кнопку "пожертвовать" (на странице кампании) попадаем на платежную форму и на мгновение появляются сверху формы суммы для выбора пожертвований (как и должно быть) и пропадают. При вбивании e mail, фио и проставления галочек соглашений, кнопка "пожертвовать" вообще не работает. Пробовал отключать различные плагины - эффекта ноль. Вот страница пожертвований https://artschool-ptz.ru/dobrovolnye-pozhertvovanija/

**Comment by foralien** [comment]
Здравствуйте!
Скажите, а вы пробовали переустановить плагин?

Ниже пошаговая инструкция, обратите внимание на пункт 4.

ИНСТРУКЦИЯ ПО ПЕРЕУСТАНОВКЕ ЛЕЙКИ

	*
Плагины &gt;&gt; Установленные &gt;&gt; Лейка

	*
Зайдите в настройки Лейки 

 https://lh6.googleusercontent.com/6vbZUuzJbIYRuCcF01aJMgRKh9O6xO8x2ta95nhwJKU8aV22E4WOt7U1XDaSvVXVkDGnkKCq3kiThNzjDgZa4tNMcvOYTLp54qO1WF-6LREfzndxDaqXzCI2tafHWgOEiZSMd3aQCS7eBeA5-BGEDmy3RG1ZURJf-zseUTXFp9NBxEljhd9mmuHHYw

	*
Зайдите в Тех.настройки

 https://lh4.googleusercontent.com/lOG2BI9zerI5MPravb9ZfK3UsO8TtPsyj41HdC0jIq0k_MmUAXWVhR8vRj76ASDaLQ-1WlztZWXZMxeEagSQY9zOFUERNnhjRCUrpjP4KEGjSY5eW6CUdCqKciAfom9f8cEhgHfaRDGiOWovgL2t79Chha8Q5NC2TtNEybygwtt_B2_vteFV1AS7cA

 

	*
Внизу страницы - раздел “Удаление данных плагина” - чтобы данные не были удалены, галочки НЕ должны стоять в обоих пунктах

 https://lh5.googleusercontent.com/xmqTaFfPZoDIJ6GIh7NsXFsnOPT6bl-pgrq3DBbWe3fmgTgNLIa5DUhsiY2GxPVocj2a5B9pdURAUqnG_Roa5XTxdsCFnjeWVdWuZnZxvfOIL45gBcJ8BPvnILG_821YXXYUYkc2AJk5UDl_q0MbMoCxEDCgDI6WYbKB9xn-w7MNdEddyRFSFg3DzQ

 

	*
Если вы внесли изменения, нажмите “сохранить”.

	*
Вернитесь к списку плагинов. Нажмите “деактивировать Лейку”, потом “удалить Лейку”. 

 

* Всплывающее при удалении окно-предупреждение о том, что данные не сохранятся - автоматическое уведомление Wordpress. Если галочки в тех.настройках не стоят, они сохранятся. 

7. Установите Лейку. 


--

С уважением,
Elena Yarmanova

Support manager

Служба поддержки
Теплица социальных технологий
https://te-st.ru
-----------------------------------------------------------
## Teplitsa/Leyka, on Oct 25 @ 12:16 (Etc/GMT-3): 
Здравствуйте! У нас школьный сайт на wordpress 6.0.3, темы &quot;Hestia&quot;. При нажатие на кнопку &quot;пожертвовать&quot; (на странице кампании) попадаем на платежную форму и на мгновение появляются сверху формы суммы для выбора пожертвований (как и должно быть) и пропадают. При вбивании e mail, фио и проставления галочек соглашений, кнопка &quot;пожертвовать&quot; вообще не работает. Пробовал отключать различные плагины - эффекта ноль. Вот страница пожертвований https://artschool-ptz.ru/dobrovolnye-pozhertvovanija/

**Comment by direktorik** [comment]
Спасибо огромное! Переустановка помогла.
