### ISSUE TITLE
Плагин вордпресс не получил обновление коммита от 30 сентября

### ISSUE THREAD

**Issue by akon1982** [Teplitsa/Leyka#398]
Плагин на нашем сайте, видимо, автоматически 29 сентября обновился до последней версии. Но в ней была ошибка - в форме пожертвования не появлялся блок с суммой пожертвования. Насколько я понимаю, коммит от 30 сентября исправил эту ошибку. Но на сайт обновление не пришло. Может, потому, что не поменялся номер версии плагина, не знаю.

**Comment by Ahaenor** [comment]
Добрый день!

Да, это известная проблема. Для решения деактивируйте плагин, удалите его, а затем заново установите и активируйте.
Данные настроек, кампаний и пожертвований при этом будут незатронуты.
