### ISSUE TITLE
unisender

### ISSUE THREAD

**Issue by serobabov** [Teplitsa/Leyka#399]
Здравствуйте, подключили к модулю Лейки сервис unisender. Подскажите как в unisender передавать данные о пожертвованиях: разовое, реккурентное, отписался от пожертвований? сейчас все доноры туда попадают только с данными имя и почта и не получается из-за этого настроить для разных событий соответствующие цепочки писем. Спасибо.

**Comment by foralien** [comment]
Здравствуйте!

Добавить дополнительные поля можно по инструкции из п.3: https://leyka.te-st.ru/docs/unisender/ [https://leyka.te-st.ru/docs/unisender/] (обратите внимание, что чтобы зайти на сайт вам понадобится VPN).


--

С уважением,
Elena Yarmanova

Support manager

Служба поддержки
Теплица социальных технологий
https://te-st.ru
-----------------------------------------------------------
## Teplitsa/Leyka, on Nov 8 @ 11:25 (Etc/GMT-3): 
Здравствуйте, подключили к модулю Лейки сервис unisender. Подскажите как в unisender передавать данные о пожертвованиях: разовое, реккурентное, отписался от пожертвований? сейчас все доноры туда попадают только с данными имя и почта и не получается из-за этого настроить для разных событий соответствующие цепочки писем. Спасибо.
