### ISSUE TITLE
Не поддерживается локализация даты

### ISSUE THREAD

**Issue by SahDoum** [Teplitsa/Leyka#408]
Например, в этом месте:

https://github.com/Teplitsa/Leyka/blob/master/inc/donations/leyka-class-donation-post.php#L414

можно написать что-то в духе:
```
$date_format = get_option('date_format');
$date_format_localise = date_i18n( $date_format ); 
...
date($date_format_localise, $donation_timestamp),
```

**Comment by Ahaenor** [comment]
Спасибо, мы включим фикс для этой проблемы в ближайшее обновление.
