### ISSUE TITLE
Как перенести список пожертвований с одной базы данных в другую?

### ISSUE THREAD

**Issue by Kstein-yandex-ru** [Teplitsa/Leyka#415]
Здравствуйте. Пока обновлял версию темы на тестовом поддомене, на основном сайте сделали много пожертвований.
Как можно с основного текущего сайта перенести весь список пожертвований на поддомен? (Потом поддомен нужно сделать основным сайтом).

Перенес таблицы:

wp_leyka_donations
wp_leyka_donations_meta
wp_postmeta
wp_yoast_indexable

Но не помогло.

**Comment by Ahaenor** [comment]
Добрый день! Мы бы для этого случая рекомендовали перенести не отдельные таблицы, а всю БД целиком. После этого в базе поддомена нужно будет поменять значения URL сайта, а также настройки тестовых подключений к платёжным операторам (если они используются на поддомене).

**Comment by Ahaenor** [comment]
А, понял вас. Тогда вам стоит использовать экспорт пожертвований (как постов WordPress). Это можно сделать через один из специальных плагинов для экспорта/импорта постов.
