### ISSUE TITLE
Не работает фильтрация на странице рекуррентных подписок

### ISSUE THREAD

**Issue by antonlukin** [Teplitsa/Leyka#424]
В последней версии Лейки не работает фильтрация на  странице рекуррентных подписок.
Прикладываю видео:

https://github.com/Teplitsa/Leyka/assets/454185/1aeb42e9-781d-43cc-be69-79905227d989

Проблема кроется здесь: 
https://github.com/Teplitsa/Leyka/blob/master/inc/admin-templates/leyka-admin-recurring-subscriptions-list-page.php#L23
Код изменяет параметры суперглобального массива $_GET, удаляя значение `page`, на основе которого потом формируются ссылки для табов-фильтров здесь:
https://github.com/Teplitsa/Leyka/blob/master/inc/admin-lists/leyka-class-recurring-subscriptions-list-table.php#L547

Мне сложно понять, зачем вообще изменять суперглобальный массив, но в качестве фастфикса, можно заменить $_GET на $_REQUEST в функции вывода табов-фильтров, либо просто вручную прописать этот параметр page в ссылках.

**Comment by BootWP** [comment]
Задача исправлена в версии 3.30.7
https://plugins.trac.wordpress.org/browser/leyka/tags/3.30.7/inc/admin-templates/leyka-admin-recurring-subscriptions-list-page.php#L25
