### ISSUE TITLE
Загрузка плагина

### ISSUE THREAD

**Issue by yuraautsayder** [Teplitsa/Leyka#436]
Добрый день! подскажите, пожалуйста, как можно загрузить и установить плагин? Из wordpress-а он удалён.

**Comment by foralien** [comment]
Добрый день! 

Плагин можно скачать из официальной директории напрямую и установить как обновление: https://downloads.wordpress.org/plugin/leyka.3.31.2.zip



--

С уважением,
Elena .

Support manager

Служба поддержки
Теплица социальных технологий
https://te-st.org
-----------------------------------------------------------
## Teplitsa/Leyka, on Apr 4 @ 00:00 (Etc/GMT-3):
