### ISSUE TITLE
[Insight] Global variable or function should never be used - in inc/leyka-options-meta.php, line 3

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#48]
**[in inc/leyka-options-meta.php, line 3](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-options-meta.php#L3)**

> `$options_meta` adds to the global scope. Prefer class properties or methods to let other developers know what this relates to.

```php
<?php if( !defined('WPINC') ) die;
/** @var $options_meta array An array of initial options set, with default values of each field */
global $options_meta;

$email_placeholders =
"<span class='placeholders-help'>".
"<code>#SITE_NAME#</code> - ".__('a title of the website', 'leyka')."<br/>".
"<code>#ORG_NAME#</code> - ".__('an official title of the organization', 'leyka')."<br/>".
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
