### ISSUE TITLE
[Insight] Global variable or function should never be used - in inc/leyka-polylang.php, line 66

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#49]
**[in inc/leyka-polylang.php, line 66](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-polylang.php#L66)**

> `$polylang` adds to the global scope. Prefer class properties or methods to let other developers know what this relates to.

```php
        // Now donations can return their language (a language of their respective campaigns):
        add_filter('leyka_get_unknown_donation_field', function($value, $field, Leyka_Donation $donation){

            if($field == 'lang' || $field == 'campaign_lang') {

                global $polylang;
                return $polylang->model->get_post_language($donation->campaign_id)->slug;
            }

            return $value;
        }, 10, 4);
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Этот код подразумевает работу с внешним плагином (polylang). Такое обращение к нему корректно, по мнению его авторов. Во всяком случае, никакого синглтона у плагина нет.
