### ISSUE TITLE
[Insight] Error silenced by the at sign (@) - in …/leyka-class-yandex_phyz-gateway.php, line 114

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#60]
**[in gateways/yandex_phyz/leyka-class-yandex_phyz-gateway.php, line 114](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/gateways/yandex_phyz/leyka-class-yandex_phyz-gateway.php#L114)**

> Adding "@" before `$_POST['operation_id']` prevents warning and errors during this function execution from being displayed.
If you need to do that, you should probably implement a better way to qualify and recover from errors, using Exceptions.

```php
        $tech_message = $tech_message ? $tech_message : $message;

        if($is_error) {
            die('<?xml version="1.0" encoding="UTF-8"?><checkOrderResponse performedDatetime="'.date(DATE_ATOM).'"
code="1000" operation_id="'.(int)@$_POST['operation_id'].'"
account_id="'.leyka_options()->opt('yandex_money_account').'"
message="'.$message.'"
techMessage="'.$tech_message.'"/>');
        } else {
            die('<?xml version="1.0" encoding="UTF-8"?>
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
