### ISSUE TITLE
[Insight] Object parameters should be type hinted - in inc/leyka-class-donation.php, line 72

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#61]
**[in inc/leyka-class-donation.php, line 72](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-class-donation.php#L72)**

> The parameter `donation`, which is an object, should be typehinted.

```php
        );

        return $messages;
    }

    public function row_actions($actions, $donation) {

        global $current_screen;

        if( !$current_screen || !is_object($current_screen) || $current_screen->post_type != self::$post_type ) {
            return $actions;
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Испавлено.
