### ISSUE TITLE
[Insight] Object parameters should be type hinted - in inc/leyka-polylang.php, line 6

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#62]
**[in inc/leyka-polylang.php, line 6](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-polylang.php#L6)**

> The parameter `cur_lang`, which is an object, should be typehinted.

```php
<?php if( !defined('WPINC') ) die;

// Polylang  plugin compatibility:
if(defined('POLYLANG_VERSION') && function_exists('pll_register_string')) {

    add_action('pll_language_defined', function($slug, $cur_lang){

//        if($slug != 'en') {
        load_textdomain('leyka', LEYKA_PLUGIN_DIR."lang/leyka-{$cur_lang->locale}.mo");
//        }

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
