### ISSUE TITLE
[Insight] Boolean should be compared strictly - in inc/leyka-class-donation.php, line 421

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#63]
**[in inc/leyka-class-donation.php, line 421](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-class-donation.php#L421)**

> With booleans, only strict comparison (with `===` operator) should be used to lower bug risks and to improve performances.

```php
    }

	public static function get_instance() {

		// If the single instance hasn't been set, set it now.
		if(null == self::$_instance) {
			self::$_instance = new self;
		}

		return self::$_instance;
	}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
