### ISSUE TITLE
[Insight] Commented code should not be committed - in inc/leyka-admin.php, line 439

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#64]
**[in inc/leyka-admin.php, line 439](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-admin.php#L439)**

> Commented out code reduces readability and lowers the code confidence for other developers. If it's common usage for debug, it should not be committed. Using a version control system, such code can be safely removed.

```php
                    <input type="submit" name="<?php echo "leyka_settings_{$current_stage}";?>_submit" value="<?php _e('Save settings', 'leyka'); ?>" class="button-primary" /></p><?php }?></form><!--            --><?php //do_action("leyka_settings_post_{$current_stage}_form");?></div></div><!-- close .wrap --><?php 
	}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено.
