### ISSUE TITLE
[Insight] Unused method, property, variable or parameter - in inc/leyka-core.php, line 434

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#66]
**[in inc/leyka-core.php, line 434](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-core.php#L434)**

> This `network_wide` argument is declared but never used. You should remove it.

```php
    /**
     * Fired when the plugin is deactivated.
     * @param boolean $network_wide True if WPMU superadmin uses "Network Deactivate" action,
     * false if WPMU is disabled or plugin is deactivated on an individual blog.
     */
    public static function deactivate($network_wide) {

        delete_option('leyka_permalinks_flushed');
    }

    function apply_formatting_filters() {
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Оставлено ради совместимости с WP Multisite.
