### ISSUE TITLE
[Insight] Unused method, property, variable or parameter - in inc/…/leyka-settings-payment.php, line 137

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#67]
**[in inc/settings-pages/leyka-settings-payment.php, line 137](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/settings-pages/leyka-settings-payment.php#L137)**

> This `label_backend` argument is declared but never used. You should remove it.

```php
            </div><!-- #pm-settings-wrapper --></div><!-- #active-pm-settings --></div><!-- .active-pm-panel --><?php function leyka_pm_sortable_option_html($is_hidden = false, $full_id = '#FID#', $label = '#L#', $label_backend = '#LB#') {?><li data-pm-id="<?php echo $full_id;?>" class="pm-order" <?php echo !!$is_hidden ? 'style="display:none"' : '';?>><?php //echo $label_backend == $label ? '' : $label_backend.'<br>';?><span class="pm-label" id="pm-label-<?php echo $full_id;?>"><?php echo $label;?></span><span class="pm-label-fields" style="display:none;">
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Оставлю эту переменную на всякий случай. Возможно, пригодится.
