### ISSUE TITLE
[Insight] Unused use statement should be avoided - in inc/excel-writer/Parser/HTMLParser.php, line 5

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#70]
**[in inc/excel-writer/Parser/HTMLParser.php, line 5](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/excel-writer/Parser/HTMLParser.php#L5)**

> The class `SimpleExcel\Exception\SimpleExcelException` is declared but never used. You should remove the `use` statement.

```php
<?php

namespace SimpleExcel\Parser;

use SimpleExcel\Exception\SimpleExcelException;

/**
 * SimpleExcel class for parsing HTML table
 *  
 * @author  Faisalman
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Начиная с версии 2.2.8 неактуально.
