### ISSUE TITLE
[Insight] Usage of a function in loops should be avoided - in inc/leyka-class-campaign.php, line 599

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#71]
**[in inc/leyka-class-campaign.php, line 599](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-class-campaign.php#L599)**

> This loop uses a function. To avoid the overhead of executing the function n times, you should precalculate it before the loop.

```php
            'posts_per_page' => -1,
            'meta_key' => 'leyka_campaign_id',
            'meta_value' => $this->_id,
        ));

        for($i=0; $i<count($donations); $i++) {
            $donations[$i] = new Leyka_Donation($donations[$i]->ID);
        }

        return $donations;
    }
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено в 2.2.8.
