### ISSUE TITLE
[Insight] Usage of a function in loops should be avoided - in inc/leyka-donations-export.php, line 83

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#72]
**[in inc/leyka-donations-export.php, line 83](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-donations-export.php#L83)**

> This loop uses a function. To avoid the overhead of executing the function n times, you should precalculate it before the loop.

```php
            return '"'.str_replace(array(';', '"'), array('', ''), $text).'"';
        }

        $file_lines = array(array('hash', 'Domain', 'Org_name', 'Timestamp', 'Date', 'Email_hash', 'Donor_name hash', 'Sum', 'Currency', 'Gateway_pm', 'Donation_status', 'Campaign_title', 'Campaign_URL', 'Payment_title', 'Target_sum', 'Campaign_target_state', 'Campaign_is_finished'));

        for($i=0; $i<count($file_lines[0]); $i++) {
            $file_lines[0][$i] = prep($file_lines[0][$i]);
        }

        $domain = str_replace(array('http:', 'https:'), '', home_url());

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Исправлено в 2.2.8.
