### ISSUE TITLE
[Insight] PHP classes should be short

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#74]
> 6% of all classes are larger than 500 lines. Split them up to keep less than 5% large classes.

- [**Leyka_Donation_Management** is 1307 lines long](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-class-donation.php#L7)
- [**Leyka_Admin_Setup** is 700 lines long](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-admin.php#L7)
- [**Leyka_Campaign_Management** is 611 lines long](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/leyka-class-campaign.php#L7)

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Противоречит кодо-стилю ВП - и нашему.
