### ISSUE TITLE
[Insight] Interfaces names should end with &quot;Interface&quot; - in inc/excel-writer/Writer/IWriter.php, line 13

### ISSUE THREAD

**Issue by GSuvorov** [Teplitsa/Leyka#82]
**[in inc/excel-writer/Writer/IWriter.php, line 13](https://github.com/Teplitsa/Leyka/blob/5054f2fac1101bd3b0e335bd5f51c3daca68db3f/inc/excel-writer/Writer/IWriter.php#L13)**

> Interface `IWriter` should be named `IWriterInterface` for better clarity.

```php
 * @author  Faisalman
 * @package SimpleExcel
 */

/** define writer interface */
interface IWriter
{
    public function addRow($values);
    public function saveString();
    public function saveFile($filename, $target);
    public function setData($values);
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1f0f68f6-7f18-4286-9b85-7ea0234d5f02/analyses/1)_

**Comment by Ahaenor** [comment]
Отказались от ExcelWriter вообще.
