### ISSUE TITLE
Alexey

### ISSUE THREAD

**Issue by AVert** [Teplitsa/Leyka#84]
все установлено и настроено
но
в итоге:
Ни одна платёжная система не выбрана. Пожалуйста, настройте их.
http://jonang.free-dharma.ru/campaign/komp/#leyka-payment-form

 php -v
PHP 5.4.43-1+deb.sury.org~precise+1 (cli) (built: Jul 15 2015 12:05:17) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by Ahaenor** [comment]
Добрый день.

Вы могли бы предоставить доступ к админ. разделу вашего сайта? Пожалуйста,
вышлите их на ahaenor@gmail.com

1 сентября 2015 г., 0:05 пользователь Alexey Vertinsky <
notifications@github.com> написал:
