### ISSUE TITLE
Роль пользователя: Администратор пожертвований

### ISSUE THREAD

**Issue by nesutulsa** [Teplitsa/Leyka#85]
Коллеги, доброго времени суток. У нас случилась беда такого характера:
Для наших партнеров мы создали отдельный аккаунт для управления системой "Лейка".

Выдали права\роль пользователю "Администратор пожертвований", через определенный промежуток времени, наши друзьям обратились к нам с проблемой, что они не могут производить корректировочные пожертвования через данный тип пользователя.

Не достаточно прав на использование данного функционала.
Как нам правильно поступить? Спасибо.

\\ Делегировать права "full-администратора" для ВордПресса считаем не правильным.
Может мы что-то делаем не так?

**Comment by Ahaenor** [comment]
Добрый день. Ок, спасибо, понял вас. Мы изучим эту проблему.

**Comment by Ahaenor** [comment]
Проблема была исправлена в версии плагина 2.2.8. Закрываю задачу.
