### ISSUE TITLE
Корректировочные платежи

### ISSUE THREAD

**Issue by nesutulsa** [Teplitsa/Leyka#86]
Доброго времени суток, пожалуйста проинспектируйте нас.

Опубликованная компания: Необходима сумма 100 000 - собрано 3400
Поступило 4 платежа:
- 1000 руб = статус *оплачено*
- 300 руб = статус *оплачено*
- 100 руб = статус отправлено
- 1000 руб = статус отправлено

Отчет сформировал нам документ на 1300 рублей, поступивших по факту
А на странице компании у нас отображается 3400

Добавляем "корректировочный платеж" на сумму -2100, платеж формируем со статусом *оплачено* Отрицательную сумму видно, но на странице она не вычитывается.

Затем я удалил корректировочный платеж и эквивалент отрицательной суммы сложился с основной суммой 3400+2100 и мы теперь получаем 5500, а по факту у нас всего 2 платежки на 1300 рублей.

Пытаюсь найти решение этой проблемы, но пока безуспешно. При всем уважении, я постарался перечитать весь мануал и гайд, так же максимально пробить в поисковиках по ключевым.

Буду признателен за наводку или помощь.
Спасибо за ваш труд.

**Comment by Ahaenor** [comment]
Добрый день.

Пожалуйста, укажите адрес вашего сайта и кампании на нём.
Кроме того, нам понадобится:
1. Доступ в админ. раздел сайта (уровня "администратор пожертвований").
2. Доступ к сайту по FTP.

Все эти сведения можно прислать на почту ahaenor@gmail.com

**Comment by BlackGari** [comment]
Абсолютно аналогичная проблема ,как и nesutulsa. 
И к сожалению я не могу предоставить доступ по FTP по причинам корпоративных правил, подскажите где искать и в чем может быть проблема?  
Буду благодарен за ответ!

**Comment by Ahaenor** [comment]
Навскидку, к сожалению, ответить не можем - это первый раз, когда нам
сообщили о такой проблеме.

Мы исследуем ваши случаи подробно и сообщим о результатах.
Ориентировочно, это будет в первых числах октября.

22 сентября 2015 г., 11:38 пользователь BlackGari <notifications@github.com>
написал:

**Comment by GenV** [comment]
У нас также проблемы с корректностью подсчетов платежей. Есть пожертвование на 400 000 р и на 150 000 р. Отражается всего лишь 452 978 р. Никаких минусующих корректировок у нас не было и быть не могло. https://pravobraz.ru/campaign/sbor-sredstv-na-proekt-sozdaniya-edinogo-uchebno-metodicheskogo-komplekta-dlya-voskresnyx-shkol/
Проблема возникла, когда мы внесли корректирующий платеж на 150 000 р. Он отразился в списке пожертвований, но общая сумма не изменилась. Теперь, если убрать этот платеж, сумма упадет до 300 пару тыщ.

**Comment by Ahaenor** [comment]
Добрый день. Ок, спасибо за сообщение.

Вы могли бы создать для меня аккаунт для доступа в админ. раздел вашего сайта?
Почта - моя, уровень доступа "администратор пожертвований".

**Comment by GenV** [comment]
Доступ предоставил

**Comment by Ahaenor** [comment]
Проблема с коррекционными платежами исследована. Она будет исправлена в ближайшей новой версии плагина (2.2.7.3).

Мы понимаем важность этой проблемы и приложим все силы для её исправления. Новая версия плагина выйдет в ближайшее время - максимум в течение след. недели.

**Comment by BlackGari** [comment]
Добрый день! 
Обновление версии плагина до сих пор нет.Может кто то решил эту проблему самостоятельно?

**Comment by Ahaenor** [comment]
Добрый день!

Сейчас проходят последние тесты. Релиз ожидаем сегодня или в понедельник.

Приносим извинения за задержку.
13.11.2015 12:55 пользователь "BlackGari" <notifications@github.com>
написал:

**Comment by nesutulsa** [comment]
Доброго времени суток, скажите пожалуйста, в данный момент решена ли проблема с корректировочными платежами? Планируем подключить плагин повторно.

Спасибо.

**Comment by Ahaenor** [comment]
Добрый день!

Да, проблема была решена в версии 2.2.8.

Приятного пользования, и ещё раз спасибо за обращение.
