### ISSUE TITLE
Совместимость плагинов Leyka и Automatically Paginate Posts

### ISSUE THREAD

**Issue by kenno24** [Teplitsa/Leyka#87]
Добрый день!
На  WordPress 4.3.1 установлен плагин Leyka 2.2.7.2, при установки плагина  Automatically Paginate Posts 0.2 в браузере появляется строка: Warning: in_array() expects parameter 2 to be array, null given in /site.ru/wp-content/plugins/automatically-paginate-posts/automatically-paginate-posts.php on line 361

Как исправить этот конфликт?
Заранее спасибо.

**Comment by Ahaenor** [comment]
Добрый день!

Ок, спасибо за обращение. Мы видим эту ошибку и исправим её в ближайшем официальном релизе.
