### ISSUE TITLE
Необходимо развернуть кампанию на статичной странице.

### ISSUE THREAD

**Issue by lerniri** [Teplitsa/Leyka#88]
День добрый. Ищу помощи у профессионалов ) На сайте есть страница "Пожертвовать" , заведена кампания. Моя задача отображать кампанию + платежную форму на странице "Пожертвовать", а не на странице самой кампании. Подскажите пожалуйста, есть ли такая возможность и какие методы можно подергать.

**Comment by Ahaenor** [comment]
Добрый день!

Для вставки формы пожертвования в произвольную страницу воспользуйтесь шорткодом leyka_payment_form с параметром id, содержащим ID записи-кампании, на которую должны собираться деньги.

Например, для кампании с ID=7: `[leyka_payment_form id="7"]`

**Comment by lerniri** [comment]
Спасибо, огромное - помогло!
