### ISSUE TITLE
Исходный код "Истории пожертвовании"

### ISSUE THREAD

**Issue by mrebenka** [Teplitsa/Leyka#89]
Здравствуйте. Нужен исходный код истории пожертвовании, который высвечивается, на странице компании.

**Comment by Ahaenor** [comment]
Добрый день. Историю пожертвований вы можете выводить в любом месте на сайте с помощью шорткода:
`[leyka_donors_list_screen]`

Параметры:
* id. Может иметь значение "all", чтобы в ленту попадали пожертвования со всех кампаний, или ID определённой кампании, чтобы выводились только пожертвования из неё. По умолчанию "all".
* num. Число пожертвований в ленте.
* show_purpose, show_name, show_date. Группа параметров для настройки того, какие параметры пожертвований будут выводиться в ленте (соотв., вывод цели пожертвования, заголовка кампании и даты пожертвования).

**Comment by mrebenka** [comment]
Извините, но хотелось бы узнать html код, т.к. вливаем все в структуру сайта.

**Comment by Ahaenor** [comment]
Собственно, шорткод будет работать, будучи вставленным в любое место на сайте. Если только мы говорим о сайте, где установлена Лейка.

Если просто скопировать и вставить на другой сайт HTML-код блока истории пожертвований, он не будет отображаться правильно - для этого ему нужны настройки стилей.

Вы могли бы описать ваш случай подробнее? Где вы хотели бы вывести список пожертвований в итоге?

**Comment by mrebenka** [comment]
На сайте установлена Лейка, все верно. Просто страницу с пожертвованием мы создаем в HTML варианте, и вставлять код [leyka_donors_list_screen] бесполезно. Код с формой пожертвовании, нам удалось найти и установить, и она прекрасно функционирует, а вот код истории пожертвовании, снизу формы пожертвовании, к сожалению найти не можем.

**Comment by Ahaenor** [comment]
У вас очень необычный кейс для WordPress)

Я решил бы вашу задачу так. Создайте новую страницу (page), её можно даже не публиковать. В контент страницы вставьте шорткод, который я привёл выше.

После этого откройте страницу в публичной части - должна отобразиться история пожертвований. Её HTML можно скопировать, открыв исходный код страницы.

После получения HTML истории пожертвований страницу можно удалить.

**Comment by mrebenka** [comment]
Спасибо) А если вставлять в отдельный шаблон php вариант, то какой код нужно использовать, чтобы отобразить историю пожертвовании с автоматическим обновлением? Если я правильно понял, то этот код, указанный вами выше, вызывает какую то функцию, т.е. как найти эту функцию, чтобы вставить в шаблон?)

**Comment by Ahaenor** [comment]
Если вы будете использовать отдельный шаблон, то можно просто вставить в
HTML шорткод. Плагин автоматически вызовет все нужные функции.

Или вы можете вызвать функцию `leyka_get_donors_list($campaign_id =
'all', $args
= array())`

Параметр $args содержит пары ключ-значение, совпадающие с аргументами
шорткода, которые я привёл выше.

12 ноября 2015 г., 14:11 пользователь mrebenka <notifications@github.com>
написал:

**Comment by mrebenka** [comment]
спасибо
