### ISSUE TITLE
Интеграция с Робокассой - Неверное значение параметра "SignatureValue"

### ISSUE THREAD

**Issue by lerniri** [Teplitsa/Leyka#90]
Уважаемые девелоперы Лейки, помогите разобраться. Используем лейку на сайте нашего фонда , готовимся к запуску сайта. Для пожертвований берем Робокассу и собственно ваш движок. До момента активации акаунта в робокассе пытаемся погонять пожертвования в тестовом режиме, все настройки были сделаны в соответствии с инструкциями как на сайте робокассы , так и на сайте Лейки. Однако при отправке упорно возникает ошибка не совпадения хэша подписи (SignatureValue). Служба поддержки робокассы категорично заявляет, что подобная ошибка ВСЕГДА возникает на стороне клиента. От себя могу сказать, что пароли перепроверили, перегенерили, идентификатор магазина совпадает, смотрели код лейки - формула расчета подписи соответствует тому , что указано у робокассы, куда еще смотреть честно говоря не понятно. Репортили ли вам подобные случаи и есть ли идеи как это дебажить,  лечить ?

Заранее благодарна!

**Comment by lerniri** [comment]
Немного поковыряв сайт  Робокассы , я нашла у них 2 инструкции по тестированию http://docs.robokassa.ru/#2387 (для тестирования используется продакшен сервер с параметром isTest = 1)   и http://robokassa.ru/ru/DocTest/Ru/Interface.aspx.(для тестирования используется тестовый сервер . Параметр isTest не используется). Как я понимаю, код лейки реализован по второй инструкции - он у меня и не работает. Реализация с использованием параметра isTest работает! В настоящее время я жду ответа от робокассы на тему актуальности тестового сервера (test.robokassa.ru/Index.aspx) . А к вам вопрос - есть ли возможность перезаписать параметры передаваемые в робокассу из вне плагина ? Попыталась поискать правильное решение через заложенные в лейку фильтры, но честно говоря из-за отсутсвия достаточного опыта , не смогла. Прошу помощи.

**Comment by Ahaenor** [comment]
Добрый день! Спасибо за вопрос.

Да, данные, которые передаются Лейкой на Робокассу, можно отфильтровать. Для этого используется фильтр `leyka_submission_form_data-id_вашего_гейтвея`. Параметры фильтра:
 * ассоциативный массив переменных,
 * id способа оплаты (в рамках используемого гейтвея),
 * id нового пожертвования в Лейке.

Вашу фильтрацию нужно вешать на приоритет выше 10.

Пример для Робокассы будет таким:
`
add_filter('leyka_submission_form_data-robokassa', function($payment_vars, $pm_id, $donation_id){
    // какое-то изменение в $payment_vars...

    return $payment_vars;
}, 11, 3);
`

**Comment by Ahaenor** [comment]
Насчёт режима тестирования. Кажется, Робокасса поменяла свой протокол для обращений к тестовому серверу. Когда её поддержка писалась, этого ещё не было.

Это важное замечание - большое спасибо. Изменение войдёт в ближайшую новую версию Лейки.
Сейчас ваша проблема может быть решена с помощью фильтра - вы наметили решение совершенно правильно.

**Comment by lerniri** [comment]
@Ahaenor  спасибо большое, но в $payment_vars нет урла. Я правильно понимаю, что для изменения оного мне надо будет так же добавить фильтрацию leyka_submission_redirect_url-robokassa так же с 11 приоритетом ?

**Comment by Ahaenor** [comment]
Да, всё правильно. $payment_vars - это поля формы, которая отправляется на гейтвей (платёжную систему) при нажатии донора на "пожертвовать".

Для УРЛа, на который происходит эта отправка, фильтр свой.

**Comment by lerniri** [comment]
Спасибо за помощь - все получилось! Закидываю сюда код, вдруг кому будет полезно, пока фикс готовится. Если есть сомнения в правильности имплементации, не держите в себе ) 

<pre>
/*
 *
 * Leyka filters/actions
 * */

add_filter('leyka_submission_form_data-robokassa', function($payment_vars, $pm_id, $donation_id){
	// add isTest parameter
	// 		1: if test mode switch on in leyka options
	// 		0: if test mode switch off in leyka options
	$payment_vars['isTest'] =  leyka_options() -> opt('robokassa_test_mode');
	return $payment_vars;
}, 11, 3);

add_filter('leyka_submission_redirect_url-robokassa', function($current_url, $pm_id){

	// hack to use prod url in test modes. (according to robokassa http://docs.robokassa.ru/#2387)
	return 'https://auth.robokassa.ru/Merchant/Index.aspx';

}, 11, 2);
</pre>

**Comment by Ahaenor** [comment]
:)) Ок. С кодом всё в порядке.
