### ISSUE TITLE
Поддержка периодических платежей - Робокасса

### ISSUE THREAD

**Issue by lerniri** [Teplitsa/Leyka#91]
День добрый. Подскажите, пожалуйста, поддерживает ли Лейка периодические платежи на робокассе (http://docs.robokassa.ru/#1216) и какие планы на разработку ?

Спасибо.

**Comment by Ahaenor** [comment]
Добрый день.

Нет, реализацию рекуррентов в Робокассе убрали из дорожной карты Лейки.

Причины организационные: у РК для этого достаточно высокие требования к контрагенту (т.е. организации, собирающей пожертвования). Например, требовалось, чтобы месячный оборот через РК был не менее 1 млн. руб.

Однаком вы можете добавить приём и обработку рекуррентов в класс гейтвея РК самостоятельно. Технически, это вполне реально.

Разумеется, мы будем благодарны за пулл-реквест.

**Comment by lerniri** [comment]
Спасибо за ответ. Правильно ли я поняла, что РК предоставляет  функционал рекуррентов в зависимости от оборота? То есть в случае оборота меньше 1 млн мы не можем собирать периодические платежи? Прошу прощения за офф топик , но хотелось бы понять ситуацию , раз у вас есть  инфа по теме
Спасибо!

**Comment by Ahaenor** [comment]
Это вполне себе "он-топик" :)

Да, всё верно. При низком обороте (и невыполнении ещё нескольких орг. условий) РК просто не согласится включить для аккаунта рекурренты.

**Comment by Ahaenor** [comment]
Для работы с картами и рекуррентами мы можем рекомендовать CloudPayments. Кроме того, Лейка поддерживает их для Chronopay.

Ещё техническая возможность есть для РБК и Яндекс.денег, но поддержка этого в плагине не реализована.

**Comment by lerniri** [comment]
@Ahaenor  , решили перейти на Chronopay. В процессе интеграции выяснилось, что они предоставляют 2 вида работы с рекуррентными платежами (далее цитатой:)

1) Работы осуществляются через "payments". Это самый простой и часто используемый способ осуществлять ежемесячные списания. В данном случае от Вас требуется направить менеджеру информацию о том, какие суммы Вы желаете списывать за любой период (к примеру 100, 600, 1000 и 3000 рублей). После, мы создаем продукты под каждую сумму и осуществляем все необходимые настройки со своей стороны. С технической стороны нам нужен обычный post запрос. Единственное, что вам нужно будет сделать, это изменить product_id. 

2) Работа через gate. Данный способ является более гибким. Вы сами можете направлять нам запросы с необходимой для вас суммой. Данный способ нуждается в тестировании и предоставится только по предварительному согласованию с нашей компанией. Подробнее данный пункт описан в нашей 
документации Gate API RUS, пункт 4.3 - регулярные платежи. 

Подскажите, какой из них или может быть оба имплементированы в лейке . Имеется ли спецификация функционала.

**Comment by Ahaenor** [comment]
Добрый день!

Наиболее приемлем для вас вариант 1, но с вариативной суммой.

Для этого нужно попросить менеджеров Хронопей создать продукт с ежемесячным списанием средств, но с суммой, определяемой вами (с помощью первого платежа в подписке).

Но при этом сами ежемесячные списания должны выполняться автоматически со стороны Хронопей и сопровождаться вызовом коллбэка.
В отличие от варианта 2, когда вы на стороне сайта сами должны посылать в Хронопей запросы на списания по рекуррентной подписке.
