### ISSUE TITLE
Шорткод не отображается

### ISSUE THREAD

**Issue by mrebenka** [Teplitsa/Leyka#92]
Здравствуйте, вставляю шорткод платежной формы в новую страницу, она не отображается. 
Вот этот шорткод [leyka_payment_form]

**Comment by Ahaenor** [comment]
Добрый день.

Чтобы шорткод платёжной формы работал корректно, необходимо передать в
качестве параметра идентификатор кампании, на которую должны идти платежи
по форме.

Например: [leyka_payment_form id="*идентификатор_кампании*"]

ID кампании можно узнать, если открыть её для редактирования и посмотреть
на адрес страницы. В нём будет параметр post=

*идентификатор_кампании*

18 декабря 2015 г., 11:32 пользователь mrebenka <notifications@github.com>
написал:
