### ISSUE TITLE
Тестирование chronopay callback

### ISSUE THREAD

**Issue by lerniri** [Teplitsa/Leyka#93]
День добрый, уважаемые. 

Столкнулась со следующей проблемой:  
     Лейка не апдейтит статусы отправленых платежей, все платежи застревают в статусе "Отправлен". Хронопей шлет колбеки на заданную url, но лейка безмолствует. Есть ощущение, что код просто не срабатывает.  Не так хорошо разбираюсь в коде лейки, не могу найти точку входа. Может быть вы подскажете какой-нибудь хороший способ подебажить колбек процессинг ? А также, если вам уже известны распространенные проблемы , вызывающие подобные симптомы , поделитесь ) 

Спасибо, 
Ирина

**Comment by Ahaenor** [comment]
Добрый день.

В каждом подклассе Leyka_Gateway (в вашем случае, в Leyka_Chronopay_Gateway) есть метод _handle_service_calls().

Он принимает единственный аргумент - тип коллбэка. Кроме того, он оперирует параметрами из $_POST и отвечает на коллбэки, меняя что-либо в БД, если это необходимо.

Для отладки работы коллбэков нужно будет вступить в диалог с саппортом платёжной системы. От них нужно понимание, какие именно параметры и на какой УРЛ отсылались сайту в коллбэке, и что в точности сайт ответил.

В зависимости от этого вы будете понимать, что именно в коллбэке сработало не так.

**Comment by lerniri** [comment]
С опозданием, но спасибо за ответ - очень помогло. Проблема была в IP адресе , возвращаемом в колбеке. В настройках Лейки у меня был указан IP хронопея, с которым сравнивался айпи колбека и возвращал ошибку, так как они были разные -  хронопей возвращает айпишник клиента, совершившего платеж, а не свой айпи. Решением было убрать айпи из настроек лейки и все заработало! 

Еще раз спасибо за хинт

**Comment by Ahaenor** [comment]
Ок, прекрасно.

Обычно сравнения с IP платёжных операторов нужны для повышения безопасности транзакций. Но от них, конечно, можно отказаться в пользу простоты в обслуживании.
