### ISSUE TITLE
Как убрать копирайт? How to remove the copyright?

### ISSUE THREAD

**Issue by Setnad17** [Teplitsa/Leyka#94]
Нужно убрать копирайт и в форме оплаты, и при редиректе, везде.

Я ценю вклад разработчиков, но лучше я сделаю донат, чем буду показывать всем какими сервисами я пользуюсь.

Спасибо заранее за ответ.

Eng: It need to remove the copyright in the payment form, and on the redirect page, everywhere.

As for me it's better to donate rather than have a Leyka's copyright on my website.

Thank you in andvance.

**Comment by Ahaenor** [comment]
Добрый день. Спасибо за обращение.

Лейка является открытым и бесплатным продуктом, предназначенным для социально-ориентированных проектов и активистов.

Наличие "копирайта" (на самом деле, не его, а указания на сервис), должно служить даже не столько целям "пиара" (что бы под этим ни понималось), сколько распространению знаний о продукте и возможности получить от него пользу.

Распространение знаний о полезных и открытых интернет-сервисах и продуктах - важная часть миссии разработчиков. По этой причине мы не можем содействовать удалению ссылки из подвала платёжных форм. Наличие или отсутствие "пожертвования разработчикам" никак этого не меняет.

Однако Лейка является продуктом с открытым кодом, и вмешиваться в него - ваше право. Любой сколько-нибудь квалифицированный PHP-разработчик легко выполнит эту задачу для вас, даже без потери совместимости с будущими версиями плагина.
