### ISSUE TITLE
Когда обновится плагин для WordPress?

### ISSUE THREAD

**Issue by Setnad17** [Teplitsa/Leyka#96]
Видел, что вы добавили новые способы оплаты. Когда обновиться плагин под WordPress? Или вы советуете установить вручную с гитхаба? Спасибо.

**Comment by Ahaenor** [comment]
Добрый день.

1. Вы можете установить обновление из ветки master на гитхабе. Но в этом
случае мы крайне рекомендуем сделать бэкап плагина. Код в этой ветке, как
правило, стабилен, но гарантировать это мы не можем.

2. Новая официальная версия плагина выйдет не ранее, чем в конце февраля -
начале марта.

Л.

21 января 2016 г., 22:36 пользователь Setnad17 <notifications@github.com>
написал:
