### ISSUE TITLE
Страница кампаний

### ISSUE THREAD

**Issue by Setnad17** [Teplitsa/Leyka#98]
Здравствуйте,

1) Можно ли как то запретить доступ пользователям на страницу мойсайт.ру/campaign ?

2) Можно ли заменить как нибудь адрес " MySite.ru/campaign/название_кампании " на "  MySite.ru/название_кампании " ?

Спасибо!

**Comment by Ahaenor** [comment]
Добрый день.

1. Это возможно теми же средствами, что и для других типов записей в WordPress. Обратите внимание на поле "видимость" в блоке "опубликовать" на странице редактирования кампании.

2. Без вмешательства со стороны программистов это невозможно.
